#!/usr/bin/env python
"""Generate the three midterm sample-exam figures and VERIFY every numeric
answer used in the sample exam's solutions (asserts fail loudly if a solution
number drifts from the actual computation):
  fig-mt-centrality — the 5-node hand-computation graph (Q3)
  fig-mt-pagerank   — the 3-node directed graph for power iterations (Q4)
  fig-mt-wl         — two triangles vs one hexagon, the WL/GCN blind pair (Q6/Q17)
Run: python scripts/figgen/mt_figs.py
"""
from fractions import Fraction
from pathlib import Path

import networkx as nx
import numpy as np

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"


def write(name, body, aria, height=300):
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 {height}\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/mt_figs.py -->\n{body}\n</svg>\n</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


def node(x, y, label, color="var(--dkr-blue, #0f8377)", r=17):
    return (f'  <circle cx="{x}" cy="{y}" r="{r}" fill="{color}"/>\n'
            f'  <text x="{x}" y="{y + 5}" text-anchor="middle" font-family="{SANS}" '
            f'font-size="14" font-weight="700" fill="var(--dkr-bg, #fff)">{label}</text>')


def edge(x1, y1, x2, y2):
    return (f'  <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" '
            f'stroke="var(--dkr-muted, #8e8e9a)" stroke-width="2"/>')


# ════════════════ Q3 graph: A–B, A–C, B–C, C–D, D–E ════════════════════════
G3 = nx.Graph([("A", "B"), ("A", "C"), ("B", "C"), ("C", "D"), ("D", "E")])

assert dict(G3.degree()) == {"A": 2, "B": 2, "C": 3, "D": 2, "E": 1}
assert abs(nx.clustering(G3)["C"] - 1 / 3) < 1e-12, "clustering(C): neighbors {A,B,D}, one edge A–B → 1/3"
assert abs(nx.closeness_centrality(G3)["C"] - 0.8) < 1e-12, "closeness(C) = (n−1)/Σd = 4/(1+1+1+2) = 0.8"
btw = nx.betweenness_centrality(G3, normalized=False)
assert abs(btw["C"] - 4.0) < 1e-12, "betweenness(C): (A,D),(A,E),(B,D),(B,E) all route uniquely through C"
assert abs(btw["D"] - 3.0) < 1e-12, "betweenness(D): (A,E),(B,E),(C,E)"
print("Q3 verified: deg A2 B2 C3 D2 E1 · clustering(C)=1/3 · closeness(C)=0.8 · betweenness(C)=4, (D)=3")

POS = {"A": (150, 70), "B": (150, 210), "C": (300, 140), "D": (450, 140), "E": (600, 140)}
c3 = [f'  <text x="380" y="30" text-anchor="middle" font-family="{SANS}" font-size="13" '
      f'fill="var(--dkr-muted, #6e6e7a)">simple, undirected, unweighted — all edges shown</text>']
for a, b in G3.edges():
    (x1, y1), (x2, y2) = POS[a], POS[b]
    c3.append(edge(x1, y1, x2, y2))
for lbl, (x, y) in POS.items():
    c3.append(node(x, y, lbl))
write("fig-mt-centrality", "\n".join(c3),
      "A five-node graph: triangle A, B, C with a path C to D to E hanging off node C", height=270)


# ════════════════ Q4 graph: X→Y, Y→X, Y→Z, Z→X — power iterations ══════════
# column-stochastic M (columns = out-distributions); out-deg: X 1, Y 2, Z 1
M = np.array([[0.0, 0.5, 1.0],   # into X: half of Y, all of Z
              [1.0, 0.0, 0.0],   # into Y: all of X
              [0.0, 0.5, 0.0]])  # into Z: half of Y
r0 = np.array([1, 1, 1]) / 3
r1, r2 = M @ r0, M @ (M @ r0)
assert np.allclose(r1, [1 / 2, 1 / 3, 1 / 6]), f"iteration 1: {r1}"
assert np.allclose(r2, [1 / 3, 1 / 2, 1 / 6]), f"iteration 2: {r2}"
fix = np.array([2 / 5, 2 / 5, 1 / 5])
assert np.allclose(M @ fix, fix), "fixed point (2/5, 2/5, 1/5)"
print("Q4 verified: r1=(1/2,1/3,1/6) · r2=(1/3,1/2,1/6) · fixed point (2/5,2/5,1/5)")


def arrow_arc(x1, y1, x2, y2, bend):
    """Curved directed edge, trimmed at both ends so the tail leaves the source
    rim and the head lands clear of the target rim."""
    mx, my = (x1 + x2) / 2, (y1 + y2) / 2
    nxv, nyv = -(y2 - y1), (x2 - x1)
    cx, cy = mx + bend * nxv, my + bend * nyv

    def toward(px, py, qx, qy, dist):
        d = ((qx - px) ** 2 + (qy - py) ** 2) ** 0.5 or 1
        return px + (qx - px) / d * dist, py + (qy - py) / d * dist

    sx, sy = toward(x1, y1, cx, cy, 20)     # start just outside the source rim
    tx, ty = toward(x2, y2, cx, cy, 24)     # head clears the target rim
    return (f'  <path d="M {sx:.1f} {sy:.1f} Q {cx:.1f} {cy:.1f} {tx:.1f} {ty:.1f}" fill="none" '
            f'stroke="var(--dkr-muted, #8e8e9a)" stroke-width="2" marker-end="url(#mt-arr)"/>')


def arrow_lane(x1, y1, x2, y2, offset):
    """Straight directed edge shifted `offset` px perpendicular to the segment —
    two opposite lanes make an X↔Y pair read as two roads, not one line."""
    dx, dy = x2 - x1, y2 - y1
    ln = (dx ** 2 + dy ** 2) ** 0.5
    ux, uy = dx / ln, dy / ln
    nx_, ny_ = -uy, ux
    ax, ay = x1 + nx_ * offset, y1 + ny_ * offset
    bx, by = x2 + nx_ * offset, y2 + ny_ * offset
    sx, sy = ax + ux * 16, ay + uy * 16     # trim: lane passes 13 px off-center,
    tx, ty = bx - ux * 16, by - uy * 16     # 16 px along-track clears an r=17 node
    return (f'  <path d="M {sx:.1f} {sy:.1f} L {tx:.1f} {ty:.1f}" fill="none" '
            f'stroke="var(--dkr-muted, #8e8e9a)" stroke-width="2" marker-end="url(#mt-arr)"/>')


# wide symmetric triangle; the X↔Y two-cycle is drawn as two offset lanes and
# every arrowhead lands on its own sector of the target's rim — direction is
# the exam content, so the geometry must read at a glance
PP = {"X": (170, 135), "Y": (570, 70), "Z": (570, 235)}
pr = ['''  <defs><marker id="mt-arr" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
    <path d="M 0 0 L 10 5 L 0 10 z" fill="var(--dkr-muted, #8e8e9a)"/></marker></defs>''']
pr.append(f'  <text x="380" y="30" text-anchor="middle" font-family="{SANS}" font-size="13" '
          f'fill="var(--dkr-muted, #6e6e7a)">directed, unweighted — a link passes importance to the page it points at</text>')
pr.append(arrow_lane(*PP["X"], *PP["Y"], offset=13))    # X→Y: lower lane
pr.append(arrow_lane(*PP["Y"], *PP["X"], offset=13))    # Y→X: upper lane (same side flips with direction)
pr.append(arrow_arc(*PP["Y"], *PP["Z"], bend=-0.16))    # Y→Z: bows right, outside
pr.append(arrow_arc(*PP["Z"], *PP["X"], bend=-0.30))    # Z→X: bows under, head lands low on X
for lbl, (x, y) in PP.items():
    pr.append(node(x, y, lbl, color="var(--dkr-accent, #d9603b)"))
write("fig-mt-pagerank", "\n".join(pr),
      "A three-node directed graph: X points to Y, Y points back to X and on to Z, and Z points to X",
      height=310)


# ════════════════ Q6/Q17: two triangles vs one hexagon (WL-blind pair) ═════
def wl_hist(g, rounds=3):
    colors = {v: 0 for v in g}
    hists = []
    for _ in range(rounds):
        colors = {v: hash((colors[v], tuple(sorted(colors[u] for u in g[v])))) for v in g}
        hists.append(sorted(__import__("collections").Counter(colors.values()).values()))
    return hists


G_tri = nx.disjoint_union(nx.cycle_graph(3), nx.cycle_graph(3))
G_hex = nx.cycle_graph(6)
assert wl_hist(G_tri) == wl_hist(G_hex), "WL color histograms identical every round — the blind pair"
assert not nx.is_isomorphic(G_tri, G_hex), "…and yet the graphs are genuinely different"
print("Q6 verified: WL histograms equal for C3∪C3 vs C6 at every round; graphs non-isomorphic")

wl = [f'  <text x="380" y="30" text-anchor="middle" font-family="{SANS}" font-size="13" '
      f'fill="var(--dkr-muted, #6e6e7a)">every node in both graphs has degree 2 — six nodes each, no labels</text>']
import math
# cy 164 (not 150): a triangle's bounding box is asymmetric about its center,
# so 164 puts the triangles' optical midline level with the hexagon's
tri1 = [(130 + 55 * math.cos(a), 164 + 55 * math.sin(a)) for a in
        (-math.pi / 2, math.pi / 6, 5 * math.pi / 6)]
tri2 = [(300 + 55 * math.cos(a), 164 + 55 * math.sin(a)) for a in
        (-math.pi / 2, math.pi / 6, 5 * math.pi / 6)]
hexn = [(590 + 62 * math.cos(a), 150 + 62 * math.sin(a)) for a in
        (math.pi / 6 + k * math.pi / 3 for k in range(6))]
for ring in (tri1, tri2, hexn):
    for i in range(len(ring)):
        (x1, y1), (x2, y2) = ring[i], ring[(i + 1) % len(ring)]
        wl.append(edge(round(x1, 1), round(y1, 1), round(x2, 1), round(y2, 1)))
    for x, y in ring:
        wl.append(f'  <circle cx="{round(x, 1)}" cy="{round(y, 1)}" r="11" fill="var(--dkr-blue, #0f8377)"/>')
wl.append(f'  <text x="215" y="248" text-anchor="middle" font-family="{SANS}" font-size="13" '
          f'font-weight="700" fill="var(--dkr-text, #1c1c21)">G&#x2081; — two triangles</text>')
wl.append(f'  <text x="590" y="248" text-anchor="middle" font-family="{SANS}" font-size="13" '
          f'font-weight="700" fill="var(--dkr-text, #1c1c21)">G&#x2082; — one hexagon</text>')
write("fig-mt-wl", "\n".join(wl),
      "Two graphs side by side: G1 is two disjoint triangles, G2 is a single hexagon; every node in both has degree two",
      height=280)


# ════════════════ remaining sample-exam numbers (no figures) ═══════════════
# Q1: weighted adjacency matrix → average degree
W = np.array([[0, 1.5, 0, 2.0], [1.5, 0, 0.5, 0], [0, 0.5, 0, 3.0], [2.0, 0, 3.0, 0]])
assert (W == W.T).all() and np.count_nonzero(W) // 2 == 4, "4 undirected edges"
assert abs(2 * 4 / 4 - 2.0) < 1e-12, "average degree 2E/N = 2"
print("Q1 verified: 4 edges, average degree 2")

# Q15: one GCN propagation on the path 1–2–3, x = (1,0,0)
A = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]], dtype=float)
At = A + np.eye(3)
d = At.sum(1)
Ahat = np.diag(d ** -0.5) @ At @ np.diag(d ** -0.5)
x = np.array([1.0, 0.0, 0.0])
out = Ahat @ x
assert np.allclose(out, [0.5, 1 / np.sqrt(6), 0.0]), f"Âx = {out}"
print(f"Q15 verified: Âx = (1/2, 1/√6, 0) ≈ ({out[0]:.3f}, {out[1]:.3f}, {out[2]:.3f})")

# Q10: TransE hand scores
h, r = np.array([1.0, 0.0]), np.array([0.0, 1.0])
t_good, t_bad = np.array([1.0, 1.0]), np.array([3.0, 2.0])
s_good, s_bad = np.linalg.norm(h + r - t_good), np.linalg.norm(h + r - t_bad)
assert s_good == 0.0 and abs(s_bad - np.sqrt(5)) < 1e-12
print(f"Q10 verified: scores 0 and √5 ≈ {s_bad:.3f}")

# Q12: raw vs filtered rank (higher score = better)
scores = {"t1": 0.9, "t2": 0.8, "t3": 0.7, "t4": 0.6, "t5": 0.5}   # gold = t3
raw = 1 + sum(1 for k, v in scores.items() if v > scores["t3"])
filt = 1 + sum(1 for k, v in scores.items() if v > scores["t3"] and k not in {"t1"})
assert (raw, filt) == (3, 2)
print("Q12 verified: raw rank 3, filtered rank 2 (t1 is a known true tail)")

print("\nall midterm sample-exam numbers verified")
