#!/usr/bin/env python
"""Generate assets/figures/fig-permutation.html from the cast graph's edge list.

Protocol F1 rule: data-derived content (the two adjacency matrices) is computed here,
never hand-placed. Re-run after any change: python scripts/figgen/permutation.py
"""
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "assets" / "figures" / "fig-permutation.html"

# The cast graph (docs/figure-style.md): identities 0..5 = A..F
EDGES = [(0, 1), (0, 2), (0, 3), (1, 2), (2, 4), (2, 5), (4, 5)]
COLORS = ["#d9a62e", "#cf4a30", "#199473", "#7c5cd6", "#d1567e", "#0f8377"]
POS = [(185, 150), (330, 62), (430, 168), (105, 252), (345, 268), (565, 248)]

ORDERS = {  # identity -> storage slot (0-based)
    "1": {"map": list(range(6)), "title": "storage order 1: A,B,C,D,E,F", "color": "var(--dkr-accent, #b84a2b)", "fill": "var(--dkr-accent, #d9603b)"},
    "2": {"map": [5 - i for i in range(6)], "title": "storage order 2: F,E,D,C,B,A", "color": "var(--dkr-blue-dark, #0a5f56)", "fill": "var(--dkr-blue, #0f8377)"},
}

CELL = 15


def matrix_cells(slot_of, fill):
    cells = []
    for a, b in EDGES:
        for i, j in ((slot_of[a], slot_of[b]), (slot_of[b], slot_of[a])):
            cells.append(f'<rect x="{j * CELL}" y="{i * CELL}" width="{CELL}" height="{CELL}" fill="{fill}" opacity="0.85"/>')
    return "\n      ".join(cells)


def grid_lines():
    n = 6 * CELL
    ls = [f'<rect x="0" y="0" width="{n}" height="{n}"/>']
    for k in range(1, 6):
        ls.append(f'<line x1="{k * CELL}" y1="0" x2="{k * CELL}" y2="{n}"/>')
        ls.append(f'<line x1="0" y1="{k * CELL}" x2="{n}" y2="{k * CELL}"/>')
    return "\n      ".join(ls)


def graph_group(order_key, ty):
    o = ORDERS[order_key]
    parts = [f'<g transform="translate(16,{ty}) scale(0.5)">']
    parts.append('  <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="3" opacity="0.7">')
    for a, b in EDGES:
        (x1, y1), (x2, y2) = POS[a], POS[b]
        parts.append(f'    <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}"/>')
    parts.append("  </g>")
    parts.append('  <g font-family="\'Source Sans 3\', sans-serif" font-weight="700" font-size="26" text-anchor="middle">')
    for ident in range(6):
        x, y = POS[ident]
        slot = o["map"][ident] + 1
        parts.append(f'    <circle cx="{x}" cy="{y}" r="27" fill="{COLORS[ident]}"/>')
        parts.append(f'    <text x="{x}" y="{y + 9}" fill="#fff">{slot}</text>')
    parts.append("  </g>")
    parts.append("</g>")
    return "\n  ".join(parts)


def matrix_group(order_key, ty):
    o = ORDERS[order_key]
    slot_of = o["map"]
    row_names = [""] * 6
    for ident, slot in enumerate(slot_of):
        row_names[slot] = "ABCDEF"[ident]
    labels = "\n      ".join(
        f'<text x="-10" y="{i * CELL + 12}" text-anchor="end" font-size="12" fill="var(--dkr-muted, #8e8e9a)">{n}</text>'
        for i, n in enumerate(row_names))
    return f"""<g transform="translate(432,{ty})" font-family="'Source Sans 3', sans-serif">
    <text x="45" y="-12" text-anchor="middle" font-size="13.5" font-weight="700" fill="{o['color']}">{'A₁' if order_key == '1' else 'A₂ = P A₁ Pᵀ'}</text>
    <g>
      {matrix_cells(slot_of, o['fill'])}
    </g>
    <g stroke="var(--dkr-border, #d5d4cf)" stroke-width="1" fill="none">
      {grid_lines()}
    </g>
    <g>
      {labels}
    </g>
  </g>"""


svg = f"""```{{=html}}
<figure class="dkr-fig">
<svg viewBox="0 0 760 420" role="img" aria-label="The same six-node graph stored under two node orders yields two different adjacency matrices; a correct model must not care which one it received">
  <!-- generated by scripts/figgen/permutation.py — do not edit the matrices by hand -->
  <g font-family="'Source Sans 3', sans-serif" font-size="14.5" font-weight="700">
    <text x="26" y="30" fill="{ORDERS['1']['color']}">{ORDERS['1']['title']}</text>
    <text x="26" y="230" fill="{ORDERS['2']['color']}">{ORDERS['2']['title']}</text>
  </g>

  {graph_group('1', 44)}
  {matrix_group('1', 74)}

  {graph_group('2', 244)}
  {matrix_group('2', 274)}

  <g font-family="'Source Sans 3', sans-serif" text-anchor="middle">
    <rect x="580" y="130" width="164" height="140" rx="12" fill="var(--dkr-paper, #fff)" stroke="var(--dkr-border, #d5d4cf)" stroke-width="1.4"/>
    <text x="662" y="160" font-size="14.5" font-weight="700" fill="var(--dkr-text, #1c1c21)">same graph,</text>
    <text x="662" y="180" font-size="14.5" font-weight="700" fill="var(--dkr-text, #1c1c21)">same colors —</text>
    <text x="662" y="200" font-size="13" fill="var(--dkr-muted, #8e8e9a)">only the storage</text>
    <text x="662" y="217" font-size="13" fill="var(--dkr-muted, #8e8e9a)">order moved.</text>
    <text x="662" y="246" font-size="13.5" font-weight="700" fill="var(--dkr-accent, #b84a2b)">a correct model</text>
    <text x="662" y="263" font-size="13.5" font-weight="700" fill="var(--dkr-accent, #b84a2b)">must not care</text>
  </g>

  <g font-family="'Source Sans 3', sans-serif" font-size="13.5" fill="var(--dkr-muted, #8e8e9a)" text-anchor="middle">
    <text x="380" y="410">numbers on the nodes = the row each node occupies in that storage order</text>
  </g>
</svg>
</figure>
```
"""

OUT.write_text(svg, encoding="utf-8")
print(f"wrote {OUT}")
