#!/usr/bin/env python
"""Generate assets/figures/fig-w1-representations.html — the cast graph next to its
three storage representations (adjacency matrix, adjacency list, edge list/COO),
all derived from the one edge list below. Run: python scripts/figgen/representations.py
"""
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "assets" / "figures" / "fig-w1-representations.html"

EDGES = [(0, 1), (0, 2), (0, 3), (1, 2), (2, 4), (2, 5), (4, 5)]   # the cast graph
NAMES = "ABCDEF"
COLORS = ["#d9a62e", "#cf4a30", "#199473", "#7c5cd6", "#d1567e", "#0f8377"]
POS = [(185, 150), (330, 62), (430, 168), (105, 252), (345, 268), (565, 248)]
N, CELL = 6, 20

adj = {i: [] for i in range(N)}
for a, b in EDGES:
    adj[a].append(b)
    adj[b].append(a)
for k in adj:
    adj[k].sort()

# matrix cells
cells = []
for a, b in EDGES:
    for i, j in ((a, b), (b, a)):
        cells.append(f'<rect x="{j*CELL}" y="{i*CELL}" width="{CELL}" height="{CELL}" fill="var(--dkr-blue, #0f8377)" opacity="0.8"/>')
cells = "\n      ".join(cells)
grid = [f'<rect x="0" y="0" width="{N*CELL}" height="{N*CELL}"/>']
for k in range(1, N):
    grid.append(f'<line x1="{k*CELL}" y1="0" x2="{k*CELL}" y2="{N*CELL}"/>')
    grid.append(f'<line x1="0" y1="{k*CELL}" x2="{N*CELL}" y2="{k*CELL}"/>')
grid = "\n      ".join(grid)
mlabels = "\n      ".join(
    f'<text x="-8" y="{i*CELL+15}" text-anchor="end">{NAMES[i]}</text>'
    f'<text x="{i*CELL+10}" y="-7" text-anchor="middle">{NAMES[i]}</text>' for i in range(N))

# adjacency list lines
alist = "\n      ".join(
    f'<text x="0" y="{i*21}"><tspan font-weight="700" fill="{COLORS[i]}">{NAMES[i]}</tspan>'
    f'<tspan fill="var(--dkr-text, #1c1c21)"> → {", ".join(NAMES[j] for j in adj[i])}</tspan></text>'
    for i in range(N))

# COO rows
src = "  ".join(str(a) for a, _ in EDGES)
dst = "  ".join(str(b) for _, b in EDGES)

graph_edges = "\n      ".join(
    f'<line x1="{POS[a][0]}" y1="{POS[a][1]}" x2="{POS[b][0]}" y2="{POS[b][1]}"/>' for a, b in EDGES)
graph_nodes = "\n      ".join(
    f'<circle cx="{POS[i][0]}" cy="{POS[i][1]}" r="26" fill="{COLORS[i]}"/>'
    f'<text x="{POS[i][0]}" y="{POS[i][1]+8}" fill="#fff">{NAMES[i]}</text>' for i in range(N))

svg = f"""```{{=html}}
<figure class="dkr-fig">
<svg viewBox="0 0 760 275" role="img" aria-label="One graph, three storages: the cast graph beside its adjacency matrix, its adjacency list, and its edge list in COO form">
  <!-- generated by scripts/figgen/representations.py — one edge list drives everything -->
  <g transform="translate(6,40) scale(0.42)">
    <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="3.5" opacity="0.7">
      {graph_edges}
    </g>
    <g font-family="'Source Sans 3', sans-serif" font-weight="700" font-size="24" text-anchor="middle">
      {graph_nodes}
    </g>
  </g>
  <text x="130" y="26" text-anchor="middle" font-family="'Source Sans 3', sans-serif" font-size="13.5" font-weight="700" fill="var(--dkr-text, #1c1c21)">one graph…</text>

  <g font-family="'Source Sans 3', sans-serif">
    <text x="470" y="26" text-anchor="middle" font-size="13.5" font-weight="700" fill="var(--dkr-text, #1c1c21)">…three ways to store it</text>

    <!-- adjacency matrix card -->
    <g transform="translate(310,70)">
      <text x="60" y="-26" text-anchor="middle" font-size="12.5" font-weight="700" fill="var(--dkr-blue-dark, #0a5f56)">adjacency matrix A</text>
      <g>
        {cells}
      </g>
      <g stroke="var(--dkr-border, #d5d4cf)" stroke-width="1" fill="none">
        {grid}
      </g>
      <g font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">
        {mlabels}
      </g>
      <text x="60" y="146" text-anchor="middle" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">n² = 36 slots</text>
    </g>

    <!-- adjacency list card -->
    <g transform="translate(478,86)" font-size="13.5">
      <text x="52" y="-42" text-anchor="middle" font-size="12.5" font-weight="700" fill="var(--dkr-blue-dark, #0a5f56)">adjacency list</text>
      {alist}
      <text x="52" y="130" text-anchor="middle" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">n + 2m = 20 entries</text>
    </g>

    <!-- edge list / COO card -->
    <g transform="translate(614,86)" font-family="'JetBrains Mono', monospace" font-size="12">
      <text x="64" y="-42" text-anchor="middle" font-family="'Source Sans 3', sans-serif" font-size="12.5" font-weight="700" fill="var(--dkr-blue-dark, #0a5f56)">edge list (COO)</text>
      <text x="0" y="0"  fill="var(--dkr-muted, #6e6e7a)">src</text><text x="34" y="0"  fill="var(--dkr-text, #1c1c21)">{src}</text>
      <text x="0" y="22" fill="var(--dkr-muted, #6e6e7a)">dst</text><text x="34" y="22" fill="var(--dkr-text, #1c1c21)">{dst}</text>
      <text x="64" y="52" text-anchor="middle" font-family="'Source Sans 3', sans-serif" font-size="12.5" fill="var(--dkr-accent, #b84a2b)" font-weight="600">= PyG's edge_index</text>
      <text x="64" y="130" text-anchor="middle" font-family="'Source Sans 3', sans-serif" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">2m = 14 entries</text>
    </g>
  </g>

  <g font-family="'Source Sans 3', sans-serif" font-size="13.5" fill="var(--dkr-muted, #6e6e7a)" text-anchor="middle">
    <text x="380" y="258">same information, wildly different costs — at n = 2.4 M the matrix needs terabytes, the edge list fits in RAM</text>
  </g>
</svg>
</figure>
```
"""
OUT.write_text(svg, encoding="utf-8")
print("wrote", OUT)
