#!/usr/bin/env python
"""Generate the four Week 10 figures and VERIFY the typed-message-passing hand
computation plus every parameter count the lecture states:
  fig-w10-hetero — the academic heterogeneous graph: schema + instance
  fig-w10-rgcn   — one R-GCN layer at paper P1, every number worked
  fig-w10-params — parameter count vs number of relations: full / basis / block
                   (computed curves, FB15k-237 marked at 237)
  fig-w10-encdec — lookup vs R-GCN encoder into the SAME DistMult decoder,
                   with our measured MRRs baked in
Measured numbers: scripts/experiments/w10_experiment3.py (the consistent ±0.06-init
series), FB15k-237, Lab-4 protocol (margin loss, 2,000 test facts, both
directions, filtered), 2026-08-22:
  TransE 5ep/7s MRR 0.178 H@10 0.301 · DistMult 5ep/7s 0.179/0.311
  (15ep DEGRADES to 0.145) · RGCN(basis 30)+DistMult 5ep/156s 0.126/0.257
  (15ep/1143s flat at 0.122)
Run: python scripts/figgen/w10_figs.py
"""
from pathlib import Path

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"

ACC = "var(--dkr-accent, #d9603b)"
TEAL = "var(--dkr-blue, #0f8377)"
GOLD = "var(--dkr-yellow, #d9a62e)"
GREEN = "var(--dkr-green, #199473)"
PURPLE = "#7c5cd6"
MUTED = "var(--dkr-muted, #6e6e7a)"
TEXT = "var(--dkr-text, #1c1c21)"
BG = "var(--dkr-bg, #fff)"


def write(name, body, aria, height=400):
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 {height}\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/w10_figs.py -->\n{body}\n</svg>\n</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


# ══════════════ verify the worked R-GCN update at P1 ═══════════════════════
H = {"A1": 1.0, "A2": 2.0, "P1": 1.0, "P2": 3.0, "V": 2.0}
W = {"self": 1.0, "writes": 0.5, "cites": 1.0, "pub_inv": 0.25}
typed = (W["self"] * H["P1"]
         + W["writes"] * (H["A1"] + H["A2"]) / 2
         + W["cites"] * H["P2"] / 1
         + W["pub_inv"] * H["V"] / 1)
assert abs(typed - 5.25) < 1e-12, typed
untyped = 1.0 * H["P1"] + 0.5 * (H["A1"] + H["A2"] + H["P2"] + H["V"]) / 4
assert abs(untyped - 2.0) < 1e-12, untyped
print(f"R-GCN hand update verified: typed {typed} vs untyped {untyped}")

# ══════════════ verify every parameter count ═══════════════════════════════
d, R, B = 100, 237, 30
full = (2 * R + 1) * d * d                       # per-relation + self, both directions
basis = B * d * d + (2 * R) * B + d * d          # bases + coefficients + self
block10 = (2 * R) * (d * d // 10) + d * d        # 10 blocks of (d/10)² each + self
assert full == 4_750_000 and basis == 324_220 and block10 == 484_000
assert round(full / basis, 1) == 14.7
print(f"params verified: full {full:,} · basis-30 {basis:,} ({full / basis:.1f}x less) · block-10 {block10:,}")


# ══════════════ figure 1: the heterogeneous academic graph ═════════════════
def node(g, x, y, label, color, r=15, fs=12.5, txtcol=None):
    g.append(f'  <circle cx="{x}" cy="{y}" r="{r}" fill="{color}"/>')
    g.append(f'  <text x="{x}" y="{y + 4}" text-anchor="middle" font-family="{SANS}" '
             f'font-size="{max(fs, 11)}" font-weight="700" fill="{txtcol or BG}">{label}</text>')


het = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
       f'left: the schema (types and allowed edges) · right: one instance — the same nodes your papers live in</text>']
# schema panel — matching cards on BOTH panels so neither floats
het.append(f'  <rect x="14" y="44" width="316" height="252" rx="12" fill="{MUTED}" opacity="0.06"/>')
het.append(f'  <rect x="366" y="44" width="380" height="252" rx="12" fill="{MUTED}" opacity="0.06"/>')
for x, y, lbl, c in [(110, 90, "author", GOLD), (110, 180, "paper", TEAL), (250, 180, "venue", ACC), (250, 90, "term", PURPLE)]:
    het.append(f'  <rect x="{x - 48}" y="{y - 20}" width="96" height="40" rx="10" fill="{c}" opacity="0.14"/>')
    het.append(f'  <rect x="{x - 48}" y="{y - 20}" width="96" height="40" rx="10" fill="none" stroke="{c}" stroke-width="2"/>')
    het.append(f'  <text x="{x}" y="{y + 5}" text-anchor="middle" font-family="{SANS}" font-size="13.5" font-weight="700" fill="{TEXT}">{lbl}</text>')
for x1, y1, x2, y2, lbl, lx, ly in [
        (110, 110, 110, 160, "writes", 78, 138),
        (158, 180, 202, 180, "published_in", 180, 214),
        (158, 90, 202, 90, "mentions⁻¹", 180, 62),
        (86, 160, 86, 110, "", 0, 0)]:
    if lbl or True:
        het.append(f'  <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{MUTED}" stroke-width="1.8" marker-end="url(#w10-arr)"/>')
    if lbl:
        het.append(f'  <text x="{lx}" y="{ly}" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="{MUTED}">{lbl}</text>')
het.append(f'  <path d="M 62 180 C 30 150 30 120 62 96" fill="none" stroke="{MUTED}" stroke-width="1.8" marker-end="url(#w10-arr)"/>')
# halo (paint-order stroke) lifts the label off its own arc
het.append(f'  <text x="42" y="112" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="{MUTED}" '
           f'paint-order="stroke" stroke="{BG}" stroke-width="4">cites</text>')
het.append(f'  <text x="172" y="284" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="{MUTED}">4 node types · 4 edge types (+ inverses)</text>')
# instance panel — the toy used in every computation this week
POS = {"A1": (450, 84), "A2": (560, 84), "P1": (470, 174), "P2": (590, 174), "V": (530, 246)}
FEAT = {"A1": 1, "A2": 2, "P1": 1, "P2": 3, "V": 2}
COL = {"A1": GOLD, "A2": GOLD, "P1": TEAL, "P2": TEAL, "V": ACC}
EDGES = [("A1", "P1", "writes"), ("A2", "P1", "writes"), ("A2", "P2", "writes"),
         ("P2", "P1", "cites"), ("P1", "V", "published_in"), ("P2", "V", "published_in")]
het.append('''  <defs><marker id="w10-arr" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto">
    <path d="M 0 0 L 10 5 L 0 10 z" fill="var(--dkr-muted, #8e8e9a)"/></marker></defs>''')
for a, b, rel in EDGES:
    (x1, y1), (x2, y2) = POS[a], POS[b]
    dx, dy = x2 - x1, y2 - y1
    ln = (dx * dx + dy * dy) ** 0.5
    sx, sy = x1 + dx / ln * 18, y1 + dy / ln * 18
    ex, ey = x2 - dx / ln * 20, y2 - dy / ln * 20
    dash = ' stroke-dasharray="5 3"' if rel == "cites" else ""
    col = GREEN if rel == "writes" else PURPLE if rel == "cites" else ACC
    het.append(f'  <line x1="{sx:.0f}" y1="{sy:.0f}" x2="{ex:.0f}" y2="{ey:.0f}" stroke="{col}" stroke-width="2"{dash} marker-end="url(#w10-arr)"/>')
for v, (x, y) in POS.items():
    node(het, x, y, v, COL[v])
    if v == "P1":
        # P1's upper-right is a three-arrowhead junction — label goes to the
        # free lower-left corner with a short leader, matching A1/A2/P2/V calm
        het.append(f'  <line x1="{x - 11}" y1="{y + 11}" x2="{x - 20}" y2="{y + 20}" stroke="{MUTED}" stroke-width="1"/>')
        het.append(f'  <text x="{x - 23}" y="{y + 28}" text-anchor="end" font-family="{MONO}" font-size="12.5" fill="{MUTED}">h={FEAT[v]}</text>')
    else:
        het.append(f'  <text x="{x + 24}" y="{y - 10}" font-family="{MONO}" font-size="12.5" fill="{MUTED}">h={FEAT[v]}</text>')
# legend centered under the instance, inside its card
het.append(f'  <g font-family="{SANS}" font-size="12.5">'
           f'<text x="440" y="284" fill="{GREEN}">— writes</text>'
           f'<text x="515" y="284" fill="{PURPLE}">-- cites</text>'
           f'<text x="583" y="284" fill="{ACC}">— published_in</text></g>')
write("fig-w10-hetero", "\n".join(het),
      "The heterogeneous academic graph: a schema panel with author, paper, venue, and term types connected by writes, published_in, mentions, and cites edges; and a five-node instance with scalar features used in this week's hand computations",
      height=310)

# ══════════════ figure 2: one R-GCN layer at P1, worked ════════════════════
rg = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'one R-GCN update at paper P&#x2081; — each relation brings its own W, its own normalization, its own voice</text>']
rows = [
    ("self", "W&#x2080; = 1", "h(P&#x2081;) = 1", "1 &#xD7; 1", "1.00", TEXT),
    ("writes", "W&#x2081; = &#xBD;", "mean{A&#x2081;, A&#x2082;} = 1.5", "&#xBD; &#xD7; 1.5", "0.75", GREEN),
    ("cites (in)", "W&#x2082; = 1", "h(P&#x2082;) = 3", "1 &#xD7; 3", "3.00", PURPLE),
    ("published_in&#x207B;&#xB9;", "W&#x2083; = &#xBC;", "h(V) = 2", "&#xBC; &#xD7; 2", "0.50", ACC),
]
y0 = 56
rg.append(f'  <g font-family="{SANS}" font-size="12" font-weight="700" fill="{MUTED}">'
          f'<text x="60" y="{y0}">relation channel</text><text x="250" y="{y0}">its weight</text>'
          f'<text x="390" y="{y0}">its (normalized) input</text><text x="580" y="{y0}">contribution</text></g>')
for i, (rel, w, inp, prod, val, col) in enumerate(rows):
    yy = y0 + 30 + i * 34
    if i % 2 == 0:
        rg.append(f'  <rect x="46" y="{yy - 17}" width="668" height="32" fill="{MUTED}" opacity="0.06"/>')
    rg.append(f'  <text x="60" y="{yy}" font-family="{SANS}" font-size="13" font-weight="700" fill="{col}">{rel}</text>')
    rg.append(f'  <text x="250" y="{yy}" font-family="{MONO}" font-size="12.5" fill="{TEXT}">{w}</text>')
    rg.append(f'  <text x="390" y="{yy}" font-family="{MONO}" font-size="12.5" fill="{TEXT}">{inp}</text>')
    rg.append(f'  <text x="580" y="{yy}" font-family="{MONO}" font-size="12.5" fill="{TEXT}">{prod} = {val}</text>')
ys = y0 + 30 + 4 * 34 + 8
rg.append(f'  <line x1="560" y1="{ys - 20}" x2="714" y2="{ys - 20}" stroke="{MUTED}" stroke-width="1.4"/>')
rg.append(f'  <text x="580" y="{ys}" font-family="{MONO}" font-size="13.5" font-weight="700" fill="{TEXT}">&#x3A3; = 5.25</text>')
rg.append(f'''  <g font-family="{SANS}">
    <rect x="70" y="{ys + 18}" width="620" height="30" rx="15" fill="{TEAL}"/>
    <text x="380" y="{ys + 38}" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">untyped baseline (one shared W = &#xBD;): 1 + &#xBD;&#xB7;mean{{1,2,3,2}} = 2.00 — citations can no longer shout</text>
  </g>''')
write("fig-w10-rgcn", "\n".join(rg),
      "A worked R-GCN update at paper P1: four relation channels (self, writes, incoming cites, inverse published_in) each with its own weight and normalization contribute 1.0, 0.75, 3.0, and 0.5, summing to 5.25 — while an untyped layer with one shared weight produces 2.0",
      height=ys + 66)

# ══════════════ figure 3: parameter counts, computed ═══════════════════════
import math
pm = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'per-layer parameters vs number of relations, d = 100 (log scale) — computed, not sketched</text>']
X0, X1, Y0, Y1 = 90, 700, 260, 60
RMAX = 500


def px(r):
    return X0 + (X1 - X0) * r / RMAX


def py(n):
    lo, hi = math.log10(3e4), math.log10(1e7)
    return Y0 - (Y0 - Y1) * (math.log10(n) - lo) / (hi - lo)


pm.append(f'  <line x1="{X0}" y1="{Y0}" x2="{X1}" y2="{Y0}" stroke="{MUTED}" stroke-width="1.4"/>')
pm.append(f'  <line x1="{X0}" y1="{Y0}" x2="{X0}" y2="{Y1 - 10}" stroke="{MUTED}" stroke-width="1.4"/>')
for n, lbl in [(1e5, "100k"), (1e6, "1M"), (1e7, "10M")]:
    pm.append(f'  <line x1="{X0 - 4}" y1="{py(n):.0f}" x2="{X1}" y2="{py(n):.0f}" stroke="{MUTED}" stroke-width="0.6" opacity="0.35"/>')
    pm.append(f'  <text x="{X0 - 10}" y="{py(n) + 4:.0f}" text-anchor="end" font-family="{MONO}" font-size="12.5" fill="{MUTED}">{lbl}</text>')
for r in (100, 237, 400):
    pm.append(f'  <text x="{px(r):.0f}" y="{Y0 + 18}" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="{MUTED}">{r}</text>')
# the x-axis carries a name, not just ticks
pm.append(f'  <text x="{X0 + 4}" y="{Y0 + 18}" font-family="{SANS}" font-size="12.5" font-style="italic" fill="{MUTED}">relations R</text>')
curves = [
    ("full: (2R+1)·d²", lambda r: (2 * r + 1) * d * d, ACC),
    ("block-10: 2R·d²/10 + d²", lambda r: (2 * r) * (d * d // 10) + d * d, PURPLE),
    ("basis-30: 30·d² + 2R·30 + d²", lambda r: 30 * d * d + 2 * r * 30 + d * d, GREEN),
]
for lbl, fn, col in curves:
    pts = " ".join(f"{px(r):.0f},{py(fn(r)):.1f}" for r in range(15, RMAX + 1, 5))
    pm.append(f'  <polyline points="{pts}" fill="none" stroke="{col}" stroke-width="2.4"/>')
pm.append(f'  <text x="{px(410):.0f}" y="{py((2 * 430 + 1) * d * d) - 8:.0f}" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{ACC}">full: (2R+1)&#xB7;d&#xB2;</text>')
pm.append(f'  <text x="{px(410):.0f}" y="{py((2 * 410) * (d * d // 10) + d * d) - 8:.0f}" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{PURPLE}">block-diag (10)</text>')
pm.append(f'  <text x="{px(410):.0f}" y="{py(30 * d * d + 2 * 410 * 30 + d * d) + 18:.0f}" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{GREEN}">basis (B=30)</text>')
xf = px(237)
pm.append(f'  <line x1="{xf:.0f}" y1="{Y0}" x2="{xf:.0f}" y2="{Y1}" stroke="{MUTED}" stroke-width="1.2" stroke-dasharray="4 3"/>')
pm.append(f'  <text x="{xf:.0f}" y="{Y1 - 14}" text-anchor="middle" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{TEXT}">FB15k-237</text>')
pm.append(f'''  <g font-family="{SANS}">
    <rect x="70" y="288" width="620" height="30" rx="15" fill="{GREEN}"/>
    <text x="380" y="308" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">at 237 relations: full 4.75M/layer &#x2192; basis-30 0.32M — 14.7&#xD7; fewer parameters, one design idea</text>
  </g>''')
write("fig-w10-params", "\n".join(pm),
      "Computed per-layer parameter counts against number of relations at hidden size 100, log scale: the full per-relation curve reaches 4.75 million at FB15k-237's 237 relations while basis decomposition with 30 bases stays near 0.32 million and block-diagonal sits between",
      height=330)

# ══════════════ figure 4: encoder–decoder showdown, measured ═══════════════
ed = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'same decoder, same loss, same filtered eval — the only change is where entity vectors come from</text>']
for x0, title, enc, col, mrr, h10, secs in [
        (60, "shallow pipeline", "lookup table E[v]", GOLD, "0.179", "0.311", "7 s"),
        (400, "encoder pipeline", "R-GCN over the graph", TEAL, "0.126", "0.257", "156 s")]:
    ed.append(f'  <rect x="{x0}" y="44" width="300" height="210" rx="12" fill="{col}" opacity="0.08"/>')
    ed.append(f'  <text x="{x0 + 150}" y="68" text-anchor="middle" font-family="{SANS}" font-size="13.5" font-weight="700" fill="{TEXT}">{title}</text>')
    for yy, txt, bold in [(96, enc, True), (140, "DistMult decoder &#x27E8;h, r, t&#x27E9;", False), (184, "filtered MRR / Hits@10", False)]:
        ed.append(f'  <rect x="{x0 + 30}" y="{yy - 16}" width="240" height="30" rx="8" fill="{BG}" opacity="0.55"/>')
        ed.append(f'  <rect x="{x0 + 30}" y="{yy - 16}" width="240" height="30" rx="8" fill="none" stroke="{col if bold else MUTED}" stroke-width="{2 if bold else 1.2}"/>')
        ed.append(f'  <text x="{x0 + 150}" y="{yy + 4}" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="{TEXT}">{txt}</text>')
        if yy < 184:
            ed.append(f'  <line x1="{x0 + 150}" y1="{yy + 14}" x2="{x0 + 150}" y2="{yy + 24}" stroke="{MUTED}" stroke-width="1.6" marker-end="url(#w10-arr2)"/>')
    ed.append(f'  <text x="{x0 + 150}" y="{232}" text-anchor="middle" font-family="{MONO}" font-size="13" font-weight="700" fill="{TEXT}">MRR {mrr} · H@10 {h10} · {secs}</text>')
ed.append('''  <defs><marker id="w10-arr2" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto">
    <path d="M 0 0 L 10 5 L 0 10 z" fill="var(--dkr-muted, #8e8e9a)"/></marker></defs>''')
ed.append(f'''  <g font-family="{SANS}">
    <rect x="60" y="272" width="640" height="30" rx="15" fill="{ACC}"/>
    <text x="380" y="292" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">measured, 5 epochs each: the lookup wins, at 1/22nd the compute — encoders are not free upgrades</text>
  </g>''')
write("fig-w10-encdec", "\n".join(ed),
      "Two knowledge-graph completion pipelines compared: a shallow lookup-table encoder and an R-GCN encoder both feeding the same DistMult decoder and the same filtered evaluation; measured at five epochs each the lookup scores MRR 0.179 in 7 seconds while the R-GCN scores 0.126 in 156 seconds",
      height=316)

print("\nall Week 10 numbers verified and baked")
