#!/usr/bin/env python
"""Generate the four Week 12 figures + bake the karate VGAE latent for the
w12-vgae widget. Measured numbers (scripts/experiments/w12_experiment.py, Cora, one
proper split, 2026-08-22): CN 0.724 · AA 0.725 · VGAE 0.903 · SEAL-lite
0.897 — and the LEAKY-label SEAL scored 0.363 (worse than random: the model
learned the leak and it anti-generalizes). Generation (GraphRNN-S on
2-community graphs, TV distance to held-out): degree 0.111 vs ER 0.152;
clustering 0.154 vs ER 0.596.
Run: python scripts/figgen/w12_figs.py
"""
import json
import math
from pathlib import Path

import networkx as nx
import numpy as np
import torch
import torch.nn.functional as F

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
D3DIR = Path(__file__).resolve().parents[2] / "assets" / "d3"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"
ACC = "var(--dkr-accent, #d9603b)"
TEAL = "var(--dkr-blue, #0f8377)"
GOLD = "var(--dkr-yellow, #d9a62e)"
GREEN = "var(--dkr-green, #199473)"
PURPLE = "#7c5cd6"
RED = "#cf4a30"
MUTED = "var(--dkr-muted, #6e6e7a)"
TEXT = "var(--dkr-text, #1c1c21)"
BG = "var(--dkr-bg, #fff)"

LADDER = [("common neighbors", 0.724, MUTED), ("Adamic–Adar", 0.725, GOLD),
          ("SEAL-lite (leak-free)", 0.897, PURPLE), ("VGAE", 0.903, TEAL)]
LEAKY = 0.363


def write(name, body, aria, height=400):
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 {height}\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/w12_figs.py -->\n{body}\n</svg>\n</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


# ═══════════ figure 1: the four-bucket link-prediction split ═══════════════
sp = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'every edge gets exactly one job — and the model may only ever SEE the message set</text>']
buckets = [
    (40, "message edges", TEAL, ["the graph the GNN", "propagates over —", "visible at all times"]),
    (215, "supervision edges", GREEN, ["training positives:", "scored, never", "propagated"]),
    (390, "validation edges", GOLD, ["tuning positives:", "hidden from messages", "AND from training loss"]),
    (565, "test edges", ACC, ["the exam:", "hidden from everything", "until the final scoring"]),
]
for x0, title, col, lines in buckets:
    sp.append(f'  <rect x="{x0}" y="48" width="155" height="128" rx="12" fill="{col}" opacity="0.10"/>')
    sp.append(f'  <rect x="{x0}" y="48" width="155" height="128" rx="12" fill="none" stroke="{col}" stroke-width="2"/>')
    sp.append(f'  <text x="{x0 + 77}" y="74" text-anchor="middle" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{col}">{title}</text>')
    for i, ln in enumerate(lines):
        sp.append(f'  <text x="{x0 + 77}" y="{100 + i * 20}" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{TEXT}">{ln}</text>')
rules = [
    ("test ∩ message = ∅", "or walks/messages deliver the answer (Week 3's +17 AUC leak)"),
    ("negatives drawn from NON-edges", "of the full graph — not just the message graph"),
    ("heuristics read the message graph only", "common-neighbors on the full graph is leakage too"),
]
for i, (rule, why) in enumerate(rules):
    yy = 214 + i * 30
    sp.append(f'  <text x="60" y="{yy}" font-family="{MONO}" font-size="12.5" font-weight="700" fill="{TEXT}">{rule}</text>')
    sp.append(f'  <text x="380" y="{yy}" font-family="{SANS}" font-size="12" fill="{MUTED}">{why}</text>')
write("fig-w12-splits", "\n".join(sp),
      "The four-bucket link prediction split: message edges the model propagates over, supervision edges used only as training targets, validation edges, and test edges hidden from everything, with the three anti-leakage rules stated",
      height=316)

# ═══════════ figure 2: the measured AUC ladder + the leak ══════════════════
ld = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'test AUC on Cora, one shared proper split — and what one labeling leak did to SEAL</text>']
X0 = 250
for i, (name, v, col) in enumerate(LADDER):
    yy = 60 + i * 48
    w = 420 * (v - 0.3) / 0.7
    ld.append(f'  <text x="{X0 - 12}" y="{yy + 14}" text-anchor="end" font-family="{SANS}" font-size="13" font-weight="700" fill="{col if col != MUTED else TEXT}">{name}</text>')
    ld.append(f'  <rect x="{X0}" y="{yy}" width="{w:.0f}" height="22" rx="6" fill="{col}" opacity="0.85"/>')
    ld.append(f'  <text x="{X0 + w + 8:.0f}" y="{yy + 15}" font-family="{MONO}" font-size="12.5" font-weight="700" fill="{TEXT}">{v:.3f}</text>')
yy = 60 + 4 * 48 + 8
wl = 420 * (LEAKY - 0.3) / 0.7
ld.append(f'  <text x="{X0 - 12}" y="{yy + 14}" text-anchor="end" font-family="{SANS}" font-size="13" font-weight="700" fill="{RED}">SEAL with the label leak</text>')
ld.append(f'  <rect x="{X0}" y="{yy}" width="{wl:.0f}" height="22" rx="6" fill="{RED}" opacity="0.75"/>')
ld.append(f'  <text x="{X0 + wl + 8:.0f}" y="{yy + 15}" font-family="{MONO}" font-size="12.5" font-weight="700" fill="{RED}">{LEAKY:.3f} — below random!</text>')
ld.append(f'  <line x1="{X0 + 420 * 0.2 / 0.7:.0f}" y1="52" x2="{X0 + 420 * 0.2 / 0.7:.0f}" y2="{yy + 30}" stroke="{MUTED}" stroke-width="1" stroke-dasharray="4 3"/>')
ld.append(f'  <text x="{X0 + 420 * 0.2 / 0.7:.0f}" y="{yy + 46}" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{MUTED}">0.5 = coin flip</text>')
ld.append(f'''  <g font-family="{SANS}">
    <rect x="70" y="{yy + 58}" width="620" height="30" rx="15" fill="{PURPLE}"/>
    <text x="380" y="{yy + 78}" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">the leaked feature exists only for TRAINING positives — at test the model votes backwards</text>
  </g>''')
write("fig-w12-ladder", "\n".join(ld),
      "Measured link prediction AUC on one shared Cora split: common neighbors 0.724, Adamic-Adar 0.725, leak-free SEAL-lite 0.897, VGAE 0.903 — and SEAL with a distance-label leak scoring 0.363, far below the 0.5 coin-flip line, because the leaked feature anti-generalizes",
      height=yy + 104)

# ═══════════ figure 3: SEAL pipeline with worked labels ════════════════════
se = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'SEAL: score the PAIR by classifying its neighborhood-as-a-graph — labels = distances to the two endpoints</text>']
# worked enclosing subgraph: a-b candidate, common neighbor c, a-only d, b-only e
POSN = {"a": (110, 120), "b": (270, 120), "c": (190, 60), "d": (60, 200), "e": (320, 200)}
LBL = {"a": "(0,1)", "b": "(1,0)", "c": "(1,1)", "d": "(1,2)", "e": "(2,1)"}
COLN = {"a": ACC, "b": ACC, "c": GREEN, "d": MUTED, "e": MUTED}
EDG = [("a", "c"), ("b", "c"), ("a", "d"), ("b", "e")]
for u, v in EDG:
    (x1, y1), (x2, y2) = POSN[u], POSN[v]
    se.append(f'  <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{MUTED}" stroke-width="2" opacity="0.6"/>')
se.append(f'  <line x1="{POSN["a"][0]}" y1="{POSN["a"][1]}" x2="{POSN["b"][0]}" y2="{POSN["b"][1]}" stroke="{RED}" stroke-width="2" stroke-dasharray="6 4"/>')
se.append(f'  <text x="190" y="140" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{RED}">the candidate — REMOVED everywhere</text>')
for v, (x, y) in POSN.items():
    se.append(f'  <circle cx="{x}" cy="{y}" r="15" fill="{COLN[v]}"/>')
    se.append(f'  <text x="{x}" y="{y + 4}" text-anchor="middle" font-family="{SANS}" font-size="12" font-weight="700" fill="{BG}">{v}</text>')
    se.append(f'  <text x="{x}" y="{y - 22}" text-anchor="middle" font-family="{MONO}" font-size="12" fill="{TEXT}">{LBL[v]}</text>')
steps = [
    ("1 · extract", "k-hop subgraph around (a, b)", TEAL),
    ("2 · label", "each node by (dist to a, dist to b)", GREEN),
    ("3 · classify", "a small GNN scores the labeled graph", PURPLE),
]
for i, (t1, t2, col) in enumerate(steps):
    x0 = 420
    yy = 60 + i * 62
    se.append(f'  <rect x="{x0}" y="{yy}" width="300" height="48" rx="10" fill="{col}" opacity="0.10"/>')
    se.append(f'  <rect x="{x0}" y="{yy}" width="300" height="48" rx="10" fill="none" stroke="{col}" stroke-width="2"/>')
    se.append(f'  <text x="{x0 + 14}" y="{yy + 20}" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{col}">{t1}</text>')
    se.append(f'  <text x="{x0 + 14}" y="{yy + 38}" font-family="{SANS}" font-size="12" fill="{TEXT}">{t2}</text>')
se.append(f'''  <g font-family="{SANS}">
    <rect x="70" y="252" width="620" height="30" rx="15" fill="{GREEN}"/>
    <text x="380" y="272" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">common neighbor c reads (1,1) — SEAL can COUNT those: heuristics become learnable</text>
  </g>''')
write("fig-w12-seal", "\n".join(se),
      "The SEAL pipeline on a worked example: extract the enclosing subgraph around candidate pair a and b with the candidate edge removed everywhere, label every node by its distances to a and to b so the common neighbor c reads one-one, then classify the labeled subgraph with a small GNN",
      height=300)

# ═══════════ figure 4: generation — autoregressive vs diffusion ════════════
ge = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'two ways to make a graph from nothing — and the measured verdict on community graphs</text>']
ge.append(f'  <text x="200" y="56" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="{TEAL}">autoregressive (GraphRNN)</text>')
# adjacency rows building up
for i in range(5):
    for j in range(i):
        filled = (i, j) in [(1, 0), (2, 1), (3, 1), (3, 2), (4, 0)]
        ge.append(f'  <rect x="{120 + j * 26}" y="{70 + i * 26}" width="22" height="22" rx="3" '
                  f'fill="{TEAL if filled else MUTED}" opacity="{0.85 if filled else 0.15}"/>')
    ge.append(f'  <text x="{120 + i * 26 + 11}" y="{70 + 5 * 26 + 16}" text-anchor="middle" font-family="{MONO}" font-size="12" fill="{MUTED}">{i + 1}</text>')
ge.append(f'  <text x="200" y="{70 + 5 * 26 + 40}" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{TEXT}">one row at a time: node i&#x2019;s edges to</text>')
ge.append(f'  <text x="200" y="{70 + 5 * 26 + 58}" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{TEXT}">earlier nodes, conditioned on history (RNN)</text>')
ge.append(f'  <text x="560" y="56" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="{PURPLE}">diffusion (DiGress)</text>')
stages = [1.0, 0.65, 0.3, 0.05]
gk = nx.gnp_random_graph(8, 0.35, seed=4)
pos8 = {v: (math.cos(2 * math.pi * v / 8), math.sin(2 * math.pi * v / 8)) for v in gk}
for si, noise in enumerate(stages):
    cx = 445 + si * 78
    rng2 = np.random.default_rng(si)
    for u, v in gk.edges():
        keep = rng2.random() > noise * 0.7
        if keep:
            ge.append(f'  <line x1="{cx + 26 * pos8[u][0]:.0f}" y1="{150 + 26 * pos8[u][1]:.0f}" '
                      f'x2="{cx + 26 * pos8[v][0]:.0f}" y2="{150 + 26 * pos8[v][1]:.0f}" '
                      f'stroke="{PURPLE}" stroke-width="1.4" opacity="{1 - 0.7 * noise:.2f}"/>')
    for v in gk:
        ge.append(f'  <circle cx="{cx + 26 * pos8[v][0]:.0f}" cy="{150 + 26 * pos8[v][1]:.0f}" r="4" fill="{PURPLE}" opacity="{1 - 0.5 * noise:.2f}"/>')
    if si < 3:
        ge.append(f'  <text x="{cx + 39}" y="154" text-anchor="middle" font-size="14" fill="{MUTED}">&#x2192;</text>')
ge.append(f'  <text x="560" y="216" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{TEXT}">start from noise; a GNN denoises all</text>')
ge.append(f'  <text x="560" y="234" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{TEXT}">edges and node types jointly, step by step</text>')
ge.append(f'  <g font-family="{MONO}" font-size="12.5">'
          f'<text x="120" y="292" fill="{TEXT}">measured (TV distance to held-out community graphs):</text></g>')
ge.append(f'  <text x="120" y="316" font-family="{MONO}" font-size="12.5" fill="{GREEN}">GraphRNN-S: degree 0.111 · clustering 0.154</text>')
ge.append(f'  <text x="450" y="316" font-family="{MONO}" font-size="12.5" fill="{RED}">ER baseline: 0.152 · 0.596</text>')
write("fig-w12-generate", "\n".join(ge),
      "Two graph generation paradigms: autoregressive GraphRNN builds the adjacency matrix one row at a time conditioned on history, while diffusion models denoise a random graph into a sample over several steps; measured on community graphs the trained GraphRNN's samples sit at total-variation distance 0.111 (degree) and 0.154 (clustering) from held-out graphs versus 0.152 and 0.596 for an Erdos-Renyi baseline",
      height=336)

# ═══════════ bake: karate VGAE 2-D latent for the widget ═══════════════════
G = nx.karate_club_graph()
A = nx.to_numpy_array(G, weight=None)
N = 34
eu = [(u, v) for u, v in G.edges()]
torch.manual_seed(0)
X = torch.eye(N)
ei = torch.tensor([[u for u, v in eu] + [v for u, v in eu],
                   [v for u, v in eu] + [u for u, v in eu]])
from torch_geometric.nn import GCNConv as _GCN
c1, cmu, clog = _GCN(N, 16), _GCN(16, 2), _GCN(16, 2)
opt = torch.optim.Adam(list(c1.parameters()) + list(cmu.parameters()) + list(clog.parameters()), lr=0.02)
pos = torch.tensor(eu).t()
gen = torch.Generator().manual_seed(0)
for ep in range(400):
    opt.zero_grad()
    h = F.relu(c1(X, ei))
    mu, logv = cmu(h, ei), clog(h, ei)
    z = mu + torch.randn_like(mu) * (0.5 * logv).exp()
    neg = torch.randint(N, (2, len(eu)), generator=gen)
    pl = (z[pos[0]] * z[pos[1]]).sum(1)
    nl = (z[neg[0]] * z[neg[1]]).sum(1)
    recon = F.binary_cross_entropy_with_logits(pl, torch.ones_like(pl)) + \
            F.binary_cross_entropy_with_logits(nl, torch.zeros_like(nl))
    kl = -0.5 / N * (1 + logv - mu ** 2 - logv.exp()).sum(1).mean()
    (recon + kl).backward()
    opt.step()
with torch.no_grad():
    h = F.relu(c1(X, ei))
    Zk = cmu(h, ei).numpy()
# sanity: reconstruction AUC on the training edges vs random non-edges
from sklearn.metrics import roc_auc_score
nonedges = [(u, v) for u in range(N) for v in range(u + 1, N) if not G.has_edge(u, v)]
rng3 = np.random.default_rng(0)
sel = rng3.choice(len(nonedges), len(eu), replace=False)
sc_p = [float(Zk[u] @ Zk[v]) for u, v in eu]
sc_n = [float(Zk[nonedges[i][0]] @ Zk[nonedges[i][1]]) for i in sel]
auc_k = roc_auc_score([1] * len(sc_p) + [0] * len(sc_n), sc_p + sc_n)
assert auc_k > 0.85, f"karate VGAE latent should reconstruct well (AUC {auc_k:.3f})"
print(f"karate VGAE 2-D latent baked (recon AUC {auc_k:.3f})")
payload = {"z": [[round(float(a), 3) for a in row] for row in Zk],
           "edges": eu, "auc": round(float(auc_k), 3)}
(D3DIR / "w12-vgae-data.js").write_text(
    "window.DKR_W12_VGAE = " + json.dumps(payload) + ";\n", encoding="utf-8")
print("wrote w12-vgae-data.js")

# copy widget sample graphs from the experiment export
import shutil
src = Path(__file__).resolve().parents[3] and None
print("\nall Week 12 figures baked")
