#!/usr/bin/env python
"""Generate the four Week 13 figures. Measured (scripts/experiments/w13_experiment.py,
ZINC-subset, 100 epochs, cosine LR, seed 0, course GPU, 2026-08-22):
  MPNN-only        test MAE 0.349  (188 s)
  MPNN + RWSE      test MAE 0.296  (194 s)   <- the encoding pays, ~free
  GPS-lite         test MAE 0.303  (529 s)   <- attention did NOT pay here
Hand RWSE on triangle(0,1,2)+tail(3): k2 = [.4167,.4167,.6667,.3333],
k3 = [.1667,.1667,.1667,0], k4 = [.2986,.2986,.5278,.2222].
Run: python scripts/figgen/w13_figs.py
"""
import math
from pathlib import Path

import networkx as nx
import numpy as np

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"
ACC = "var(--dkr-accent, #d9603b)"
TEAL = "var(--dkr-blue, #0f8377)"
GOLD = "var(--dkr-yellow, #d9a62e)"
GREEN = "var(--dkr-green, #199473)"
PURPLE = "#7c5cd6"
RED = "#cf4a30"
MUTED = "var(--dkr-muted, #6e6e7a)"
TEXT = "var(--dkr-text, #1c1c21)"
BG = "var(--dkr-bg, #fff)"

# verify the hand RWSE numbers
G = nx.Graph([(0, 1), (1, 2), (2, 0), (2, 3)])
A = nx.to_numpy_array(G)
M = A / A.sum(1, keepdims=True)
P = np.eye(4)
HAND = {}
for k in range(1, 5):
    P = P @ M
    HAND[k] = [round(float(P[i, i]), 4) for i in range(4)]
assert HAND[2] == [0.4167, 0.4167, 0.6667, 0.3333]
assert HAND[3] == [0.1667, 0.1667, 0.1667, 0.0], "the tail node CANNOT return in 3 steps: no triangle"
assert HAND[4] == [0.2986, 0.2986, 0.5278, 0.2222]
print("hand RWSE verified")

LADDER = [("MPNN-only (GINE ×4)", 0.349, 188, TEAL),
          ("MPNN + RWSE", 0.296, 194, GREEN),
          ("GPS-lite (∥ attention + RWSE)", 0.303, 529, PURPLE)]


def write(name, body, aria, height=400):
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 {height}\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/w13_figs.py -->\n{body}\n</svg>\n</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


# ═══════════ figure 1: locality vs attention ═══════════════════════════════
at = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'who can talk to whom in ONE layer — and what each convention costs</text>']
ring = [(120 + 62 * math.cos(-math.pi / 2 + k * math.pi / 4),
         150 + 62 * math.sin(-math.pi / 2 + k * math.pi / 4)) for k in range(8)]
ring2 = [(560 + 62 * math.cos(-math.pi / 2 + k * math.pi / 4),
          150 + 62 * math.sin(-math.pi / 2 + k * math.pi / 4)) for k in range(8)]
# left: MPNN — ring edges only, node 0 highlighted with its 1-hop reach
for k in range(8):
    x1, y1 = ring[k]; x2, y2 = ring[(k + 1) % 8]
    at.append(f'  <line x1="{x1:.0f}" y1="{y1:.0f}" x2="{x2:.0f}" y2="{y2:.0f}" stroke="{TEAL}" stroke-width="2" opacity="0.7"/>')
for k, (x, y) in enumerate(ring):
    hot = k in (0, 1, 7)
    at.append(f'  <circle cx="{x:.0f}" cy="{y:.0f}" r="{10 if k == 0 else 8}" fill="{TEAL}" opacity="{1 if hot else 0.35}"/>')
at.append(f'  <text x="120" y="252" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="{TEAL}">message passing: reach = my edges</text>')
at.append(f'  <text x="120" y="272" text-anchor="middle" font-family="{MONO}" font-size="12" fill="{MUTED}">cost per layer: O(E) · range: 1 hop</text>')
# right: attention — all pairs from node 0
for k in range(1, 8):
    x1, y1 = ring2[0]; x2, y2 = ring2[k]
    at.append(f'  <line x1="{x1:.0f}" y1="{y1:.0f}" x2="{x2:.0f}" y2="{y2:.0f}" stroke="{PURPLE}" stroke-width="1.6" opacity="0.55"/>')
for k in range(8):
    x1, y1 = ring2[k]; x2, y2 = ring2[(k + 1) % 8]
    at.append(f'  <line x1="{x1:.0f}" y1="{y1:.0f}" x2="{x2:.0f}" y2="{y2:.0f}" stroke="{MUTED}" stroke-width="1" opacity="0.25"/>')
for k, (x, y) in enumerate(ring2):
    at.append(f'  <circle cx="{x:.0f}" cy="{y:.0f}" r="{10 if k == 0 else 8}" fill="{PURPLE}" opacity="{1 if k == 0 else 0.75}"/>')
at.append(f'  <text x="560" y="252" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="{PURPLE}">attention: reach = everyone, at once</text>')
at.append(f'  <text x="560" y="272" text-anchor="middle" font-family="{MONO}" font-size="12" fill="{MUTED}">cost per layer: O(n&#xB2;) · the graph? gone</text>')
at.append(f'''  <g font-family="{SANS}">
    <rect x="70" y="292" width="620" height="30" rx="15" fill="{ACC}"/>
    <text x="380" y="312" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">attention deletes the edges along with the walls — the graph must re-enter as FEATURES</text>
  </g>''')
write("fig-w13-attention", "\n".join(at),
      "One layer's connectivity under message passing versus full attention on an eight-node ring: message passing reaches only the highlighted node's two neighbors at O(E) cost, attention connects it to all seven others at O(n squared) — discarding the graph structure, which must then be reintroduced as features",
      height=336)

# ═══════════ figure 2: RWSE by hand ════════════════════════════════════════
POS = {0: (110, 120), 1: (250, 120), 2: (180, 210), 3: (320, 210)}
rw = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'random-walk structural encoding: each node&#x2019;s return probabilities — computed by hand, k = 2, 3, 4</text>']
for a, b in G.edges():
    (x1, y1), (x2, y2) = POS[a], POS[b]
    rw.append(f'  <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{MUTED}" stroke-width="2" opacity="0.6"/>')
NODE_COL = {0: TEAL, 1: TEAL, 2: GOLD, 3: ACC}
for v, (x, y) in POS.items():
    rw.append(f'  <circle cx="{x}" cy="{y}" r="14" fill="{NODE_COL[v]}"/>')
    rw.append(f'  <text x="{x}" y="{y + 5}" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="{BG}">{v}</text>')
rw.append(f'  <g font-family="{SANS}" font-size="12" font-weight="700" fill="{MUTED}">'
          f'<text x="475" y="80">node</text><text x="545" y="80">k=2</text>'
          f'<text x="615" y="80">k=3</text><text x="685" y="80">k=4</text></g>')
for i, v in enumerate([0, 2, 3]):
    yy = 110 + i * 32
    lbl = {0: "0 (triangle)", 2: "2 (hub)", 3: "3 (tail)"}[v]
    rw.append(f'  <text x="475" y="{yy}" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{NODE_COL[v]}">{lbl}</text>')
    for j, k in enumerate((2, 3, 4)):
        val = HAND[k][v]
        hot = (k == 3)
        rw.append(f'  <text x="{545 + j * 70}" y="{yy}" font-family="{MONO}" font-size="12.5" '
                  f'{"font-weight=\"700\"" if hot else ""} fill="{TEXT}">{val:.3f}</text>')
rw.append(f'  <text x="380" y="262" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="{TEXT}">'
          f'k = 3 is the triangle detector: nodes 0, 1, 2 can walk their triangle home (1/6 each); node 3 cannot — exactly 0</text>')
rw.append(f'''  <g font-family="{SANS}">
    <rect x="90" y="280" width="580" height="30" rx="15" fill="{GREEN}"/>
    <text x="380" y="300" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">Week 9&#x2019;s return probabilities, renamed: the CSL-cracking numbers, now input features</text>
  </g>''')
write("fig-w13-rwse", "\n".join(rw),
      "Random-walk structural encoding computed by hand on a triangle with a tail: the k equals 3 return probability is one sixth for every triangle node and exactly zero for the tail node — the triangle detector — and these return probabilities are Week 9's CSL-cracking numbers used as input features",
      height=324)

# ═══════════ figure 3: Graphormer's three biases ═══════════════════════════
gr = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'Graphormer: a standard transformer, with the graph smuggled in through three doors</text>']
doors = [
    (40, "centrality encoding", GOLD, ["degree &#x2192; learned embedding,", "ADDED to node features:", "&#x201C;how important am I&#x201D;"]),
    (275, "spatial encoding", TEAL, ["shortest-path distance (u,v)", "&#x2192; learned scalar ADDED to the", "attention logit: a distance prior"]),
    (510, "edge encoding", PURPLE, ["edge features along the path", "&#x2192; a second logit bias:", "&#x201C;what lies between us&#x201D;"]),
]
for x0, title, col, lines in doors:
    gr.append(f'  <rect x="{x0}" y="44" width="210" height="118" rx="12" fill="{col}" opacity="0.10"/>')
    gr.append(f'  <rect x="{x0}" y="44" width="210" height="118" rx="12" fill="none" stroke="{col}" stroke-width="2"/>')
    gr.append(f'  <text x="{x0 + 105}" y="70" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="{col}">{title}</text>')
    for i, ln in enumerate(lines):
        gr.append(f'  <text x="{x0 + 105}" y="{96 + i * 20}" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{TEXT}">{ln}</text>')
gr.append(f'  <text x="380" y="196" text-anchor="middle" font-family="{MONO}" font-size="13" fill="{TEXT}">'
          f'attention(u, v) = softmax( q&#x1D64;&#xB7;k&#x1D65; / &#x221A;d  +  b&#x2081;[dist(u,v)]  +  b&#x2082;[edges on path] )</text>')
gr.append(f'  <text x="380" y="226" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="{MUTED}">'
          f'learn b&#x2081; decaying with distance and attention rediscovers locality; learn it flat and the graph dissolves —</text>')
gr.append(f'  <text x="380" y="244" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="{MUTED}">'
          f'message passing becomes one POINT in this model&#x2019;s hypothesis space, not a rival architecture</text>')
write("fig-w13-graphormer", "\n".join(gr),
      "Graphormer's three structural doors into a standard transformer: centrality encodings added to node features, shortest-path spatial biases added to attention logits, and edge encodings along paths as a second logit bias — with the attention formula showing both bias terms",
      height=262)

# ═══════════ figure 4: the measured ladder ═════════════════════════════════
ld = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'ZINC-subset, 100 epochs, same budget discipline — test MAE (lower is better) and the wall-clock bill</text>']
for i, (name, mae, secs, col) in enumerate(LADDER):
    yy = 62 + i * 56
    w = 470 * (0.42 - mae) / 0.15
    ld.append(f'  <text x="250" y="{yy + 4}" text-anchor="end" font-family="{SANS}" font-size="13" font-weight="700" fill="{col}">{name}</text>')
    ld.append(f'  <text x="250" y="{yy + 22}" text-anchor="end" font-family="{SANS}" font-size="12" fill="{MUTED}">{secs} s</text>')
    ld.append(f'  <rect x="262" y="{yy - 8}" width="{w:.0f}" height="24" rx="6" fill="{col}" opacity="0.85"/>')
    ld.append(f'  <text x="{262 + w + 8:.0f}" y="{yy + 9}" font-family="{MONO}" font-size="13" font-weight="700" fill="{TEXT}">{mae:.3f}</text>')
ld.append(f'  <text x="380" y="248" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="{MUTED}">'
          f'reference: heavily tuned GPS with ~10&#xD7; the schedule reports &#x2248;0.07 on this benchmark — budget moves everything</text>')
ld.append(f'''  <g font-family="{SANS}">
    <rect x="60" y="266" width="640" height="30" rx="15" fill="{GREEN}"/>
    <text x="380" y="286" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">at our budget the ENCODING paid (0.349&#x2192;0.296, free) and the attention did not (0.303 at 2.7&#xD7; the time)</text>
  </g>''')
write("fig-w13-results", "\n".join(ld),
      "The measured ZINC ladder at 100 epochs: MPNN-only reaches test MAE 0.349 in 188 seconds; adding random-walk structural encodings improves it to 0.296 at no extra cost; the GPS-lite hybrid with global attention lands at 0.303 while costing 529 seconds — at this budget the structural encoding paid and the attention did not",
      height=310)

print("\nall Week 13 figures verified and baked")
