#!/usr/bin/env python
"""Generate the four Week 14 figures. Measured (scripts/experiments/w14_experiment.py
+ w14_experiment2.py, MovieLens-100k, LightGCN d=64 BPR, seed 0, course GPU,
2026-08-22):
  global-temporal split (66 test users):
    popularity R@20 0.1655 · K=0 0.1562 · K=1 0.1749 · K=2 0.1851 · K=3 0.1953
  leave-last-out (940 users): popularity 0.1266 · K=3 0.2096
  random 80/10/10:            K=3 0.3462   <- the protocol lie: x1.77 vs temporal
Run: python scripts/figgen/w14_figs.py
"""
from pathlib import Path

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"
ACC = "var(--dkr-accent, #d9603b)"
TEAL = "var(--dkr-blue, #0f8377)"
GOLD = "var(--dkr-yellow, #d9a62e)"
GREEN = "var(--dkr-green, #199473)"
PURPLE = "#7c5cd6"
MUTED = "var(--dkr-muted, #6e6e7a)"
TEXT = "var(--dkr-text, #1c1c21)"
BG = "var(--dkr-bg, #fff)"

# measured constants (provenance in module docstring) + claim asserts
POP_T, K0, K1, K2, K3_T = 0.1655, 0.1562, 0.1749, 0.1851, 0.1953
POP_LLO, K3_LLO = 0.1266, 0.2096
K3_RAND = 0.3462
SECS = {0: 4, 1: 5, 2: 9, 3: 10}
assert round(K3_RAND / K3_T, 2) == 1.77, "inflation claim must match the measurement"
assert POP_T > K0, "the humbling: popularity beats K=0 (pure BPR-MF) on the temporal split"
assert K0 < K1 < K2 < K3_T, "each propagation layer pays on Recall@20"


def write(name, body, aria, height=400):
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 {height}\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/w14_figs.py -->\n{body}\n</svg>\n</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


# ═══════════ figure 1: LightGCN — what survives of GCN ═════════════════════
USERS = [(105, 100), (105, 170), (105, 240)]
ITEMS = [(285, 80), (285, 150), (285, 220), (285, 290)]
EDGES = [(0, 0), (0, 1), (1, 1), (1, 2), (2, 2), (2, 3)]  # u1 shares item i2 with u2, u2 shares i3 with u3
lg = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'LightGCN: strip GCN to the part that matters on an interaction graph</text>']
for u, i in EDGES:
    (x1, y1), (x2, y2) = USERS[u], ITEMS[i]
    hot = (u, i) in ((0, 1), (1, 1), (1, 2), (2, 2))
    lg.append(f'  <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{ACC if hot else MUTED}" '
              f'stroke-width="{2.5 if hot else 1.6}" opacity="{0.9 if hot else 0.45}"/>')
for k, (x, y) in enumerate(USERS):
    lg.append(f'  <circle cx="{x}" cy="{y}" r="15" fill="{TEAL}"/>')
    lg.append(f'  <text x="{x}" y="{y + 4}" text-anchor="middle" font-family="{MONO}" font-size="12" font-weight="700" fill="{BG}">u{k + 1}</text>')
for k, (x, y) in enumerate(ITEMS):
    lg.append(f'  <rect x="{x - 13}" y="{y - 13}" width="26" height="26" rx="5" fill="{GOLD}"/>')
    lg.append(f'  <text x="{x}" y="{y + 4}" text-anchor="middle" font-family="{MONO}" font-size="12" font-weight="700" fill="{BG}">i{k + 1}</text>')
lg.append(f'  <text x="105" y="285" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="{TEAL}" font-weight="700">users</text>')
lg.append(f'  <text x="285" y="325" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="{GOLD}" font-weight="700">items</text>')
lg.append(f'  <text x="195" y="345" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{ACC}">highlighted: u1&#x2019;s 2-hop signal — the users who share its items</text>')
# right: the three equations, in a quiet panel
lg.append(f'  <rect x="400" y="52" width="330" height="230" rx="10" fill="{MUTED}" opacity="0.08"/>')
eqs = [
    ("propagate (that&#x2019;s all):", None),
    ("e&#x1D64;&#x207D;&#x1D4F;&#x207A;&#xB9;&#x207E; = &#x3A3;&#x1D62;&#x2208;N(u)  e&#x1D62;&#x207D;&#x1D4F;&#x207E; / &#x221A;(d&#x1D64;d&#x1D62;)", MONO),
    ("(and symmetrically for items)", None),
    ("read out: mean of ALL layers", None),
    ("e = (e&#x207D;&#x2070;&#x207E; + e&#x207D;&#xB9;&#x207E; + &#x2026; + e&#x207D;&#x1D37;&#x207E;) / (K+1)", MONO),
    ("score(u, i) = e&#x1D64; &#xB7; e&#x1D62;", MONO),
]
yy = 84
for txt, fam in eqs:
    is_eq = fam is not None
    lg.append(f'  <text x="565" y="{yy}" text-anchor="middle" font-family="{fam or SANS}" '
              f'font-size="{13 if is_eq else 12.5}" font-weight="{700 if is_eq else 400}" '
              f'fill="{TEXT if is_eq else MUTED}">{txt}</text>')
    yy += 40 if is_eq else 34
lg.append(f'''  <g font-family="{SANS}">
    <rect x="70" y="366" width="620" height="30" rx="15" fill="{ACC}"/>
    <text x="380" y="386" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">no weight matrix, no ReLU, no self-loop — when features are IDs, averaging IS the model</text>
  </g>''')
write("fig-w14-lightgcn", "\n".join(lg),
      "A small bipartite user-item graph next to LightGCN's three equations: embeddings propagate by degree-normalized neighborhood averaging with no weight matrices or nonlinearities, the final embedding is the mean over all layers, and scores are dot products; the highlighted path shows a user's two-hop signal reaching users who share its items",
      height=406)

# ═══════════ figure 2: the protocol table — one model, three numbers ═══════
PROTO = [("random 80/10/10", K3_RAND, "future leaks into train", PURPLE),
         ("leave-last-out", K3_LLO, "each user&#x2019;s last item held out", GOLD),
         ("global temporal", K3_T, "hard time wall at the 80% mark", TEAL)]
sp = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'the SAME LightGCN (K=3, d=64), the SAME data, test Recall@20 — only the split changes</text>']
BARW = 130
for k, (name, val, note, col) in enumerate(PROTO):
    cx = 155 + k * 225
    h = round(val * 570)
    sp.append(f'  <rect x="{cx - BARW // 2}" y="{268 - h}" width="{BARW}" height="{h}" rx="8" fill="{col}" opacity="0.85"/>')
    sp.append(f'  <text x="{cx}" y="{252 - h}" text-anchor="middle" font-family="{MONO}" font-size="15" font-weight="700" fill="{TEXT}">{val:.3f}</text>')
    sp.append(f'  <text x="{cx}" y="{292}" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="{col}">{name}</text>')
    sp.append(f'  <text x="{cx}" y="{312}" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{MUTED}">{note}</text>')
# inflation bracket: step-down from the random bar's height to the temporal bar's top
y_rand_top = 268 - round(K3_RAND * 570)
y_temp_top = 268 - round(K3_T * 570)
sp.append(f'  <path d="M 225 {y_rand_top} L 650 {y_rand_top} L 650 {y_temp_top - 7}" '
          f'stroke="{ACC}" stroke-width="2" fill="none" stroke-dasharray="6 4" marker-end="url(#w14sp-arr)"/>')
sp.append(f'  <defs><marker id="w14sp-arr" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
          f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{ACC}"/></marker></defs>')
# label sits just BELOW the bracket line: clear of the header and the 0.346
# value label (audit: top zone was crowded), still visually attached to it
sp.append(f'  <text x="435" y="{y_rand_top + 17}" text-anchor="middle" font-family="{SANS}" font-size="14" font-weight="700" fill="{ACC}">&#xD7;1.77 — the random split nearly doubles the score</text>')
sp.append(f'''  <g font-family="{SANS}">
    <rect x="70" y="330" width="620" height="30" rx="15" fill="{ACC}"/>
    <text x="380" y="350" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">Recall@20 is not a property of the model — it is a property of the model AND the protocol</text>
  </g>''')
write("fig-w14-splits", "\n".join(sp),
      "Three bars showing the same LightGCN model's test Recall at 20 on MovieLens-100k under three evaluation protocols: 0.346 under a random split where future interactions leak into training, 0.210 under leave-last-out, and 0.195 under a hard global temporal split — the random split inflates the score by a factor of 1.77",
      height=370)

# ═══════════ figure 3: the layer ladder on the honest split ════════════════
ld = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'global-temporal split, test Recall@20 — propagation depth K is the only thing changing</text>']
BARS = [(0, K0), (1, K1), (2, K2), (3, K3_T)]
for k, val in BARS:
    cx = 190 + k * 150
    h = round(val * 1100)
    col = TEAL if k else PURPLE
    # K=0's value label gets extra clearance from the popularity dashed line
    # (audit: 0.1562 sat too close to it)
    vy = 264 - h if k == 0 else 272 - h
    ld.append(f'  <rect x="{cx - 55}" y="{288 - h}" width="110" height="{h}" rx="8" fill="{col}" opacity="0.85"/>')
    ld.append(f'  <text x="{cx}" y="{vy}" text-anchor="middle" font-family="{MONO}" font-size="14" font-weight="700" fill="{TEXT}">{val:.4f}</text>')
    ld.append(f'  <text x="{cx}" y="{312}" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="{col}">K = {k}{" (= BPR-MF)" if k == 0 else ""}</text>')
    ld.append(f'  <text x="{cx}" y="{331}" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{MUTED}">{SECS[k]} s</text>')
ypop = 288 - round(POP_T * 1100)
ld.append(f'  <line x1="132" y1="{ypop}" x2="700" y2="{ypop}" stroke="{ACC}" stroke-width="2" stroke-dasharray="7 5"/>')
# stacked label sits clear of the edge with a solid leader tying it to the
# dashed line's start (audit: was cramped / read like an axis tick)
ld.append(f'  <line x1="121" y1="{ypop}" x2="130" y2="{ypop}" stroke="{ACC}" stroke-width="2"/>')
ld.append(f'  <text x="118" y="{ypop - 3}" text-anchor="end" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{ACC}">popularity</text>')
ld.append(f'  <text x="118" y="{ypop + 15}" text-anchor="end" font-family="{MONO}" font-size="12.5" font-weight="700" fill="{ACC}">{POP_T:.4f}</text>')
ld.append(f'''  <g font-family="{SANS}">
    <rect x="70" y="346" width="620" height="30" rx="15" fill="{ACC}"/>
    <text x="380" y="366" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">the co-consumption signal lives in the graph: K=0 loses to POPULARITY; each layer climbs past it</text>
  </g>''')
write("fig-w14-ladder", "\n".join(ld),
      "Four bars showing LightGCN test Recall at 20 on the honest global-temporal MovieLens split as propagation depth grows: 0.156 at K equals 0 which is plain BPR matrix factorization, then 0.175, 0.185, and 0.195 at K equals 3, with a dashed popularity-baseline line at 0.166 that the K equals 0 model falls below and every propagating model clears",
      height=386)

# ═══════════ figure 4: TGN in one loop (schematic) ═════════════════════════
tg = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="{MUTED}">'
      f'temporal graph networks, one loop (schematic) — a memory that events keep writing to</text>']
BOXES = [(95, "event", "(u, i, t, features)", TEAL),
         (270, "message", "m = msg(s&#x1D64;,s&#x1D62;,&#x394;t,x)", GOLD),
         (455, "memory", "s &#x2190; GRU(s, m)", ACC),
         (640, "embed + predict", "h(t) from s + graph", GREEN)]
for cx, title, sub, col in BOXES:
    tg.append(f'  <rect x="{cx - 78}" y="70" width="156" height="64" rx="10" fill="{col}" opacity="0.14"/>')
    tg.append(f'  <rect x="{cx - 78}" y="70" width="156" height="64" rx="10" fill="none" stroke="{col}" stroke-width="2"/>')
    tg.append(f'  <text x="{cx}" y="{95}" text-anchor="middle" font-family="{SANS}" font-size="13.5" font-weight="700" fill="{col}">{title}</text>')
    tg.append(f'  <text x="{cx}" y="{117}" text-anchor="middle" font-family="{MONO}" font-size="12" fill="{TEXT}">{sub}</text>')
for x1, x2 in [(173, 192), (348, 377), (533, 562)]:
    tg.append(f'  <line x1="{x1}" y1="102" x2="{x2}" y2="102" stroke="{MUTED}" stroke-width="2" marker-end="url(#w14tg-arr)"/>')
tg.append(f'  <defs><marker id="w14tg-arr" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
          f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{MUTED}"/></marker></defs>')
# the loop back: prediction time -> next event updates memory
tg.append(f'  <path d="M 640 138 C 640 190, 95 190, 95 142" stroke="{ACC}" stroke-width="2" fill="none" stroke-dasharray="6 4" marker-end="url(#w14tg-arr2)"/>')
tg.append(f'  <defs><marker id="w14tg-arr2" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
          f'<path d="M 0 0 L 10 5 L 0 10 z" fill="{ACC}"/></marker></defs>')
tg.append(f'  <text x="368" y="204" text-anchor="middle" font-family="{SANS}" font-size="12.5" font-weight="600" fill="{ACC}">the next event finds the memory already changed — order matters, so training must respect time</text>')
# time axis with events
tg.append(f'  <line x1="95" y1="232" x2="665" y2="232" stroke="{MUTED}" stroke-width="1.5" marker-end="url(#w14tg-arr)"/>')
for k, xx in enumerate((140, 205, 300, 340, 470, 555)):
    tg.append(f'  <circle cx="{xx}" cy="232" r="5" fill="{TEAL}"/>')
tg.append(f'  <text x="680" y="237" font-family="{SANS}" font-size="12.5" fill="{MUTED}">time</text>')
tg.append(f'  <text x="380" y="262" text-anchor="middle" font-family="{SANS}" font-size="12" fill="{MUTED}">events arrive irregularly — snapshots would blur them; TGN consumes the stream as it is</text>')
tg.append(f'''  <g font-family="{SANS}">
    <rect x="70" y="280" width="620" height="30" rx="15" fill="{ACC}"/>
    <text x="380" y="300" text-anchor="middle" font-size="13" font-weight="700" fill="{BG}">the memory carries the past — Week 3&#x2019;s lookup table, taught to tell time</text>
  </g>''')
write("fig-w14-tgn", "\n".join(tg),
      "Schematic of a temporal graph network as a loop: an event with two endpoints and a timestamp produces a message, the message updates each endpoint's GRU memory, time-aware embeddings are computed from memory plus the graph for prediction, and the next event finds the memory already changed, over an irregular event timeline",
      height=316)

print("all four Week 14 figures generated")
