#!/usr/bin/env python
"""Generate assets/figures/fig-w1-degrees.html — the karate club's degree
distribution with the friendship paradox annotated: the mean degree (~4.6)
versus the mean degree of a random friendship's endpoint (~7.8).

Protocol F1: data-derived figure -> generated from the real 78-edge dataset.
Run: python scripts/figgen/w1_figs.py
"""
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from karate_common import EDGES, N  # noqa: E402  (real Zachary 1977 data)

OUT = Path(__file__).resolve().parents[2] / "assets" / "figures" / "fig-w1-degrees.html"

C_HI, C_OFF = "#d9a62e", "#0f8377"          # faction colors, matching fig-w1-hero

deg = [0] * N
for a, b in EDGES:
    deg[a] += 1
    deg[b] += 1
hist = Counter(deg)
d_mean = sum(deg) / N                        # 156/34 ≈ 4.59
d_friend = sum(d * d for d in deg) / sum(deg)  # ≈ 7.77 — edge-endpoint mean
assert abs(d_mean - 4.59) < 0.01 and abs(d_friend - 7.77) < 0.01, "lecture numbers drifted"

DMAX = max(deg)                              # 17 (the Officer); Mr. Hi has 16
CMAX = max(hist.values())                    # 11 members of degree 2

# ── geometry ────────────────────────────────────────────────────────────────
X0, BINW, BARW = 70, 39, 26                 # bin origin / pitch / bar width
BASE, TOP = 244, 64                          # baseline and max-bar top
PXC = (BASE - TOP) / CMAX


def xc(d):                                   # continuous x for degree value d
    return X0 + (d - 1) * BINW + BINW / 2


bars, counts = [], []
for d in range(1, DMAX + 1):
    c = hist.get(d, 0)
    if c == 0:
        continue
    h = c * PXC
    if d == 16:
        fill, op = C_HI, "1"
    elif d == 17:
        fill, op = C_OFF, "1"
    else:
        fill, op = "var(--dkr-muted, #8e8e9a)", "0.5"
    bars.append(f'<rect x="{xc(d)-BARW/2:.1f}" y="{BASE-h:.1f}" width="{BARW}" '
                f'height="{h:.1f}" rx="3" fill="{fill}" opacity="{op}"/>')
    counts.append(f'<text x="{xc(d):.1f}" y="{BASE-h-6:.1f}" text-anchor="middle">{c}</text>')
bars = "\n    ".join(bars)
counts = "\n    ".join(counts)
ticks = "\n    ".join(
    f'<text x="{xc(d):.1f}" y="{BASE+18}" text-anchor="middle">{d}</text>'
    for d in range(1, DMAX + 1))

x_mean, x_friend = xc(d_mean), xc(d_friend)
hub_top16 = BASE - hist[16] * PXC
hub_top17 = BASE - hist[17] * PXC

svg = f"""```{{=html}}
<figure class="dkr-fig">
<svg viewBox="0 0 760 330" role="img" aria-label="Degree distribution of the karate club: most members have two to four friends, two hub leaders have sixteen and seventeen; the mean degree 4.6 sits far left of the mean degree 7.8 of a random friendship's endpoint — the friendship paradox">
  <!-- generated by scripts/figgen/w1_figs.py from the real 78-edge dataset -->
  <g>
    {bars}
  </g>
  <g font-family="'Source Sans 3', sans-serif" font-size="12" fill="var(--dkr-muted, #6e6e7a)">
    {counts}
  </g>
  <line x1="{X0-10}" y1="{BASE}" x2="{xc(DMAX)+BARW/2+10:.1f}" y2="{BASE}" stroke="var(--dkr-border, #d5d4cf)" stroke-width="1.5"/>
  <g font-family="'Source Sans 3', sans-serif" font-size="12" fill="var(--dkr-muted, #6e6e7a)">
    {ticks}
    <text x="{(X0 + xc(DMAX))/2:.0f}" y="{BASE+38}" text-anchor="middle">degree (number of friendships)</text>
    <text x="{X0-10}" y="32" text-anchor="start">members with that degree</text>
  </g>

  <!-- the two means: the friendship paradox in one gap -->
  <line x1="{x_mean:.1f}" y1="66" x2="{x_mean:.1f}" y2="{BASE}" stroke="var(--dkr-text, #1c1c21)" stroke-width="1.6" stroke-dasharray="5,4" opacity="0.8"/>
  <line x1="{x_friend:.1f}" y1="92" x2="{x_friend:.1f}" y2="{BASE}" stroke="var(--dkr-accent, #d9603b)" stroke-width="1.8" stroke-dasharray="5,4"/>
  <g font-family="'Source Sans 3', sans-serif" font-size="12.5" font-weight="600">
    <text x="{x_mean+8:.1f}" y="72" text-anchor="start" fill="var(--dkr-text, #1c1c21)">average member: d&#772; &#8776; 4.6</text>
    <text x="{x_friend+8:.1f}" y="98" text-anchor="start" fill="var(--dkr-accent, #b84a2b)">average friend-of-a-member: &#8776; 7.8</text>
  </g>

  <!-- the hubs -->
  <g font-family="'Source Sans 3', sans-serif" font-size="12.5" font-weight="600">
    <text x="{xc(16):.1f}" y="{hub_top16-40:.1f}" text-anchor="end" fill="#b98a1e">Mr. Hi (d = 16)</text>
    <text x="{xc(17)+6:.1f}" y="{hub_top17-64:.1f}" text-anchor="end" fill="var(--dkr-blue-dark, #0a5f56)">the Officer (d = 17)</text>
  </g>
  <g stroke-width="1.2" stroke-dasharray="2,3" opacity="0.9" fill="none">
    <line x1="{xc(16):.1f}" y1="{hub_top16-34:.1f}" x2="{xc(16):.1f}" y2="{hub_top16-4:.1f}" stroke="#b98a1e"/>
    <line x1="{xc(17):.1f}" y1="{hub_top17-58:.1f}" x2="{xc(17):.1f}" y2="{hub_top17-4:.1f}" stroke="var(--dkr-blue-dark, #0a5f56)"/>
  </g>

  <g font-family="'Source Sans 3', sans-serif">
    <rect x="80" y="292" width="600" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="312" text-anchor="middle" font-size="14" font-weight="700" fill="var(--dkr-bg, #fff)">a random member has &#8776; 4.6 friends, a random friend &#8776; 7.8 — the heavy tail at work</text>
  </g>
</svg>
</figure>
```
"""
OUT.write_text(svg, encoding="utf-8")
print("wrote", OUT)
