#!/usr/bin/env python
"""Generate assets/figures/fig-w2-cast.html — the cast graph as a compact reference
strip: the drawing with identity colours and degrees, its edge list, and its adjacency
matrix, so a reader doing a hand calculation has every number in view. Reprinted
beside each worked example of Lecture 2 that computes on this graph.

Everything drawn is derived from the edge list here (degrees, matrix cells).
Run: python scripts/figgen/w2_cast.py
"""
from pathlib import Path

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"

NAMES = "ABCDEF"
EDGES = [("A", "B"), ("A", "C"), ("A", "D"), ("B", "C"), ("C", "E"), ("C", "F"), ("E", "F")]
COLOR = {"A": "#d9a62e", "B": "#cf4a30", "C": "#199473", "D": "#7c5cd6", "E": "#d1567e", "F": "#0f8377"}
POS = {"A": (112, 84), "B": (226, 44), "C": (220, 128), "D": (60, 146), "E": (116, 190), "F": (234, 200)}

deg = {u: 0 for u in NAMES}
for a, b in EDGES:
    deg[a] += 1
    deg[b] += 1
adj = {(a, b) for a, b in EDGES} | {(b, a) for a, b in EDGES}

# degree labels sit on the side of each node that faces away from the graph's centre
cx = sum(p[0] for p in POS.values()) / 6
cy = sum(p[1] for p in POS.values()) / 6
parts = []
parts.append(f'  <text x="20" y="22" font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #8e8e9a)">the cast graph · n = 6, m = {len(EDGES)}</text>')
parts.append('  <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="2" opacity="0.6">')
for a, b in EDGES:
    (x1, y1), (x2, y2) = POS[a], POS[b]
    parts.append(f'    <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}"/>')
parts.append("  </g>")
for u in NAMES:
    x, y = POS[u]
    dx, dy = x - cx, y - cy
    L = (dx * dx + dy * dy) ** 0.5 or 1
    lx, ly = x + dx / L * 30, y + dy / L * 30
    parts.append(f'  <circle cx="{x}" cy="{y}" r="15" fill="{COLOR[u]}"/>')
    parts.append(f'  <text x="{x}" y="{y + 5}" text-anchor="middle" font-family="{SANS}" font-size="14" font-weight="700" fill="#fff">{u}</text>')
    parts.append(f'  <text x="{lx:.0f}" y="{ly + 4:.0f}" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="var(--dkr-muted, #8e8e9a)">d={deg[u]}</text>')
edge_list = " · ".join(a + b for a, b in EDGES)
parts.append(f'  <text x="180" y="246" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="var(--dkr-text, #1c1c21)">edges: {edge_list}</text>')
parts.append(f'  <text x="180" y="266" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="var(--dkr-muted, #8e8e9a)">d = ({", ".join(str(deg[u]) for u in NAMES)}), Σd = {sum(deg.values())} = 2m</text>')

# adjacency matrix
mx, my, cell = 452, 62, 27
parts.append(f'  <text x="{mx + 3 * cell + 14}" y="{my - 30}" text-anchor="middle" font-family="{SANS}" font-size="13.5" font-weight="700" fill="var(--dkr-text, #1c1c21)">adjacency matrix A</text>')
for j, v in enumerate(NAMES):
    parts.append(f'  <text x="{mx + 28 + j * cell + cell / 2:.0f}" y="{my - 8}" text-anchor="middle" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{COLOR[v]}">{v}</text>')
    parts.append(f'  <text x="{mx + 16}" y="{my + j * cell + cell / 2 + 4.5:.0f}" text-anchor="middle" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{COLOR[v]}">{v}</text>')
for i, u in enumerate(NAMES):
    for j, v in enumerate(NAMES):
        on = (u, v) in adj
        x, y = mx + 28 + j * cell, my + i * cell
        parts.append(f'  <rect x="{x}" y="{y}" width="{cell}" height="{cell}" fill="{"var(--dkr-blue, #0f8377)" if on else "none"}" fill-opacity="{0.85 if on else 0}" stroke="var(--dkr-border, #e8e7e3)" stroke-width="1"/>')
        parts.append(f'  <text x="{x + cell / 2:.0f}" y="{y + cell / 2 + 4.5:.0f}" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="{"#fff" if on else "var(--dkr-muted, #8e8e9a)"}">{1 if on else 0}</text>')
parts.append(f'  <text x="{mx + 28 + 3 * cell:.0f}" y="{my + 6 * cell + 20}" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #8e8e9a)">row u = who u is joined to · each row sums to d_u</text>')

aria = ("The cast graph used in every hand calculation: six nodes A to F joined by the edges AB, AC, AD, BC, CE, CF and EF, "
        "with degrees 3, 2, 4, 1, 2, 2, drawn beside its six-by-six adjacency matrix with the ones filled in.")
svg = ("```{=html}\n<figure class=\"dkr-fig\">\n"
       f"<svg viewBox=\"0 0 760 280\" role=\"img\" aria-label=\"{aria}\">\n"
       "  <!-- generated by scripts/figgen/w2_cast.py -->\n" + "\n".join(parts) + "\n</svg>\n</figure>\n```\n")
(FIGDIR / "fig-w2-cast.html").write_text(svg, encoding="utf-8")
print("wrote fig-w2-cast · degrees", deg)
