#!/usr/bin/env python
"""Generate the four data-derived Week 2 figures:
  fig-w2-hero            — PageRank on a toy web (computed), the quality-over-quantity story
  fig-w2-centralities    — Krackhardt kite with each centrality's champion (all computed)
  fig-w2-wl              — two rounds of real WL color refinement on the cast graph
  fig-w2-fiedler         — karate club split by the computed Fiedler vector vs reality
Run: python scripts/figgen/w2_figs.py
"""
import math
from collections import deque
from pathlib import Path

from karate_common import EDGES as K_EDGES, N as K_N, MR_HI, C_HI, C_OFF, layout, make_label_placer, fiedler_vector

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"


def write(name, body, aria):
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 400\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/w2_figs.py -->\n{body}\n</svg>\n</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


# ════════════════════════════════ PageRank hero ════════════════════════════
# A toy web where page Q has ONE inlink (from the giant hub) and page V has FOUR
# inlinks from leaf pages — and PageRank ranks Q above V. Quality beats quantity.
WEB = {  # node -> outlinks
    "Hub": ["Q", "N1", "N2"],
    "N1": ["Hub"], "N2": ["Hub"], "N3": ["Hub"], "N4": ["Hub", "V"],
    "L1": ["V"], "L2": ["V"], "L3": ["V"],
    "Q": ["Hub"],
    "V": ["N3"],
}
NODES = list(WEB)


def pagerank(web, beta=0.85, iters=200):
    nodes = list(web)
    n = len(nodes)
    pr = {u: 1 / n for u in nodes}
    for _ in range(iters):
        nxt = {u: (1 - beta) / n for u in nodes}
        for u, outs in web.items():
            share = beta * pr[u] / len(outs)
            for v in outs:
                nxt[v] += share
        pr = nxt
    return pr


PR = pagerank(WEB)
assert PR["Q"] > PR["V"], "the story requires PR(Q) > PR(V); adjust the toy web"

WPOS = {"Hub": (200, 180), "N1": (90, 90), "N2": (90, 270), "N3": (330, 90), "N4": (330, 270),
        "Q": (480, 175), "V": (560, 300), "L1": (460, 345), "L2": (525, 352), "L3": (660, 345)}

body = ['  <defs><marker id="w2hArrow" markerWidth="8" markerHeight="8" refX="22" refY="3" orient="auto">'
        '<path d="M0,0 L7,3 L0,6 Z" fill="var(--dkr-muted, #8e8e9a)"/></marker></defs>']
body.append('  <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1.4" opacity="0.65" fill="none">')
for u, outs in WEB.items():
    for v in outs:
        (x1, y1), (x2, y2) = WPOS[u], WPOS[v]
        body.append(f'    <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" marker-end="url(#w2hArrow)"/>')
body.append("  </g>")
body.append(f'  <g font-family="{SANS}" text-anchor="middle">')
for u in NODES:
    x, y = WPOS[u]
    r = 10 + 90 * PR[u]
    hot = u in ("Q", "V")
    fill = "var(--dkr-accent, #d9603b)" if u == "Q" else ("#7c5cd6" if u == "V" else "var(--dkr-blue, #0f8377)")
    opacity = 0.95 if hot else (0.8 if u == "Hub" else 0.55)
    label = {"Q": "Q", "V": "V", "Hub": "hub"}.get(u, "")
    body.append(f'    <circle cx="{x}" cy="{y}" r="{r:.0f}" fill="{fill}" opacity="{opacity}"/>')
    body.append(f'    <text x="{x}" y="{y + 4}" font-size="12" font-weight="700" fill="#fff">{label}</text>')
    body.append(f'    <text x="{x}" y="{y - r - 6:.0f}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">{PR[u]:.3f}</text>')
body.append("  </g>")
body.append(f'''  <g font-family="{SANS}" font-size="13" font-weight="600">
    <text x="470" y="120" text-anchor="middle" fill="var(--dkr-accent, #b84a2b)">Q: ONE inlink — from the hub</text>
    <text x="600" y="255" text-anchor="middle" fill="#7c5cd6">V: FOUR inlinks — from nobodies</text>
  </g>
  <g font-family="{SANS}">
    <rect x="150" y="368" width="460" height="28" rx="14" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="387" text-anchor="middle" font-size="13.5" font-weight="700" fill="var(--dkr-bg, #fff)">PageRank(Q) = {PR['Q']:.3f}  &gt;  PageRank(V) = {PR['V']:.3f} — quality beats quantity</text>
  </g>
  <text x="380" y="26" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">a toy web · arrows = links · node size and number = converged PageRank (β = 0.85)</text>''')
write("fig-w2-hero", "\n".join(body),
      "A toy web of ten pages sized by converged PageRank: a page with one inlink from the hub outranks a page with four inlinks from unimportant pages")


# ═══════════════════════════ Krackhardt kite centralities ═══════════════════
KITE = [(0,1),(0,2),(0,3),(0,5),(1,3),(1,4),(1,6),(2,3),(2,5),(3,4),(3,5),(3,6),(4,6),(5,6),(5,7),(6,7),(7,8),(8,9)]
KN = 10
KNAMES = ["Andre", "Beverly", "Carol", "Diane", "Ed", "Fernando", "Garth", "Heather", "Ike", "Jane"]
KPOS = [(120, 120), (300, 100), (95, 235), (208, 180), (322, 235), (140, 320), (280, 330), (210, 415 - 15), (210, 415 + 45 - 15), (210, 505 - 15)]
KPOS = [(x + 30, int(y * 0.72) + 10) for x, y in KPOS]

adjK = {i: set() for i in range(KN)}
for a, b in KITE:
    adjK[a].add(b); adjK[b].add(a)

deg = [len(adjK[i]) for i in range(KN)]

def bfs_dist(s):
    dist = {s: 0}
    q = deque([s])
    while q:
        u = q.popleft()
        for v in adjK[u]:
            if v not in dist:
                dist[v] = dist[u] + 1
                q.append(v)
    return dist

clo = [ (KN - 1) / sum(bfs_dist(s).values()) for s in range(KN)]

# betweenness by path enumeration (BFS DAG counting)
btw = [0.0] * KN
for s in range(KN):
    dist = bfs_dist(s)
    sigma = {v: 0 for v in range(KN)}; sigma[s] = 1
    order = sorted(dist, key=dist.get)
    for u in order:
        for v in adjK[u]:
            if dist[v] == dist[u] + 1:
                sigma[v] += sigma[u]
    delta = {v: 0.0 for v in range(KN)}
    for u in reversed(order):
        for v in adjK[u]:
            if dist[v] == dist[u] + 1:
                delta[u] += sigma[u] / sigma[v] * (1 + delta[v])
        if u != s:
            btw[u] += delta[u]
btw = [b / 2 for b in btw]

eig = [1.0] * KN
for _ in range(300):
    nxt = [sum(eig[j] for j in adjK[i]) for i in range(KN)]
    nrm = math.sqrt(sum(x * x for x in nxt))
    eig = [x / nrm for x in nxt]

def argmaxes(vals):
    m = max(vals)
    return [i for i in range(KN) if vals[i] >= m - 1e-9]

CHAMPS = [
    ("degree", argmaxes(deg), "var(--dkr-accent, #d9603b)", ["most connections"]),
    ("closeness", argmaxes(clo), "var(--dkr-green, #199473)", ["shortest average distance", "to everyone"]),
    ("betweenness", argmaxes(btw), "#7c5cd6", ["sits on the most", "shortest paths"]),
    ("eigenvector", argmaxes(eig), "#d9a62e", ["connected to the", "well-connected —", "agrees with degree here"]),
]
# the kite's teaching point: three measures disagree, eigenvector sides with degree
assert CHAMPS[0][1] == [3] and CHAMPS[1][1] == [5, 6] and CHAMPS[2][1] == [7], \
    f"kite champions changed: {[(c[0], c[1]) for c in CHAMPS]}"
assert CHAMPS[3][1] == CHAMPS[0][1], "caption claims eigenvector agrees with degree"

panels = []
for pi, (cname, champs, color, desc) in enumerate(CHAMPS):
    ox = 20 + (pi % 2) * 375
    oy = 8 + (pi // 2) * 196
    g = [f'  <g transform="translate({ox},{oy}) scale(0.44)">']
    g.append('    <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="2.6" opacity="0.6">')
    for a, b in KITE:
        g.append(f'      <line x1="{KPOS[a][0]}" y1="{KPOS[a][1]}" x2="{KPOS[b][0]}" y2="{KPOS[b][1]}"/>')
    g.append("    </g>")
    for i in range(KN):
        x, y = KPOS[i]
        is_c = i in champs
        rr = (26 if len(champs) == 1 else 23) if is_c else 15
        g.append(f'      <circle cx="{x}" cy="{y}" r="{rr}" fill="{color if is_c else "var(--dkr-muted, #8e8e9a)"}" opacity="{1 if is_c else 0.45}"/>')
    for c in champs:
        cx, cy = KPOS[c]
        fs = 26 if len(champs) == 1 else 22
        g.append(f'      <text x="{cx}" y="{cy + fs // 3}" text-anchor="middle" font-family="{SANS}" font-size="{fs}" font-weight="700" fill="#fff">{KNAMES[c][0]}</text>')
    g.append("  </g>")
    if len(champs) == 1:
        champ_lines = [f"champion: {KNAMES[champs[0]]}"]
    else:
        champ_lines = ["champions (tied):", " &amp; ".join(KNAMES[c] for c in champs)]
    lines = "\n".join(
        f'    <text x="0" y="{20 + 18 * li}" font-size="12.5" fill="var(--dkr-text, #1c1c21)">{line}</text>'
        for li, line in enumerate(champ_lines)) + "\n" + "\n".join(
        f'    <text x="0" y="{20 + 18 * len(champ_lines) + 17 * li}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">{line}</text>'
        for li, line in enumerate(desc))
    g.append(f'''  <g font-family="{SANS}" transform="translate({ox + 190},{oy + 30})">
    <text x="0" y="0" font-size="14.5" font-weight="700" fill="{color}">{cname}</text>
{lines}
  </g>''')
    panels.append("\n".join(g))
panels.append(f'  <text x="380" y="396" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">Krackhardt\'s kite: three measures, three different champions — and eigenvector sides with degree</text>')
write("fig-w2-centralities", "\n".join(panels),
      "The Krackhardt kite network shown four times; degree crowns Diane, closeness crowns the tied Fernando and Garth, betweenness crowns Heather, and eigenvector agrees with degree — all computed from the graph")


# ═════════════════════════════ WL refinement on the cast ═════════════════════
CAST = [(0, 1), (0, 2), (0, 3), (1, 2), (2, 4), (2, 5), (4, 5)]
CN = 6
CNAMES = "ABCDEF"
CPOS = [(120, 105), (215, 48), (280, 118), (68, 172), (224, 185), (368, 172)]
adjC = {i: sorted({b for a, b in CAST if a == i} | {a for a, b in CAST if b == i}) for i in range(CN)}

# one visual color per WL color id, no wraparound: round 0 uses id 0, round 1 ids
# 1-4, round 2 ids 5-9 — a color id must keep one visual color across the figure
WLPAL = ["#8e8e9a", "#d9603b", "#0f8377", "#7c5cd6", "#d9a62e",
         "#d1567e", "#199473", "#8a5a33", "#cf4a30", "#5f7a1e"]

colors = [0] * CN
rounds = [list(colors)]
tables = []
for r in range(2):
    sigs = [(colors[i], tuple(sorted(colors[j] for j in adjC[i]))) for i in range(CN)]
    seen = {}
    newc = []
    for s in sigs:
        if s not in seen:
            seen[s] = len(seen) + max(colors) + 1
        newc.append(seen[s])
    tables.append(sorted(seen.items(), key=lambda kv: kv[1]))
    colors = newc
    rounds.append(list(colors))

parts = []
for ri, cols in enumerate(rounds):
    ox = 8 + ri * 240
    parts.append(f'  <g transform="translate({ox},30) scale(0.58)">')
    parts.append('    <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="2.4" opacity="0.65">')
    for a, b in CAST:
        parts.append(f'      <line x1="{CPOS[a][0]}" y1="{CPOS[a][1]}" x2="{CPOS[b][0]}" y2="{CPOS[b][1]}"/>')
    parts.append("    </g>")
    for i in range(CN):
        x, y = CPOS[i]
        parts.append(f'      <circle cx="{x}" cy="{y}" r="20" fill="{WLPAL[cols[i] % len(WLPAL)]}"/>')
        parts.append(f'      <text x="{x}" y="{y + 7}" text-anchor="middle" font-family="{SANS}" font-size="19" font-weight="700" fill="#fff">{CNAMES[i]}</text>')
    parts.append("  </g>")
    ncls = len(set(cols))
    parts.append(f'  <text x="{ox + 128}" y="22" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="var(--dkr-text, #1c1c21)">round {ri} · {ncls} color{"s" if ncls > 1 else ""}</text>')
    parts.append(f'  <text x="{ox + 128}" y="176" text-anchor="middle" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">{"everyone identical" if ri == 0 else ("split by degree" if ri == 1 else "stable — refinement done")}</text>')

# relabeling table for round 1→2
parts.append(f'  <g font-family="{SANS}" transform="translate(70,215)">')
parts.append('    <text x="0" y="0" font-size="13" font-weight="700" fill="var(--dkr-text, #1c1c21)">the relabeling rule, round 2:  new color = HASH( my color , multiset of neighbor colors )</text>')
for i, ((own, nbrs), new) in enumerate(tables[1]):
    x = (i % 3) * 210
    y = 30 + (i // 3) * 26
    nb = "{" + ",".join(str(c) for c in nbrs) + "}"
    parts.append(f'    <text x="{x}" y="{y}" font-size="12.5" font-family="\'JetBrains Mono\', monospace" fill="var(--dkr-text, #1c1c21)">({own}, {nb})</text>')
    parts.append(f'    <text x="{x + 122}" y="{y}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">→</text>')
    parts.append(f'    <circle cx="{x + 154}" cy="{y - 4}" r="9" fill="{WLPAL[new % len(WLPAL)]}"/>')
parts.append("  </g>")
hist = {}
for c in rounds[-1]:
    hist[c] = hist.get(c, 0) + 1
parts.append(f'''  <g font-family="{SANS}">
    <rect x="60" y="358" width="640" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="378" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">histogram {tuple(sorted(hist.values()))} is this graph's WL fingerprint — and, in Week 9, a GNN's ceiling</text>
  </g>''')
write("fig-w2-wl", "\n".join(parts),
      "Two rounds of Weisfeiler-Lehman color refinement on the cast graph: from one shared color, to degree classes, to a stable five-color partition, with the hash relabeling table")


# ═════════════════════════════ Karate Fiedler split ═════════════════════════
P = layout()
fv = fiedler_vector()
pred_hi = {i for i in range(K_N) if fv[i] * (1 if fv[0] > 0 else -1) > 0}
agree = sum(1 for i in range(K_N) if (i in pred_hi) == (i in MR_HI))
# align the eigenvector's arbitrary sign with whichever labeling agrees more
flip = (K_N - agree) > agree
agree = max(agree, K_N - agree)
wrong = [i for i in range(K_N) if ((i in pred_hi) != (i in MR_HI)) != flip]

parts = ['  <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1" opacity="0.4">']
for a, b in K_EDGES:
    parts.append(f'    <line x1="{P[a][0]}" y1="{P[a][1]}" x2="{P[b][0]}" y2="{P[b][1]}"/>')
parts.append("  </g>")
for i in range(K_N):
    x, y = P[i]
    fill = C_HI if ((i in pred_hi) != flip) else C_OFF
    ring = ' stroke="#cf4a30" stroke-width="3"' if i in wrong else ""
    parts.append(f'  <circle cx="{x}" cy="{y}" r="{12 if i in (0, 33) else 8}" fill="{fill}"{ring}/>')
parts.append(f'''  <g font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #8e8e9a)">
    <circle cx="80" cy="30" r="7" fill="{C_HI}"/><text x="93" y="34">Fiedler says: Mr. Hi's side</text>
    <circle cx="260" cy="30" r="7" fill="{C_OFF}"/><text x="273" y="34">Fiedler says: the Officer's</text>
    <text x="720" y="34" text-anchor="end">red ring = disagrees with the real 1977 split</text>
  </g>
  <g font-family="{SANS}">
    <rect x="120" y="358" width="520" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="378" text-anchor="middle" font-size="13.5" font-weight="700" fill="var(--dkr-bg, #fff)">one eigenvector of L, thresholded at zero: {agree} of 34 members placed correctly</text>
  </g>''')
write("fig-w2-fiedler", "\n".join(parts),
      f"The karate club colored by the sign of the Fiedler vector of its Laplacian; {agree} of 34 members match the real split, disagreements ringed in red")
print(f"fiedler agreement: {agree}/34, wrong = {wrong}")
