#!/usr/bin/env python
"""Generate the four data-derived Week 2 figures:
  fig-w2-hero            — PageRank on a toy web (computed), the quality-over-quantity story
  fig-w2-centralities    — Krackhardt kite with each centrality's champion (all computed)
  fig-w2-wl              — two rounds of real WL color refinement on the cast graph
  fig-w2-fiedler         — karate club split by the computed Fiedler vector vs reality
Run: python scripts/figgen/w2_figs.py
"""
import math
from collections import deque
from pathlib import Path

from karate_common import EDGES as K_EDGES, N as K_N, MR_HI, C_HI, C_OFF, layout, make_label_placer, fiedler_vector

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"


def write(name, body, aria, h=400, caption=None):
    cap = f"<figcaption class=\"fig-caption\">{caption}</figcaption>\n" if caption else ""
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 {h}\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/w2_figs.py -->\n{body}\n</svg>\n{cap}</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


# ════════════════════════════════ PageRank hero ════════════════════════════
# A toy web where page Q has ONE inlink (from the giant hub) and page V has FOUR
# inlinks from leaf pages — and PageRank ranks Q above V. Quality beats quantity.
# Every edge is drawn with a width proportional to the mass it carries per step,
# β·r_u / d_out(u), so the argument is visible before the numbers are read: one fat
# link into Q, four hairlines into V. A ledger underneath stacks those arrivals.
WEB = {  # node -> outlinks
    "Hub": ["Q", "N1", "N2"],
    "N1": ["Hub"], "N2": ["Hub"], "N3": ["Hub"], "N4": ["Hub", "V"],
    "L1": ["V"], "L2": ["V"], "L3": ["V"],
    "Q": ["Hub"],
    "V": ["N3"],
}
NODES = list(WEB)
BETA = 0.85


def pagerank(web, beta=BETA, iters=200):
    nodes = list(web)
    n = len(nodes)
    pr = {u: 1 / n for u in nodes}
    for _ in range(iters):
        nxt = {u: (1 - beta) / n for u in nodes}
        for u, outs in web.items():
            share = beta * pr[u] / len(outs)
            for v in outs:
                nxt[v] += share
        pr = nxt
    return pr


PR = pagerank(WEB)
assert PR["Q"] > PR["V"], "the story requires PR(Q) > PR(V); adjust the toy web"
NPAGES = len(NODES)
TELEPORT = (1 - BETA) / NPAGES
FLOW = {(u, v): BETA * PR[u] / len(outs) for u, outs in WEB.items() for v in outs}
IN_Q = [(u, FLOW[(u, "Q")]) for u in NODES if "Q" in WEB[u]]
IN_V = [(u, FLOW[(u, "V")]) for u in NODES if "V" in WEB[u]]
assert abs(sum(f for _, f in IN_Q) + TELEPORT - PR["Q"]) < 1e-9
assert abs(sum(f for _, f in IN_V) + TELEPORT - PR["V"]) < 1e-9

HX, HY = 175, 190
WPOS = {"Hub": (HX, HY), "N1": (70, 92), "N2": (70, 288), "N3": (300, 78), "N4": (300, 300),
        "Q": (470, 130), "V": (600, 250), "L1": (516, 330), "L2": (606, 346), "L3": (700, 326)}
MONO = "'JetBrains Mono', monospace"
ACC, PUR, TEAL, MUT = ("var(--dkr-accent, #d9603b)", "var(--dkr-purple, #7c5cd6)",
                       "var(--dkr-blue, #0f8377)", "var(--dkr-muted, #8e8e9a)")


def radius(u):
    return 8 + 40 * math.sqrt(PR[u])


BOW_SIDE = {("V", "N3"): -1}   # -1 bows to the right of travel; default is left


def edge_path(u, v):
    # Quadratic arc from u's rim to just short of v's rim, bowed to the left of travel
    # so a pair of opposite links separates into two distinct arcs.
    (x1, y1), (x2, y2) = WPOS[u], WPOS[v]
    dx, dy = x2 - x1, y2 - y1
    L = math.hypot(dx, dy)
    ux, uy = dx / L, dy / L
    px, py = -uy, ux                      # left-hand normal
    bow = 0.13 * L * BOW_SIDE.get((u, v), 1)
    cx, cy = (x1 + x2) / 2 + px * bow, (y1 + y2) / 2 + py * bow
    # trim both ends so the arrowhead lands on the rim of v, not under the disc
    r1, r2 = radius(u) + 2, radius(v) + head_len(u, v) + 1
    # direction at the ends of the quadratic
    d1x, d1y = cx - x1, cy - y1
    l1 = math.hypot(d1x, d1y); d1x, d1y = d1x / l1, d1y / l1
    d2x, d2y = x2 - cx, y2 - cy
    l2 = math.hypot(d2x, d2y); d2x, d2y = d2x / l2, d2y / l2
    sx, sy = x1 + d1x * r1, y1 + d1y * r1
    ex, ey = x2 - d2x * r2, y2 - d2y * r2
    return f"M {sx:.1f} {sy:.1f} Q {cx:.1f} {cy:.1f} {ex:.1f} {ey:.1f}"


def edge_width(u, v):
    return 1.5 + 20 * FLOW[(u, v)]


def head_len(u, v):
    return max(11.0, 4.4 * edge_width(u, v))  # long head: the tip is an acute point


def head_half(u, v):
    return max(2.6, 0.8 * edge_width(u, v))   # narrow head: about a 20-degree tip


def marker_id(u, v):
    return f"w2h_{u}_{v}"


# ── diagnostic: every arc must stay clear of the discs it is not connecting ──
def _arc_point(u, v, t):
    (x1, y1), (x2, y2) = WPOS[u], WPOS[v]
    dx, dy = x2 - x1, y2 - y1
    L = math.hypot(dx, dy)
    px, py = -dy / L, dx / L
    b = 0.13 * L * BOW_SIDE.get((u, v), 1)
    cx, cy = (x1 + x2) / 2 + px * b, (y1 + y2) / 2 + py * b
    return ((1 - t) ** 2 * x1 + 2 * (1 - t) * t * cx + t ** 2 * x2,
            (1 - t) ** 2 * y1 + 2 * (1 - t) * t * cy + t ** 2 * y2)
for u, outs in WEB.items():
    for v in outs:
        for w in NODES:
            if w in (u, v):
                continue
            gap = min(math.hypot(_arc_point(u, v, k / 40)[0] - WPOS[w][0], _arc_point(u, v, k / 40)[1] - WPOS[w][1]) for k in range(41)) - radius(w)
            if gap < 6:
                print(f"  hero arc {u}->{v} passes {gap:.1f}px from disc {w}")

body = ["  <defs>"]
for u, outs in WEB.items():
    for v in outs:
        col = ACC if v == "Q" else (PUR if v == "V" else MUT)
        h = head_len(u, v)
        w = head_half(u, v)
        body.append(f'    <marker id="{marker_id(u, v)}" markerWidth="{h + 1:.1f}" markerHeight="{2 * w + 1:.1f}" refX="{h:.1f}" refY="{w + 0.5:.1f}" orient="auto" markerUnits="userSpaceOnUse"><path d="M0,0.5 L{h:.1f},{w + 0.5:.1f} L0,{2 * w + 0.5:.1f} Z" fill="{col}" stroke="none"/></marker>')
body.append("  </defs>")
body.append(f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="{MUT}">a toy web of ten pages · arrow width = the mass a link carries each step · disc size and number = converged PageRank (β = 0.85)</text>')

# edges: muted first, then the two highlighted inflows on top
body.append('  <g fill="none" stroke-linecap="round">')
for u, outs in WEB.items():
    for v in outs:
        if v in ("Q", "V"):
            continue
        body.append(f'    <path d="{edge_path(u, v)}" stroke="{MUT}" stroke-width="{edge_width(u, v):.1f}" opacity="0.7" marker-end="url(#{marker_id(u, v)})"/>')
for u, outs in WEB.items():
    for v in outs:
        if v == "Q":
            body.append(f'    <path d="{edge_path(u, v)}" stroke="{ACC}" stroke-width="{edge_width(u, v):.1f}" opacity="0.95" marker-end="url(#{marker_id(u, v)})"/>')
        elif v == "V":
            body.append(f'    <path d="{edge_path(u, v)}" stroke="{PUR}" stroke-width="{edge_width(u, v):.1f}" opacity="0.9" marker-end="url(#{marker_id(u, v)})"/>')
body.append("  </g>")

# nodes
body.append(f'  <g font-family="{SANS}" text-anchor="middle">')
for u in NODES:
    x, y = WPOS[u]
    r = radius(u)
    if u == "Q":
        fill, op = ACC, 1.0
    elif u == "V":
        fill, op = PUR, 1.0
    elif u == "Hub":
        fill, op = TEAL, 0.92
    elif u.startswith("N"):
        fill, op = TEAL, 0.55
    else:
        fill, op = MUT, 0.5
    if u in ("Q", "V"):
        body.append(f'    <circle cx="{x}" cy="{y}" r="{r + 7:.1f}" fill="{fill}" opacity="0.16"/>')
    body.append(f'    <circle cx="{x}" cy="{y}" r="{r:.1f}" fill="{fill}" opacity="{op}"/>')
    inner = {"Q": "Q", "V": "V", "Hub": "hub"}.get(u, "")
    if inner:
        body.append(f'    <text x="{x}" y="{y + 5}" font-size="{14 if u != "Hub" else 15}" font-weight="700" fill="#fff">{inner}</text>')
    # PageRank readout, placed away from the arrows
    lx, ly, anchor = x, y + r + 16, "middle"
    if u in ("N1", "N2"):
        lx, ly, anchor = x, y + r + 16, "middle"
    if u == "N3":
        lx, ly, anchor = x + r + 6, y + 4, "start"
    if u == "Hub":
        lx, ly = x, y + r + 17
    if u == "Q":
        lx, ly, anchor = x + r + 10, y + 4, "start"
    if u == "V":
        lx, ly, anchor = x + r + 10, y + 4, "start"
    if u == "L1":
        lx, ly, anchor = x - r - 6, y + 4, "end"
    if u == "L2":
        lx, ly, anchor = x + r + 6, y + 4, "start"
    body.append(f'    <text x="{lx:.0f}" y="{ly:.0f}" text-anchor="{anchor}" font-family="{MONO}" font-size="12.5" fill="{MUT}">{PR[u]:.3f}</text>')
body.append("  </g>")

# callouts, sitting beside their subject rather than on a leader
body.append(f'''  <g font-family="{SANS}" font-size="13.5" font-weight="700">
    <text x="470" y="80" text-anchor="middle" fill="{ACC}">Q · one inlink, from the hub</text>
    <text x="662" y="222" text-anchor="middle" fill="{PUR}">V · four inlinks, from nobodies</text>
  </g>''')

# ledger: the arrivals at Q and at V, stacked to scale
LY = 398
SCALE = 300 / PR["Q"]
LX0 = 118
body.append(f'  <text x="{LX0}" y="{LY - 6}" font-family="{SANS}" font-size="12.5" fill="{MUT}">mass arriving each step, to scale — one thick slice against four thin ones, plus the grey teleport sliver</text>')
rows = [("Q", IN_Q, ACC, "Q ← 1 link"), ("V", IN_V, PUR, "V ← 4 links")]
for i, (node, arrivals, col, label) in enumerate(rows):
    y = LY + 6 + i * 26
    body.append(f'  <text x="{LX0 - 8}" y="{y + 13}" text-anchor="end" font-family="{SANS}" font-size="13" font-weight="700" fill="{col}">{label}</text>')
    x = LX0
    for j, (src, f) in enumerate(sorted(arrivals, key=lambda t: -t[1])):
        w = f * SCALE
        body.append(f'  <rect x="{x:.1f}" y="{y}" width="{max(w - 1.5, 1):.1f}" height="18" rx="2" fill="{col}" opacity="{0.95 - 0.12 * j}"/>')
        x += w
    body.append(f'  <rect x="{x:.1f}" y="{y}" width="{TELEPORT * SCALE - 1.5:.1f}" height="18" rx="2" fill="{MUT}" opacity="0.5"/>')
    x += TELEPORT * SCALE
    body.append(f'  <text x="{x + 8:.1f}" y="{y + 13}" font-family="{MONO}" font-size="12.5" font-weight="700" fill="var(--dkr-text, #1c1c21)">= {PR[node]:.3f}</text>')
hub_share = IN_Q[0][1]
body.append(f'  <text x="{LX0 + hub_share * SCALE / 2:.0f}" y="{LY + 6 + 13}" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="#fff">from the hub: {hub_share:.3f}</text>')

# verdict band
body.append(f'''  <g font-family="{SANS}">
    <rect x="130" y="458" width="500" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="478" text-anchor="middle" font-size="14" font-weight="700" fill="#fff">PageRank(Q) = {PR['Q']:.3f}  &gt;  PageRank(V) = {PR['V']:.3f} — quality beats quantity</text>
  </g>''')
write("fig-w2-hero", "\n".join(body),
      f"A toy web of ten pages drawn with arrow widths proportional to the PageRank mass each link carries. Page Q has one inlink, from the hub, and converges to {PR['Q']:.3f}; page V has four inlinks from unimportant pages and converges to {PR['V']:.3f}. A ledger underneath stacks the arrivals to scale: one thick slice into Q against four thin slices into V, so a single endorsement from an important page outweighs four from nobodies.",
      h=502, caption="The opening toy web: one link into Q from the hub outranks four links into V from pages nobody links to; arrow width is the mass each link carries.")


# ═══════════════════════════ Krackhardt kite centralities ═══════════════════
KITE = [(0,1),(0,2),(0,3),(0,5),(1,3),(1,4),(1,6),(2,3),(2,5),(3,4),(3,5),(3,6),(4,6),(5,6),(5,7),(6,7),(7,8),(8,9)]
KN = 10
KNAMES = ["Andre", "Beverly", "Carol", "Diane", "Ed", "Fernando", "Garth", "Heather", "Ike", "Jane"]
KPOS = [(120, 120), (300, 100), (95, 235), (208, 180), (322, 235), (140, 320), (280, 330), (210, 415 - 15), (210, 415 + 45 - 15), (210, 505 - 15)]
KPOS = [(x + 30, int(y * 0.72) + 10) for x, y in KPOS]

adjK = {i: set() for i in range(KN)}
for a, b in KITE:
    adjK[a].add(b); adjK[b].add(a)

deg = [len(adjK[i]) for i in range(KN)]

def bfs_dist(s):
    dist = {s: 0}
    q = deque([s])
    while q:
        u = q.popleft()
        for v in adjK[u]:
            if v not in dist:
                dist[v] = dist[u] + 1
                q.append(v)
    return dist

clo = [ (KN - 1) / sum(bfs_dist(s).values()) for s in range(KN)]

# betweenness by path enumeration (BFS DAG counting)
btw = [0.0] * KN
for s in range(KN):
    dist = bfs_dist(s)
    sigma = {v: 0 for v in range(KN)}; sigma[s] = 1
    order = sorted(dist, key=dist.get)
    for u in order:
        for v in adjK[u]:
            if dist[v] == dist[u] + 1:
                sigma[v] += sigma[u]
    delta = {v: 0.0 for v in range(KN)}
    for u in reversed(order):
        for v in adjK[u]:
            if dist[v] == dist[u] + 1:
                delta[u] += sigma[u] / sigma[v] * (1 + delta[v])
        if u != s:
            btw[u] += delta[u]
btw = [b / 2 for b in btw]

eig = [1.0] * KN
for _ in range(300):
    nxt = [sum(eig[j] for j in adjK[i]) for i in range(KN)]
    nrm = math.sqrt(sum(x * x for x in nxt))
    eig = [x / nrm for x in nxt]

def argmaxes(vals):
    m = max(vals)
    return [i for i in range(KN) if vals[i] >= m - 1e-9]

CHAMPS = [
    ("degree", argmaxes(deg), "var(--dkr-accent, #d9603b)", ["most connections"]),
    ("closeness", argmaxes(clo), "var(--dkr-green, #199473)", ["shortest average distance", "to everyone"]),
    ("betweenness", argmaxes(btw), "#7c5cd6", ["sits on the most", "shortest paths"]),
    ("eigenvector", argmaxes(eig), "#d9a62e", ["connected to the", "well-connected —", "agrees with degree here"]),
]
# panel-heading text color: the gold node color fails AA as 14.5px text on the light
# cream page, so the eigenvector heading darkens one step (nodes keep the gold)
HEAD_COLOR = {"eigenvector": "#a87f18"}
# the kite's teaching point: three measures disagree, eigenvector sides with degree
assert CHAMPS[0][1] == [3] and CHAMPS[1][1] == [5, 6] and CHAMPS[2][1] == [7], \
    f"kite champions changed: {[(c[0], c[1]) for c in CHAMPS]}"
assert CHAMPS[3][1] == CHAMPS[0][1], "caption claims eigenvector agrees with degree"

panels = []
for pi, (cname, champs, color, desc) in enumerate(CHAMPS):
    ox = 20 + (pi % 2) * 375
    oy = 8 + (pi // 2) * 196
    g = [f'  <g transform="translate({ox},{oy}) scale(0.44)">']
    g.append('    <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="2.6" opacity="0.6">')
    for a, b in KITE:
        g.append(f'      <line x1="{KPOS[a][0]}" y1="{KPOS[a][1]}" x2="{KPOS[b][0]}" y2="{KPOS[b][1]}"/>')
    g.append("    </g>")
    for i in range(KN):
        x, y = KPOS[i]
        is_c = i in champs
        rr = (26 if len(champs) == 1 else 23) if is_c else 15
        g.append(f'      <circle cx="{x}" cy="{y}" r="{rr}" fill="{color if is_c else "var(--dkr-muted, #8e8e9a)"}" opacity="{1 if is_c else 0.45}"/>')
    for c in champs:
        cx, cy = KPOS[c]
        fs = 26 if len(champs) == 1 else 22
        g.append(f'      <text x="{cx}" y="{cy + fs // 3}" text-anchor="middle" font-family="{SANS}" font-size="{fs}" font-weight="700" fill="#fff">{KNAMES[c][0]}</text>')
    g.append("  </g>")
    if len(champs) == 1:
        champ_lines = [f"champion: {KNAMES[champs[0]]}"]
    else:
        champ_lines = ["champions (tied):", " &amp; ".join(KNAMES[c] for c in champs)]
    lines = "\n".join(
        f'    <text x="0" y="{20 + 18 * li}" font-size="12.5" fill="var(--dkr-text, #1c1c21)">{line}</text>'
        for li, line in enumerate(champ_lines)) + "\n" + "\n".join(
        f'    <text x="0" y="{20 + 18 * len(champ_lines) + 17 * li}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">{line}</text>'
        for li, line in enumerate(desc))
    g.append(f'''  <g font-family="{SANS}" transform="translate({ox + 190},{oy + 30})">
    <text x="0" y="0" font-size="14.5" font-weight="700" fill="{HEAD_COLOR.get(cname, color)}">{cname}</text>
{lines}
  </g>''')
    panels.append("\n".join(g))
panels.append(f'  <text x="380" y="396" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">Krackhardt\'s kite: three measures, three different champions — and eigenvector sides with degree</text>')
write("fig-w2-centralities", "\n".join(panels),
      "The Krackhardt kite network shown four times; degree crowns Diane, closeness crowns the tied Fernando and Garth, betweenness crowns Heather, and eigenvector agrees with degree — all computed from the graph",
      caption="Krackhardt's kite: three centralities, three different champions — and eigenvector centrality sides with degree.")


# ═════════════════════════════ WL refinement on the cast ═════════════════════
CAST = [(0, 1), (0, 2), (0, 3), (1, 2), (2, 4), (2, 5), (4, 5)]
CN = 6
CNAMES = "ABCDEF"
CPOS = [(120, 105), (215, 48), (280, 118), (68, 172), (224, 185), (368, 172)]
adjC = {i: sorted({b for a, b in CAST if a == i} | {a for a, b in CAST if b == i}) for i in range(CN)}

# one visual color per WL color id, no wraparound: round 0 uses id 0, round 1 ids
# 1-4, round 2 ids 5-9 — a color id must keep one visual color across the figure.
# The five round-2 colors (ids 5-9) are hue-separated: pink, blue, brown, red, green
# (the old set had green-vs-olive and pink/red/brown near-collisions).
# KEEP IN SYNC with WLPAL in assets/d3/w2-wl.js (the widget shares these ids).
WLPAL = ["#8e8e9a", "#d9603b", "#0f8377", "#7c5cd6", "#d9a62e",
         "#d1567e", "#2e7dd1", "#8a5a33", "#cf4a30", "#199473"]

colors = [0] * CN
rounds = [list(colors)]
tables = []
for r in range(2):
    sigs = [(colors[i], tuple(sorted(colors[j] for j in adjC[i]))) for i in range(CN)]
    seen = {}
    newc = []
    for s in sigs:
        if s not in seen:
            seen[s] = len(seen) + max(colors) + 1
        newc.append(seen[s])
    tables.append(sorted(seen.items(), key=lambda kv: kv[1]))
    colors = newc
    rounds.append(list(colors))

parts = []
for ri, cols in enumerate(rounds):
    ox = 8 + ri * 240
    parts.append(f'  <g transform="translate({ox},30) scale(0.58)">')
    parts.append('    <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="2.4" opacity="0.65">')
    for a, b in CAST:
        parts.append(f'      <line x1="{CPOS[a][0]}" y1="{CPOS[a][1]}" x2="{CPOS[b][0]}" y2="{CPOS[b][1]}"/>')
    parts.append("    </g>")
    for i in range(CN):
        x, y = CPOS[i]
        parts.append(f'      <circle cx="{x}" cy="{y}" r="20" fill="{WLPAL[cols[i] % len(WLPAL)]}"/>')
        parts.append(f'      <text x="{x}" y="{y + 7}" text-anchor="middle" font-family="{SANS}" font-size="19" font-weight="700" fill="#fff">{CNAMES[i]}</text>')
    parts.append("  </g>")
    ncls = len(set(cols))
    parts.append(f'  <text x="{ox + 128}" y="22" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="var(--dkr-text, #1c1c21)">round {ri} · {ncls} color{"s" if ncls > 1 else ""}</text>')
    parts.append(f'  <text x="{ox + 128}" y="176" text-anchor="middle" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">{"everyone identical" if ri == 0 else ("split by degree" if ri == 1 else "stable — refinement done")}</text>')

# relabeling table for round 1→2
parts.append(f'  <g font-family="{SANS}" transform="translate(70,215)">')
parts.append('    <text x="0" y="0" font-size="13" font-weight="700" fill="var(--dkr-text, #1c1c21)">the relabeling rule, round 2:  new color = HASH( my color , multiset of neighbor colors )</text>')
n_rows = (len(tables[1]) + 2) // 3
for i, ((own, nbrs), new) in enumerate(tables[1]):
    row = i // 3
    in_row = min(3, len(tables[1]) - 3 * row)
    x = (i % 3) * 210 + (3 - in_row) * 105          # center a short last row
    y = 30 + row * 26
    nb = "{" + ",".join(str(c) for c in nbrs) + "}"
    parts.append(f'    <text x="{x}" y="{y}" font-size="12.5" font-family="\'JetBrains Mono\', monospace" fill="var(--dkr-text, #1c1c21)">({own}, {nb})</text>')
    parts.append(f'    <text x="{x + 122}" y="{y}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">→</text>')
    parts.append(f'    <circle cx="{x + 154}" cy="{y - 4}" r="9" fill="{WLPAL[new % len(WLPAL)]}"/>')
parts.append("  </g>")
hist = {}
for c in rounds[-1]:
    hist[c] = hist.get(c, 0) + 1
parts.append(f'''  <g font-family="{SANS}">
    <rect x="60" y="358" width="640" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="378" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">histogram {tuple(sorted(hist.values()))} after round 2 · the fingerprint stacks every round: (6 | 1,3,1,1 | 1,1,1,1,2)</text>
  </g>''')
write("fig-w2-wl", "\n".join(parts),
      "Two rounds of Weisfeiler-Lehman color refinement on the cast graph: from one shared color, to degree classes, to a stable five-color partition, with the hash relabeling table",
      caption="Two rounds of color refinement on the cast graph; the hash table at the bottom is the algorithm, and the banner reads the round-2 histogram.")


# ═════════════════════════════ Karate Fiedler split ═════════════════════════
# The club is drawn EXACTLY as Lecture 1's live hero lays it out (layout_w1: the
# converged d3-force positions, shifted right to balance the canvas), with the same
# node radii (10, leaders 15) and edge style, so the reader recognises one object.
from karate_common import layout_w1
FX, FH = 40, 500                      # horizontal shift; canvas height
P = layout_w1(dx=FX)
fv = fiedler_vector()
pred_hi = {i for i in range(K_N) if fv[i] * (1 if fv[0] > 0 else -1) > 0}
agree = sum(1 for i in range(K_N) if (i in pred_hi) == (i in MR_HI))
# align the eigenvector's arbitrary sign with whichever labeling agrees more
flip = (K_N - agree) > agree
agree = max(agree, K_N - agree)
wrong = [i for i in range(K_N) if ((i in pred_hi) != (i in MR_HI)) != flip]
R_MEMBER, R_LEADER, R_MISS = 10, 15, 12


def f_radius(i):
    return R_LEADER if i in (0, 33) else R_MEMBER


def clearance_box(x0, y0, x1, y1, ignore=()):
    # Smallest gap between a label box and any node rim (negative = overlap).
    best = 1e9
    for i, (x, y) in enumerate(P):
        if i in ignore:
            continue
        dx = max(x0 - x, 0.0, x - x1)
        dy = max(y0 - y, 0.0, y - y1)
        best = min(best, math.hypot(dx, dy) - f_radius(i))
    return best


def seg_clear(ax, ay, bx, by, ignore=()):
    best = 1e9
    for i, (px, py) in enumerate(P):
        if i in ignore:
            continue
        vx, vy = bx - ax, by - ay
        t = max(0.0, min(1.0, ((px - ax) * vx + (py - ay) * vy) / (vx * vx + vy * vy)))
        best = min(best, math.hypot(px - (ax + t * vx), py - (ay + t * vy)) - f_radius(i))
    return best


def place_name(i, text, size=13):
    # Leader name above or below its node, whichever side is clear (as the hero does).
    x, y = P[i]
    w = len(text) * size * 0.52
    cands = [(x, y - f_radius(i) - 10), (x, y + f_radius(i) + 18)]
    scored = []
    for cx, cy in cands:
        cx = min(max(cx, 20 + w / 2), 740 - w / 2)
        scored.append((clearance_box(cx - w / 2, cy - size, cx + w / 2, cy + 3, ignore=(i,)), cx, cy))
    scored.sort(reverse=True)
    return scored[0][1], scored[0][2]


parts = ['  <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1.3" opacity="0.45">']
for a, b in K_EDGES:
    parts.append(f'    <line x1="{P[a][0]}" y1="{P[a][1]}" x2="{P[b][0]}" y2="{P[b][1]}"/>')
parts.append("  </g>")
for i in range(K_N):
    if i in wrong:
        continue
    x, y = P[i]
    fill = C_HI if ((i in pred_hi) != flip) else C_OFF
    parts.append(f'  <circle cx="{x}" cy="{y}" r="{f_radius(i)}" fill="{fill}" opacity="0.9"/>')

# the two misses: ringed and drawn last, each tagged with its member number on the
# clearest side of the node, so nothing has to be drawn across the cloud; the
# explanation sits in whichever bottom corner is free
for i in wrong:
    x, y = P[i]
    fill = C_HI if ((i in pred_hi) != flip) else C_OFF
    parts.append(f'  <circle cx="{x}" cy="{y}" r="{R_MISS}" fill="{fill}" stroke="#cf4a30" stroke-width="4.5"/>')
for i in wrong:
    x, y = P[i]
    best = None
    for k in range(12):
        ang = 2 * math.pi * k / 12
        tx, ty = x + 26 * math.cos(ang), y + 26 * math.sin(ang)
        c = clearance_box(tx - 6, ty - 10, tx + 6, ty + 3, ignore=(i,))
        if best is None or c > best[0]:
            best = (c, tx, ty)
    _, tx, ty = best
    parts.append(f'  <text x="{tx:.0f}" y="{ty + 4:.0f}" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="#cf4a30" stroke="var(--dkr-bg, #fbfbfa)" stroke-width="3.5" paint-order="stroke">{i}</text>')
note1 = f"the two misses — members {wrong[0]} and {wrong[1]}, ringed"
note2 = "each disagrees with the real 1977 split"
wn = max(len(note1) * 13.5, len(note2) * 12.5) * 0.52
corner = None
for cx_ in (170 + wn / 2, 590 - wn / 2 + 150):
    cx_ = min(max(cx_, 20 + wn / 2), 740 - wn / 2)
    c = clearance_box(cx_ - wn / 2, FH - 96, cx_ + wn / 2, FH - 60)
    if corner is None or c > corner[0]:
        corner = (c, cx_)
_, miss_label_x = corner
miss_label_y = FH - 78
parts.append(f'  <text x="{miss_label_x:.0f}" y="{miss_label_y}" text-anchor="middle" font-family="{SANS}" font-size="13.5" font-weight="700" fill="#cf4a30">{note1}</text>')
parts.append(f'  <text x="{miss_label_x:.0f}" y="{miss_label_y + 17}" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #8e8e9a)">{note2}</text>')

# the two leaders, named as in Lecture 1
for i, name in ((0, "Mr. Hi (instructor)"), (33, "the Officer (president)")):
    nx_, ny_ = place_name(i, name)
    parts.append(f'  <text x="{nx_:.0f}" y="{ny_:.0f}" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="var(--dkr-text, #1c1c21)" stroke="var(--dkr-bg, #fbfbfa)" stroke-width="4" paint-order="stroke">{name}</text>')

parts.append(f'''  <g font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #8e8e9a)">
    <circle cx="80" cy="30" r="7" fill="{C_HI}"/><text x="93" y="34">Fiedler says: Mr. Hi's side</text>
    <circle cx="262" cy="30" r="7" fill="{C_OFF}"/><text x="275" y="34">Fiedler says: the Officer's</text>
  </g>
  <g font-family="{SANS}">
    <rect x="120" y="{FH - 42}" width="520" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="{FH - 22}" text-anchor="middle" font-size="13.5" font-weight="700" fill="#fff">one eigenvector of L, thresholded at zero: {agree} of 34 members placed correctly</text>
  </g>''')
write("fig-w2-fiedler", "\n".join(parts),
      f"The karate club, drawn exactly as in Lecture 1, colored by the sign of the Fiedler vector of its Laplacian; {agree} of 34 members match the real split, the two disagreements ringed in red",
      h=FH,
      caption="The karate club colored by the sign of its Fiedler vector; the two ringed members are the ones the eigenvector places against the 1977 split.")
print(f"fiedler agreement: {agree}/34, wrong = {wrong}")
