#!/usr/bin/env python
"""Generate assets/figures/fig-w2-tenweb.html — the ten-node, two-group graph that the
Louvain widget (assets/d3/w2-louvain.js) runs on, as a compact reference strip with
degrees and the edge list, so the worked example that computes on it has every number
in view. Positions and edges mirror the widget exactly; degrees are derived here.
Run: python scripts/figgen/w2_tenweb.py
"""
from pathlib import Path

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"

EDGES = [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (3, 4), (2, 4), (0, 3),
         (5, 6), (5, 7), (6, 7), (6, 8), (7, 8), (8, 9), (7, 9), (5, 8),
         (4, 5), (4, 6)]
# the widget's layout, scaled into the left 470 px of the strip
WPOS = [(92, 128), (172, 62), (150, 196), (248, 132), (368, 126),
        (486, 66), (492, 190), (590, 62), (604, 194), (676, 128)]
SX, SY, OX, OY = 0.66, 0.68, 22, 34
POS = [(round(x * SX + OX), round(y * SY + OY)) for x, y in WPOS]
N = 10
deg = [0] * N
for a, b in EDGES:
    deg[a] += 1
    deg[b] += 1
m = len(EDGES)
cx = sum(p[0] for p in POS) / N
cy = sum(p[1] for p in POS) / N

parts = [f'  <text x="20" y="22" font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #8e8e9a)">the ten-node graph of the Louvain widget · two groups joined through node 4 · m = {m}</text>']
parts.append('  <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1.8" opacity="0.6">')
for a, b in EDGES:
    (x1, y1), (x2, y2) = POS[a], POS[b]
    parts.append(f'    <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}"/>')
parts.append("  </g>")
for i in range(N):
    x, y = POS[i]
    dx, dy = x - cx, y - cy
    L = (dx * dx + dy * dy) ** 0.5 or 1
    # node 4 sits at the centre: push its label straight up
    if i == 4:
        dx, dy, L = 0, -1, 1
    lx, ly = x + dx / L * 27, y + dy / L * 27
    fill = "var(--dkr-accent, #d9603b)" if i == 4 else ("var(--dkr-blue, #0f8377)" if i < 4 else "var(--dkr-purple, #7c5cd6)")
    parts.append(f'  <circle cx="{x}" cy="{y}" r="14" fill="{fill}" opacity="0.92"/>')
    parts.append(f'  <text x="{x}" y="{y + 4.5}" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" fill="#fff">{i}</text>')
    parts.append(f'  <text x="{lx:.0f}" y="{ly + 4:.0f}" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="var(--dkr-muted, #8e8e9a)">d={deg[i]}</text>')

# degree table on the right
tx, ty = 540, 62
parts.append(f'  <text x="{tx}" y="{ty - 22}" font-family="{SANS}" font-size="13.5" font-weight="700" fill="var(--dkr-text, #1c1c21)">degrees</text>')
for i in range(N):
    col = i // 5
    row = i % 5
    x = tx + col * 100
    y = ty + row * 22
    parts.append(f'  <text x="{x}" y="{y + 4}" font-family="{MONO}" font-size="12.5" fill="var(--dkr-text, #1c1c21)">d_{i} = {deg[i]}</text>')
parts.append(f'  <text x="{tx}" y="{ty + 5 * 22 + 8}" font-family="{MONO}" font-size="12.5" fill="var(--dkr-muted, #8e8e9a)">Σd = {sum(deg)} = 2m</text>')
edge_list = "  ".join(f"{a}–{b}" for a, b in EDGES)
parts.append(f'  <text x="250" y="216" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="var(--dkr-text, #1c1c21)">edges: {edge_list[:60]}</text>')
parts.append(f'  <text x="250" y="234" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="var(--dkr-text, #1c1c21)">{edge_list[60:].strip()}</text>')

aria = ("The ten-node graph the Louvain widget runs on: nodes 0 to 4 form one dense group and 5 to 9 another, joined through node 4, "
        f"with {m} edges; every node's degree is printed beside it and listed in a table.")
svg = ("```{=html}\n<figure class=\"dkr-fig\">\n"
       f"<svg viewBox=\"0 0 760 248\" role=\"img\" aria-label=\"{aria}\">\n"
       "  <!-- generated by scripts/figgen/w2_tenweb.py -->\n" + "\n".join(parts) + "\n</svg>\n</figure>\n```\n")
(FIGDIR / "fig-w2-tenweb.html").write_text(svg, encoding="utf-8")
print("wrote fig-w2-tenweb · degrees", deg, "· m =", m)
