#!/usr/bin/env python
"""Generate the four data-derived Week 3 figures:
  fig-w3-hero       — words vs walks: real skip-gram windows on a real generated walk
  fig-w3-encdec     — the encoder-decoder framework (schematic, labeled as such)
  fig-w3-pq         — node2vec transition probabilities, computed for two (p,q) settings
  fig-w3-embedding  — karate club in 2D from real walk co-occurrences (PPMI + SVD),
                      with the separation accuracy computed, not asserted
Run: python scripts/figgen/w3_figs.py
"""
import math
import random
from pathlib import Path

import numpy as np

from karate_common import EDGES as K_EDGES, N as K_N, MR_HI, C_HI, C_OFF

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"


def write(name, body, aria, height=400):
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 {height}\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/w3_figs.py -->\n{body}\n</svg>\n</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


# ══════════════════════════════ hero: words vs walks ═══════════════════════
CAST_EDGES = [(0, 1), (0, 2), (0, 3), (1, 2), (2, 4), (2, 5), (4, 5)]
CN = "ABCDEF"
adj = {i: sorted({b for a, b in CAST_EDGES if a == i} | {a for a, b in CAST_EDGES if b == i})
       for i in range(6)}

# a real seeded walk — deterministically pick the first seed whose walk reads well:
# no self-pair inside the demo window (a (X,X) pair is correct but a confusing FIRST
# example) and at least 5 distinct nodes visited
for seed in range(1, 200):
    rng = random.Random(seed)
    walk = [3]                               # start at D, the leaf — it must leave
    for _ in range(7):
        walk.append(rng.choice(adj[walk[-1]]))
    center = walk[3]
    window = walk[1:3] + walk[4:6]
    if center not in window and len(set(walk)) >= 5:
        break
WTOK = [CN[i] for i in walk]
print("hero walk:", " ".join(WTOK), f"(seed {seed})")
for a, b in zip(walk, walk[1:]):
    assert b in adj[a], "generated walk uses a non-edge"

SENT = ["the", "spectral", "gap", "controls", "mixing", "speed", "everywhere"]
CW = 3                                        # center index for the word window
CN_IDX = 3                                    # center index for the walk window
W = 2                                         # window half-size

word_pairs = [(SENT[CW], SENT[j]) for j in range(max(0, CW - W), min(len(SENT), CW + W + 1)) if j != CW]
walk_pairs = [(WTOK[CN_IDX], WTOK[j]) for j in range(max(0, CN_IDX - W), min(len(WTOK), CN_IDX + W + 1)) if j != CN_IDX]

def token_row(tokens, y, center, mono=False, cell=None):
    cell = cell or (88 if not mono else 46)
    x0 = 380 - cell * len(tokens) / 2
    parts = []
    for i, t in enumerate(tokens):
        x = x0 + i * cell
        hot = i == center
        inwin = abs(i - center) <= W and not hot
        fill = "var(--dkr-accent, #d9603b)" if hot else ("var(--dkr-blue, #0f8377)" if inwin else "none")
        stroke = "none" if (hot or inwin) else "var(--dkr-muted, #8e8e9a)"
        parts.append(f'    <rect x="{x + 3:.0f}" y="{y}" width="{cell - 6}" height="30" rx="8" fill="{fill}" opacity="{1 if hot else 0.85 if inwin else 1}" stroke="{stroke}" stroke-width="1.2"/>')
        tfill = "#fff" if (hot or inwin) else "var(--dkr-text, #1c1c21)"
        parts.append(f'    <text x="{x + cell / 2:.0f}" y="{y + 20}" text-anchor="middle" font-family="{MONO}" font-size="{13 if not mono else 14}" fill="{tfill}">{t}</text>')
    return "\n".join(parts)

pairs_txt = lambda ps: "  ".join(f"({a},{b})" for a, b in ps)

hero = [f'  <g font-family="{SANS}" font-size="14.5" font-weight="700" fill="var(--dkr-text, #1c1c21)">',
        '    <text x="380" y="30" text-anchor="middle">2013 — word2vec: a word is known by the company it keeps</text>',
        '    <text x="380" y="196" text-anchor="middle">2014 — DeepWalk: so is a node. A random walk IS a sentence</text>',
        "  </g>"]
hero.append(token_row(SENT, 48, CW))
hero.append(f'  <text x="380" y="112" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">training pairs from this window:  {pairs_txt(word_pairs)}</text>')
hero.append(f'  <text x="380" y="134" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">center word (terracotta) predicts its context (teal), window ±{W}</text>')
hero.append(token_row(WTOK, 214, CN_IDX, mono=True))
hero.append(f'  <text x="380" y="278" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">training pairs from this window:  {pairs_txt(walk_pairs)}</text>')
hero.append(f'  <text x="380" y="300" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">a real walk on the cast graph (started at D, seeded RNG) — every step follows an edge</text>')
hero.append(f'''  <g font-family="{SANS}">
    <rect x="110" y="330" width="540" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="350" text-anchor="middle" font-size="13.5" font-weight="700" fill="var(--dkr-bg, #fff)">same algorithm, unchanged — graph people hijacked word2vec within a year</text>
  </g>''')
write("fig-w3-hero", "\n".join(hero),
      "A sentence with a skip-gram window above, and a real random walk on the cast graph with the identical window below: the training pairs are extracted the same way",
      height=375)


# ═══════════════════════════ encoder-decoder schematic ═════════════════════
enc = [f'  <text x="380" y="26" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">the four-part template every method in Weeks 3–6 instantiates (schematic)</text>']
boxes = [
    (30, 60, 180, 120, "ENCODER", "node → vector", "var(--dkr-blue, #0f8377)"),
    (290, 60, 180, 120, "DECODER", "two vectors → score", "var(--dkr-accent, #d9603b)"),
    (550, 60, 180, 120, "SIMILARITY", "what the graph says", "#7c5cd6"),
]
for x, y, w, h, title, sub, color in boxes:
    enc.append(f'''  <g font-family="{SANS}">
    <rect x="{x}" y="{y}" width="{w}" height="{h}" rx="14" fill="{color}" opacity="0.13"/>
    <rect x="{x}" y="{y}" width="{w}" height="{h}" rx="14" fill="none" stroke="{color}" stroke-width="2.2"/>
    <text x="{x + w / 2}" y="{y + 28}" text-anchor="middle" font-size="15" font-weight="700" fill="{color}">{title}</text>
    <text x="{x + w / 2}" y="{y + 48}" text-anchor="middle" font-size="12" fill="var(--dkr-muted, #6e6e7a)">{sub}</text>
  </g>''')
enc.append(f'''  <g font-family="{MONO}" font-size="13" fill="var(--dkr-text, #1c1c21)" text-anchor="middle">
    <text x="120" y="140">ENC(u) = Z[u]</text>
    <text x="120" y="160" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">a lookup table, n × d</text>
    <text x="380" y="140">DEC(u, v) = z_u · z_v</text>
    <text x="380" y="160" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">dot product, this week</text>
    <text x="640" y="140">S(u, v)</text>
    <text x="640" y="160" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">walk co-occurrence</text>
  </g>
  <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="2" fill="none">
    <path d="M210,120 L286,120" marker-end="url(#w3eArrow)"/>
    <path d="M550,120 L474,120" marker-end="url(#w3eArrow)"/>
  </g>
  <g font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)" text-anchor="middle">
    <text x="248" y="110">vectors</text>
    <text x="512" y="110">targets</text>
    <text x="404" y="206" text-anchor="start">scores</text>
  </g>
  <defs><marker id="w3eArrow" markerWidth="9" markerHeight="9" refX="7" refY="3.5" orient="auto"><path d="M0,0 L8,3.5 L0,7 Z" fill="var(--dkr-muted, #8e8e9a)"/></marker></defs>
  <g font-family="{SANS}">
    <path d="M380,180 L380,222" stroke="var(--dkr-green, #199473)" stroke-width="2.2" marker-end="url(#w3eArrow)" fill="none"/>
    <rect x="30" y="226" width="700" height="54" rx="14" fill="var(--dkr-green, #199473)" opacity="0.13"/>
    <rect x="30" y="226" width="700" height="54" rx="14" fill="none" stroke="var(--dkr-green, #199473)" stroke-width="2.2"/>
    <text x="380" y="249" text-anchor="middle" font-size="15" font-weight="700" fill="var(--dkr-green, #199473)">LOSS</text>
    <text x="380" y="268" text-anchor="middle" font-size="12" fill="var(--dkr-muted, #6e6e7a)">make the decoder's score match the graph's similarity</text>
  </g>
  <text x="380" y="312" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">training adjusts ONLY the table Z — gradients flow into the rows of a matrix, nothing else</text>''')
write("fig-w3-encdec", "\n".join(enc),
      "Schematic of the encoder-decoder framework: an embedding-lookup encoder and dot-product decoder are trained so pair scores match a walk-based similarity",
      height=330)


# ═════════════════════════ node2vec p/q probabilities ══════════════════════
def pq_weights(p, q):
    # v's neighbors: t (the previous node, dist 0 from t), x1 (dist 1), x2, x3 (dist 2)
    raw = {"t": 1 / p, "x1": 1.0, "x2": 1 / q, "x3": 1 / q}
    z = sum(raw.values())
    return {k: v / z for k, v in raw.items()}

POS = {"t": (95, 200), "v": (240, 130), "x1": (135, 60), "x2": (355, 55), "x3": (370, 200)}
NBR_EDGES = [("t", "v"), ("v", "x1"), ("v", "x2"), ("v", "x3"), ("t", "x1")]

def pq_panel(ox, p, q, title, color):
    wts = pq_weights(p, q)
    g = [f'  <g transform="translate({ox},40)">']
    g.append(f'    <text x="230" y="6" text-anchor="middle" font-family="{SANS}" font-size="14" font-weight="700" fill="{color}">{title}</text>')
    g.append(f'    <text x="230" y="26" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">p = {p}, q = {q}</text>')
    g.append('    <g stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1.6" opacity="0.5">')
    for a, b in NBR_EDGES:
        g.append(f'      <line x1="{POS[a][0]}" y1="{POS[a][1]}" x2="{POS[b][0]}" y2="{POS[b][1]}"/>')
    g.append("    </g>")
    for k, w in wts.items():
        x, y = POS[k]
        g.append(f'      <line x1="{POS["v"][0]}" y1="{POS["v"][1]}" x2="{x}" y2="{y}" stroke="{color}" stroke-width="{1.5 + 14 * w:.1f}" opacity="0.45"/>')
    for k, (x, y) in POS.items():
        is_v = k == "v"
        is_t = k == "t"
        fill = "var(--dkr-accent, #d9603b)" if is_v else ("var(--dkr-yellow, #d9a62e)" if is_t else "var(--dkr-muted, #8e8e9a)")
        g.append(f'      <circle cx="{x}" cy="{y}" r="{17 if is_v else 14}" fill="{fill}" opacity="{1 if (is_v or is_t) else 0.55}"/>')
        # theme text color on the translucent gray nodes: dark-on-light in light
        # theme, light-on-dark in dark theme (white was borderline in light)
        tfill = "#fff" if (is_v or is_t) else "var(--dkr-text, #1c1c21)"
        g.append(f'      <text x="{x}" y="{y + 4.5}" text-anchor="middle" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{tfill}">{k}</text>')
    for k, w in wts.items():
        x, y = POS[k]
        dx, dy = x - POS["v"][0], y - POS["v"][1]
        d = math.hypot(dx, dy)
        lx, ly = x + dx / d * 23, y + dy / d * 23
        g.append(f'      <text x="{lx:.0f}" y="{ly + 4:.0f}" text-anchor="middle" font-family="{MONO}" font-size="12" font-weight="700" fill="{color}">{w:.0%}</text>')
    g.append("  </g>")
    return "\n".join(g)

pq = ['  <text x="380" y="24" text-anchor="middle" font-family="{}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">the walker sits at v, having arrived from t — where next? (computed transition probabilities)</text>'.format(SANS)]
pq.append(pq_panel(-30, 0.25, 4.0, "return-and-orbit (BFS-like)", "var(--dkr-blue, #0f8377)"))
pq.append(pq_panel(350, 4.0, 0.25, "push outward (DFS-like)", "var(--dkr-accent, #b84a2b)"))
pq.append(f'''  <g font-family="{SANS}">
    <rect x="110" y="292" width="540" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="312" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">1/p back · 1 sideways · 1/q outward — two knobs, one dial: BFS ↔ DFS</text>
  </g>''')
write("fig-w3-pq", "\n".join(pq),
      "Two copies of the node2vec step: with p=0.25, q=4 most probability returns toward t; with p=4, q=0.25 most probability pushes outward — edge widths and percentages computed from the formula",
      height=340)


# ══════════════════ karate in 2D: PPMI of real walks + SVD ═════════════════
kadj = {i: [] for i in range(K_N)}
for a, b in K_EDGES:
    kadj[a].append(b); kadj[b].append(a)

wrng = random.Random(5)
walks = []
for _ in range(30):
    for s in range(K_N):
        wk = [s]
        for _ in range(19):
            wk.append(wrng.choice(kadj[wk[-1]]))
        walks.append(wk)

WIN = 4
C = np.zeros((K_N, K_N))
for wk in walks:
    for i, u in enumerate(wk):
        for j in range(max(0, i - WIN), min(len(wk), i + WIN + 1)):
            if j != i:
                C[u, wk[j]] += 1
total = C.sum()
row = C.sum(axis=1, keepdims=True)
with np.errstate(divide="ignore", invalid="ignore"):
    pmi = np.log(C * total / (row @ row.T))
ppmi = np.maximum(pmi, 0)
ppmi[~np.isfinite(ppmi)] = 0
# center columns before factorizing (PCA): the raw first singular direction is
# dominated by visit frequency and flattens the picture into an arc
centered = ppmi - ppmi.mean(axis=0, keepdims=True)
U, S, _ = np.linalg.svd(centered, full_matrices=False)
emb = U[:, :2] * np.sqrt(S[:2])

# separation: logistic regression on the 2 dims, plain gradient descent
y = np.array([1.0 if i in MR_HI else 0.0 for i in range(K_N)])
Xb = np.hstack([emb, np.ones((K_N, 1))])
wvec = np.zeros(3)
for _ in range(5000):
    pred = 1 / (1 + np.exp(-Xb @ wvec))
    wvec -= 0.1 * Xb.T @ (pred - y) / K_N
acc = int(((Xb @ wvec > 0) == (y > 0.5)).sum())
print(f"embedding linear separation: {acc}/34")

xs, ys_ = emb[:, 0], emb[:, 1]
sx = lambda x: 70 + (x - xs.min()) / (xs.max() - xs.min()) * 620
sy = lambda v: 80 + (v - ys_.min()) / (ys_.max() - ys_.min()) * 240
parts = [f'  <text x="380" y="26" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">every friendship edge is invisible here — only walk co-occurrence placed these points</text>']
# coordinate-plane frame: claims the empty center-left as embedding space, not
# an unfinished scatter; axis names say what the two coordinates are
parts.append('  <rect x="48" y="62" width="664" height="276" rx="6" fill="none" stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1.2" opacity="0.4"/>')
parts.append(f'  <text x="702" y="330" text-anchor="end" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #8e8e9a)">dim 1 →</text>')
parts.append(f'  <text x="62" y="204" text-anchor="middle" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #8e8e9a)" transform="rotate(-90 62 204)">dim 2 →</text>')
# ringed boundary members drawn LAST so their rings sit above every fill
for i in [j for j in range(K_N) if j not in (2, 8)] + [2, 8]:
    x, yv = sx(xs[i]), sy(ys_[i])
    fill = C_HI if i in MR_HI else C_OFF
    ring = ' stroke="#cf4a30" stroke-width="2.6"' if i in (2, 8) else ""
    r = 12 if i in (0, 33) else 8
    parts.append(f'  <circle cx="{x:.1f}" cy="{yv:.1f}" r="{r}" fill="{fill}" opacity="0.9"{ring}/>')
parts.append(f'''  <g font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #8e8e9a)">
    <circle cx="90" cy="50" r="7" fill="{C_HI}"/><text x="103" y="54">Mr. Hi's faction</text>
    <circle cx="230" cy="50" r="7" fill="{C_OFF}"/><text x="243" y="54">the Officer's</text>
    <text x="690" y="54" text-anchor="end">red ring = Week 2's boundary members 2 and 8</text>
  </g>
  <g font-family="{SANS}">
    <rect x="115" y="350" width="530" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="370" text-anchor="middle" font-size="13.5" font-weight="700" fill="var(--dkr-bg, #fff)">2 learned coordinates per member — one straight line separates {acc} of 34</text>
  </g>''')
write("fig-w3-embedding", "\n".join(parts),
      f"The 34 karate club members placed in a framed two-dimensional coordinate plane by factorizing the PPMI matrix of real random-walk co-occurrences; the factions form two separable groups and a straight line classifies {acc} of 34",
      height=396)
