#!/usr/bin/env python
"""Generate the four data-derived Week 4 figures:
  fig-w4-hero      — the Lab-1 Wikidata fragment with a composition-inferred missing fact
  fig-w4-scorers   — TransE / DistMult / ComplEx / RotatE geometry, all numbers computed
  fig-w4-patterns  — the relation-pattern cheat sheet (verified against RotatE Table 1)
  fig-w4-eval      — a filtered-ranking worked example with scores computed by TransE
Run: python scripts/figgen/w4_figs.py
"""
import cmath
import math
from pathlib import Path

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"


def write(name, body, aria, height=400):
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 {height}\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/w4_figs.py -->\n{body}\n</svg>\n</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


# ═══════════════════════════════ hero: the fragment ════════════════════════
TRIPLES = [
    ("IU", "instance_of", "university"), ("IU", "located_in", "Innopolis"),
    ("Innopolis", "located_in", "Tatarstan"), ("Kazan", "capital_of", "Tatarstan"),
    ("Kazan", "located_in", "Tatarstan"), ("Tatarstan", "part_of", "Russia"),
    ("KFU", "instance_of", "university"), ("KFU", "located_in", "Kazan"),
    ("Innopolis", "instance_of", "city"), ("Kazan", "instance_of", "city"),
    ("Tatarstan", "instance_of", "region"), ("Volga", "flows_through", "Tatarstan"),
]
EPOS = {
    "IU": (105, 84), "KFU": (105, 268), "Innopolis": (280, 84), "Kazan": (280, 268),
    "Tatarstan": (465, 176), "Russia": (650, 108), "Volga": (650, 250),
    "university": (105, 176), "city": (280, 176), "region": (465, 62),
}
RCOLOR = {"located_in": "var(--dkr-blue, #0f8377)", "instance_of": "var(--dkr-muted, #8e8e9a)",
          "capital_of": "var(--dkr-purple, #7c5cd6)", "part_of": "var(--dkr-green, #199473)",
          "flows_through": "#d1567e"}
# label ink: identity-pink is too low-contrast for text on either ground, so the
# label (not the edge) borrows a little of the theme's text color each way
LABEL_INK = {"flows_through":
             "color-mix(in srgb, #d1567e 76%, var(--dkr-text, #1c1c21) 24%)"}
# halo behind every floating label so edges never cut through the lettering
HALO = ('paint-order="stroke" stroke="var(--dkr-bg, #fbfbfa)" stroke-width="4" '
        'stroke-linejoin="round"')
ETYPE = {"university", "city", "region"}

# the inferred fact: located_in(IU, Innopolis) ∘ located_in(Innopolis, Tatarstan)
MISSING = ("IU", "located_in", "Tatarstan")
assert MISSING not in TRIPLES and ("IU", "located_in", "Innopolis") in TRIPLES \
    and ("Innopolis", "located_in", "Tatarstan") in TRIPLES, "composition premises must hold"

hero = ['  <defs><marker id="w4hA" markerWidth="8" markerHeight="8" refX="30" refY="3" orient="auto">'
        '<path d="M0,0 L7,3 L0,6 Z" fill="var(--dkr-muted, #8e8e9a)"/></marker>'
        '<marker id="w4hB" markerWidth="8" markerHeight="8" refX="30" refY="3" orient="auto">'
        '<path d="M0,0 L7,3 L0,6 Z" fill="var(--dkr-accent, #d9603b)"/></marker></defs>']
lab_pts = []
seen_pairs = {}
for h, r, t in TRIPLES:
    (x1, y1), (x2, y2) = EPOS[h], EPOS[t]
    # parallel facts between the same pair: curve the repeat so both stay visible
    bend = seen_pairs.get((h, t), 0)
    seen_pairs[(h, t)] = bend + 1
    if bend == 0:
        hero.append(f'  <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="{RCOLOR[r]}" '
                    f'stroke-width="1.8" opacity="0.6" marker-end="url(#w4hA)"/>')
        mx, my = (x1 + x2) / 2, (y1 + y2) / 2 - 7
    else:
        dxn, dyn = x2 - x1, y2 - y1
        L = math.hypot(dxn, dyn)
        px, py = -dyn / L, dxn / L                      # unit normal
        cxq, cyq = (x1 + x2) / 2 + px * 34, (y1 + y2) / 2 + py * 34
        hero.append(f'  <path d="M{x1},{y1} Q{cxq:.0f},{cyq:.0f} {x2},{y2}" fill="none" '
                    f'stroke="{RCOLOR[r]}" stroke-width="1.8" opacity="0.6" marker-end="url(#w4hA)"/>')
        mx, my = (x1 + x2) / 2 + px * 24, (y1 + y2) / 2 + py * 24 - 4
    if r != "instance_of":                       # label the interesting relations
        lab_pts.append((mx, my, r, RCOLOR[r]))
(x1, y1), (x2, y2) = EPOS[MISSING[0]], EPOS[MISSING[2]]
hero.append(f'  <line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="var(--dkr-accent, #d9603b)" '
            f'stroke-width="2.6" stroke-dasharray="7,5" opacity="0.9" marker-end="url(#w4hB)"/>')
# hand-tuned label anchors where the automatic midpoint sits on a crossing:
# capital_of above its own straight edge (the located_in curve bows the other
# way), flows_through below its edge, clear of the part_of/Russia cluster
LABEL_POS = {"capital_of": (348, 200), "flows_through": (552, 232),
             "part_of": (582, 150)}
seen_r = set()
for mx, my, r, c in lab_pts:
    if r in seen_r:
        continue
    seen_r.add(r)
    mx, my = LABEL_POS.get(r, (mx, my))
    ink = LABEL_INK.get(r)
    fill = f'style="fill:{ink}"' if ink else f'fill="{c}"'
    hero.append(f'  <text x="{mx:.0f}" y="{my:.0f}" text-anchor="middle" font-family="{MONO}" '
                f'font-size="12" {HALO} {fill}>{r}</text>')
# the instance_of edges are the fragment's type system — label one representative
# so every relation in a "typed, labeled, directed" figure is in fact labeled
hero.append(f'  <text x="472" y="125" text-anchor="start" font-family="{MONO}" font-size="12" '
            f'font-style="italic" {HALO} fill="var(--dkr-muted, #6e6e7a)">instance_of</text>')
for e, (x, y) in EPOS.items():
    is_type = e in ETYPE
    fill = "var(--dkr-paper, #fff)" if is_type else "var(--dkr-yellow, #d9a62e)"
    stroke = "var(--dkr-muted, #8e8e9a)" if is_type else "none"
    w = max(46, 11 * len(e) + 14)
    hero.append(f'  <g font-family="{SANS}">'
                f'<rect x="{x - w / 2}" y="{y - 15}" width="{w}" height="30" rx="15" fill="{fill}" '
                f'stroke="{stroke}" stroke-width="1.4"/>'
                f'<text x="{x}" y="{y + 4.5}" text-anchor="middle" font-size="12.5" font-weight="700" '
                f'fill="{"var(--dkr-muted, #6e6e7a)" if is_type else "#5c4508"}">{e}</text></g>')
hero.append(f'''  <text x="380" y="26" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">Lab 1's twelve Wikidata facts — now with types drawn as what they are: labeled, directed edges</text>
  <g font-family="{SANS}">
    <rect x="55" y="330" width="650" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="350" text-anchor="middle" font-size="13.5" font-weight="700" fill="var(--dkr-bg, #fff)">nobody stated IU⤍Tatarstan — located_in ∘ located_in implies it. Can vectors learn that?</text>
  </g>''')
write("fig-w4-hero", "\n".join(hero),
      "The course's twelve Wikidata triples drawn as a typed directed graph, with the unstated fact that Innopolis University is located in Tatarstan shown as a dashed inferred edge",
      height=372)


# ════════════════════════════ four scorers, computed ═══════════════════════
# TransE toy: h=(1,1), r=(2,1), t=(3,2) — exact hit; decoy t'=(3,1) at distance 1
th, tr, tt, tdec = (1, 1), (2, 1), (3, 2), (3, 1)
d_true = math.dist((th[0] + tr[0], th[1] + tr[1]), tt)
d_dec = math.dist((th[0] + tr[0], th[1] + tr[1]), tdec)
assert d_true == 0.0 and d_dec == 1.0

# DistMult toy: h=(2,1), r=(1,3), t=(1,2) — and the swap gives the SAME score
dh, dr, dt = (2, 1), (1, 3), (1, 2)
dm = sum(a * b * c for a, b, c in zip(dh, dr, dt))
dm_swap = sum(a * b * c for a, b, c in zip(dt, dr, dh))
assert dm == dm_swap == 8

# ComplEx toy (d=1): h=1+i, r=i, t=-1+i — swap flips the sign
ch, cr, ct = 1 + 1j, 1j, -1 + 1j
cx = (ch * cr * ct.conjugate()).real
cx_swap = (ct * cr * ch.conjugate()).real
assert cx == 2.0 and cx_swap == -2.0

# RotatE toy (d=1): h at 45°, r rotates by 90°, t at 135° — exact hit
rh = cmath.exp(1j * math.pi / 4)
rr = cmath.exp(1j * math.pi / 2)
rt = cmath.exp(1j * 3 * math.pi / 4)
assert abs(rh * rr - rt) < 1e-12

def spt(x, y, ox, oy, s=38):
    """toy plane coords -> panel svg coords"""
    return ox + 30 + x * s, oy + 148 - y * s

panels = []
# panel frame helper
def frame(ox, oy, title, formula, color):
    return (f'  <g font-family="{SANS}">'
            f'<text x="{ox + 92}" y="{oy + 16}" text-anchor="middle" font-size="14.5" font-weight="700" fill="{color}">{title}</text>'
            f'<text x="{ox + 92}" y="{oy + 34}" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">{formula}</text></g>')

# — TransE panel (0,0)
ox, oy = 12, 8
p = [frame(ox, oy, "TransE", "−‖h + r − t‖", "var(--dkr-accent, #d9603b)")]
hx, hy = spt(*th, ox, oy); tx, ty = spt(*tt, ox, oy); dx, dy = spt(*tdec, ox, oy)
sx_, sy_ = spt(th[0] + tr[0], th[1] + tr[1], ox, oy)
p.append(f'  <line x1="{hx}" y1="{hy}" x2="{sx_}" y2="{sy_}" stroke="var(--dkr-accent, #d9603b)" stroke-width="2.4" marker-end="url(#w4sA)"/>')
p.append(f'  <circle cx="{hx}" cy="{hy}" r="7" fill="var(--dkr-yellow, #d9a62e)"/>')
p.append(f'  <circle cx="{tx}" cy="{ty}" r="7" fill="var(--dkr-green, #199473)"/>')
p.append(f'  <circle cx="{dx}" cy="{dy}" r="6" fill="none" stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1.6"/>')
p.append(f'  <g font-family="{SANS}" font-size="12" font-weight="600">'
         f'<text x="{hx - 14}" y="{hy + 4}" fill="var(--dkr-text, #1c1c21)">h</text>'
         f'<text x="{(hx + sx_) / 2}" y="{(hy + sy_) / 2 - 8}" fill="var(--dkr-accent, #b84a2b)">+r</text>'
         f'<text x="{tx + 12}" y="{ty - 6}" fill="var(--dkr-green, #199473)">t ✓ score 0</text>'
         f'<text x="{dx + 11}" y="{dy + 12}" fill="var(--dkr-muted, #6e6e7a)">t′: −1</text></g>')
p.append(f'  <text x="{ox + 92}" y="{oy + 198}" text-anchor="middle" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">relation = a translation</text>')
panels.append("\n".join(p))

# — DistMult panel (1,0)
ox = 202
p = [frame(ox, oy, "DistMult", "Σ hᵢ rᵢ tᵢ", "var(--dkr-purple, #7c5cd6)")]
rows = [("h", dh, "var(--dkr-yellow, #d9a62e)"), ("r", dr, "var(--dkr-purple, #7c5cd6)"), ("t", dt, "var(--dkr-green, #199473)")]
for k, (nm, vec, color) in enumerate(rows):
    yy = oy + 58 + k * 34
    p.append(f'  <text x="{ox + 26}" y="{yy + 17}" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{color}">{nm}</text>')
    for j, v in enumerate(vec):
        p.append(f'  <rect x="{ox + 40 + j * 34}" y="{yy}" width="30" height="24" rx="5" fill="{color}" opacity="0.2"/>')
        p.append(f'  <text x="{ox + 55 + j * 34}" y="{yy + 16.5}" text-anchor="middle" font-family="{MONO}" font-size="12.5" fill="var(--dkr-text, #1c1c21)">{v}</text>')
p.append(f'  <text x="{ox + 92}" y="{oy + 180}" text-anchor="middle" font-family="{MONO}" font-size="12" fill="var(--dkr-text, #1c1c21)">2·1·1 + 1·3·2 = {dm}</text>')
p.append(f'  <text x="{ox + 92}" y="{oy + 198}" text-anchor="middle" font-family="{SANS}" font-size="12" font-weight="600" fill="var(--dkr-red, #cf4a30)">swap h↔t: still {dm_swap} — always</text>')
panels.append("\n".join(p))

# — ComplEx panel (2,0): the same one-drawing grammar as its siblings — a unit
# circle showing h, t, and the conjugate flip t̄ that breaks the swap symmetry
ox = 392
p = [frame(ox, oy, "ComplEx", "Re⟨h, r, t̄⟩", "var(--dkr-blue, #0f8377)")]
p.append(f'  <text x="{ox + 92}" y="{oy + 54}" text-anchor="middle" font-family="{MONO}" font-size="12" '
         f'fill="var(--dkr-text, #1c1c21)">h = 1+i · r = i · t = −1+i</text>')
ccx2, ccy2, R2 = ox + 92, oy + 114, 27
p.append(f'  <circle cx="{ccx2}" cy="{ccy2}" r="{R2}" fill="none" stroke="var(--dkr-border, #e8e7e3)" stroke-width="1.6"/>')
p.append(f'  <line x1="{ccx2 - R2 - 12}" y1="{ccy2}" x2="{ccx2 + R2 + 12}" y2="{ccy2}" '
         f'stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1" stroke-dasharray="2,3" opacity="0.7"/>')
for ang, nm, colr, open_dot, lx, ly, anc in [
        (45, "h", "var(--dkr-yellow, #d9a62e)", False, 10, -6, "start"),
        (135, "t", "var(--dkr-green, #199473)", False, -10, -6, "end"),
        (225, "t̄", "var(--dkr-green, #199473)", True, -10, 14, "end")]:
    px2 = ccx2 + R2 * math.cos(math.radians(ang))
    py2 = ccy2 - R2 * math.sin(math.radians(ang))
    if open_dot:
        p.append(f'  <circle cx="{px2:.1f}" cy="{py2:.1f}" r="5.5" fill="none" stroke="{colr}" stroke-width="1.8"/>')
    else:
        p.append(f'  <circle cx="{px2:.1f}" cy="{py2:.1f}" r="6" fill="{colr}"/>')
    p.append(f'  <text x="{px2 + lx:.1f}" y="{py2 + ly:.1f}" text-anchor="{anc}" font-family="{SANS}" '
             f'font-size="12" font-weight="600" fill="{colr}">{nm}</text>')
# the conjugate flip: t mirrors across the real axis to t̄
fa0, fa1 = math.radians(135), math.radians(225)
Rf = R2 + 9
p.append(f'  <path d="M {ccx2 + Rf * math.cos(fa0):.1f},{ccy2 - Rf * math.sin(fa0):.1f} '
         f'A {Rf},{Rf} 0 0 0 {ccx2 + Rf * math.cos(fa1):.1f},{ccy2 - Rf * math.sin(fa1):.1f}" '
         f'fill="none" stroke="var(--dkr-accent, #d9603b)" stroke-width="1.8" '
         f'stroke-dasharray="4,3" marker-end="url(#w4sA)"/>')
p.append(f'  <text x="{ox + 92}" y="{oy + 162}" text-anchor="middle" font-family="{MONO}" font-size="12" '
         f'fill="var(--dkr-text, #1c1c21)">Re(h·r·t̄) = {cx:+.0f} · swap {cx_swap:+.0f}</text>')
p.append(f'  <text x="{ox + 92}" y="{oy + 180}" text-anchor="middle" font-family="{SANS}" font-size="12" font-weight="600" fill="var(--dkr-green, #199473)">swap flips the score:</text>')
p.append(f'  <text x="{ox + 92}" y="{oy + 198}" text-anchor="middle" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">direction is back — for free</text>')
panels.append("\n".join(p))

# — RotatE panel (3,0)
ox = 574
p = [frame(ox, oy, "RotatE", "−‖h ∘ r − t‖, |rᵢ|=1", "var(--dkr-green, #199473)")]
ccx, ccy, R = ox + 92, oy + 122, 56
p.append(f'  <circle cx="{ccx}" cy="{ccy}" r="{R}" fill="none" stroke="var(--dkr-border, #e8e7e3)" stroke-width="1.6"/>')
for z, nm, color, ddx in [(rh, "h", "var(--dkr-yellow, #d9a62e)", 12), (rt, "t = h∘r", "var(--dkr-green, #199473)", -6)]:
    px, py = ccx + R * z.real, ccy - R * z.imag
    p.append(f'  <circle cx="{px:.1f}" cy="{py:.1f}" r="7" fill="{color}"/>')
    anchor = "start" if ddx > 0 else "end"
    p.append(f'  <text x="{px + ddx:.1f}" y="{py - 10:.1f}" text-anchor="{anchor}" font-family="{SANS}" font-size="12" font-weight="600" fill="{color}">{nm}</text>')
# 90° arc from h to t; its label sits in the (empty) circle center, clear of
# both the arc above and the formula line in the frame
a0, a1 = math.pi / 4, 3 * math.pi / 4
p.append(f'  <path d="M {ccx + (R + 14) * math.cos(a0):.1f},{ccy - (R + 14) * math.sin(a0):.1f} '
         f'A {R + 14},{R + 14} 0 0 0 {ccx + (R + 14) * math.cos(a1):.1f},{ccy - (R + 14) * math.sin(a1):.1f}" '
         f'fill="none" stroke="var(--dkr-accent, #d9603b)" stroke-width="2.2" marker-end="url(#w4sA)"/>')
p.append(f'  <text x="{ccx}" y="{ccy + 4}" text-anchor="middle" font-family="{SANS}" font-size="12" font-weight="600" fill="var(--dkr-accent, #b84a2b)">r = rotate 90°</text>')
p.append(f'  <text x="{ox + 92}" y="{oy + 198}" text-anchor="middle" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">relation = a rotation, per dim</text>')
panels.append("\n".join(p))

scor = ['  <defs><marker id="w4sA" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto">'
        '<path d="M0,0 L7,3 L0,6 Z" fill="var(--dkr-accent, #d9603b)"/></marker></defs>']
scor += panels
for k in range(1, 4):
    x = 12 + k * 190 - 5
    scor.append(f'  <line x1="{x}" y1="18" x2="{x}" y2="218" stroke="var(--dkr-border, #e8e7e3)" stroke-width="1"/>')
scor.append(f'''  <g font-family="{SANS}">
    <rect x="65" y="248" width="630" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="268" text-anchor="middle" font-size="13.5" font-weight="700" fill="var(--dkr-bg, #fff)">one decoder per geometry — every number above computed from the toy vectors shown</text>
  </g>''')
write("fig-w4-scorers", "\n".join(scor),
      "Four panels showing the TransE translation, DistMult trilinear product, ComplEx Hermitian product, and RotatE rotation scoring functions, each evaluated on concrete toy embeddings",
      height=290)


# ═════════════════════════════ pattern cheat sheet ═════════════════════════
# verified against RotatE (ICLR 2019) Table 1 + the standard 1-to-N analysis
PATTERNS = [
    ("symmetry", "r(a,b) ⇒ r(b,a)", [("✗", "forces r = 0"), ("✓", "built-in"), ("✓", "r real"), ("✓", "rᵢ = ±1")]),
    ("antisymmetry", "r(a,b) ⇒ ¬r(b,a)", [("✓", ""), ("✗", "can't — ever"), ("✓", ""), ("✓", "")]),
    ("inversion", "r₂ = r₁⁻¹", [("✓", "r₂ = −r₁"), ("✗", ""), ("✓", "r₂ = r̄₁"), ("✓", "r₂ = r₁⁻¹")]),
    ("composition", "r₃ = r₂ ∘ r₁", [("✓", "r₃ = r₁+r₂"), ("✗", ""), ("✗", ""), ("✓", "r₃ = r₁∘r₂")]),
    ("1-to-N", "one head, many tails", [("✗", "tails collapse"), ("✓", ""), ("✓", ""), ("✗", "bijective")]),
]
MODELS = [("TransE", "var(--dkr-accent, #d9603b)"), ("DistMult", "#7c5cd6"),
          ("ComplEx", "var(--dkr-blue, #0f8377)"), ("RotatE", "var(--dkr-green, #199473)")]

pat = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">what each scoring geometry can represent exactly — the model-selection cheat sheet</text>']
X0, Y0, CW, RH = 250, 44, 122, 52
for j, (m, color) in enumerate(MODELS):
    pat.append(f'  <text x="{X0 + CW * j + CW / 2}" y="{Y0 + 18}" text-anchor="middle" font-family="{SANS}" font-size="13.5" font-weight="700" fill="{color}">{m}</text>')
for i, (pname, pdef, cells) in enumerate(PATTERNS):
    yy = Y0 + 30 + i * RH
    if i % 2 == 0:
        pat.append(f'  <rect x="20" y="{yy}" width="720" height="{RH}" fill="var(--dkr-muted, #8e8e9a)" opacity="0.07"/>')
    pat.append(f'  <text x="30" y="{yy + 24}" font-family="{SANS}" font-size="13" font-weight="700" fill="var(--dkr-text, #1c1c21)">{pname}</text>')
    pat.append(f'  <text x="30" y="{yy + 41}" font-family="{MONO}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">{pdef}</text>')
    for j, (mark, why) in enumerate(cells):
        cx = X0 + CW * j + CW / 2
        good = mark == "✓"
        color = "var(--dkr-green, #199473)" if good else "var(--dkr-red, #cf4a30)"
        pat.append(f'  <text x="{cx}" y="{yy + 25}" text-anchor="middle" font-family="{SANS}" font-size="16" font-weight="800" fill="{color}">{mark}</text>')
        if why:
            pat.append(f'  <text x="{cx}" y="{yy + 42}" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">{why}</text>')
n_yes = sum(1 for _, _, cells in PATTERNS for m, _ in cells if m == "✓")
pat.append(f'''  <g font-family="{SANS}">
    <rect x="75" y="{Y0 + 30 + 5 * RH + 14}" width="610" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="{Y0 + 30 + 5 * RH + 34}" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">no model wins every row — the pattern your relations actually need picks your model</text>
  </g>''')
write("fig-w4-patterns", "\n".join(pat),
      "A five-by-four cheat sheet of relation patterns versus embedding models: which of symmetry, antisymmetry, inversion, composition, and one-to-many each of TransE, DistMult, ComplEx, and RotatE can represent, with the algebraic reason for the notable cells",
      height=Y0 + 30 + 5 * RH + 60)


# ═══════════════════════ filtered ranking, worked example ══════════════════
# TransE in 1D, hand-set so the story computes itself:
# entities on a line; query (Volga, flows_through, ?), true tail Tatarstan.
E1D = {"Tatarstan": 4.0, "Russia": 4.3, "Kazan": 1.0, "Innopolis": 2.2, "IU": 0.4, "Volga": 6.0}
R_FT = -1.8                                     # flows_through as a 1-D translation
QUERY_H, TRUE_T = "Volga", "Tatarstan"
KNOWN_TRUE = ("Volga", "flows_through", "Russia")   # in the training set — must be filtered

scores = {t: -abs(E1D[QUERY_H] + R_FT - E1D[t]) for t in E1D if t != QUERY_H}
ranked = sorted(scores, key=scores.get, reverse=True)
raw_rank = ranked.index(TRUE_T) + 1
filt_ranked = [t for t in ranked if t != KNOWN_TRUE[2]]
filt_rank = filt_ranked.index(TRUE_T) + 1
assert (raw_rank, filt_rank) == (2, 1), f"story needs ranks 2→1, got {raw_rank}→{filt_rank}"

ev = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">query: (Volga, flows_through, ?) · truth: Tatarstan · scores from a 1-D TransE, computed</text>']
ev.append(f'  <g font-family="{SANS}" font-size="13" font-weight="700" fill="var(--dkr-text, #1c1c21)">'
          f'<text x="205" y="56" text-anchor="middle">raw ranking</text>'
          f'<text x="555" y="56" text-anchor="middle">filtered ranking</text></g>')
for col, (items, note_t) in enumerate([(ranked, "raw"), (filt_ranked, "filt")]):
    ox = 80 + col * 350
    k = 0
    for t in ranked:
        yy = 70 + k * 34
        is_true = t == TRUE_T
        is_known = t == KNOWN_TRUE[2]
        ghost = note_t == "filt" and is_known
        fill = ("var(--dkr-green, #199473)" if is_true else
                "#7c5cd6" if is_known else "var(--dkr-muted, #8e8e9a)")
        op = 0.16 if ghost else (0.9 if (is_true or is_known) else 0.45)
        rk = (filt_ranked.index(t) + 1) if (note_t == "filt" and not ghost) else (ranked.index(t) + 1)
        p_rank = "—" if ghost else str(rk)
        # the removed row must read "struck out", not "rendering bug": faint band,
        # but solid struck-through text in the competitor's own purple
        strike = ' text-decoration="line-through"' if ghost else ""
        tfill = "var(--dkr-purple, #7c5cd6)" if ghost else "#fff"
        ev.append(f'  <rect x="{ox}" y="{yy}" width="250" height="27" rx="8" fill="{fill}" opacity="{op}"/>')
        ev.append(f'  <text x="{ox + 12}" y="{yy + 18.5}" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{tfill}">{p_rank}</text>')
        ev.append(f'  <text x="{ox + 36}" y="{yy + 18.5}" font-family="{SANS}" font-size="12.5" fill="{tfill}"{strike}>{t}</text>')
        ev.append(f'  <text x="{ox + 242}" y="{yy + 18.5}" text-anchor="end" font-family="{MONO}" font-size="12" fill="{tfill}"{strike}>{scores[t]:+.1f}</text>')
        k += 1
ev.append(f'  <text x="205" y="262" text-anchor="middle" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">Russia outranks the answer — but (Volga, flows_through, Russia)</text>')
ev.append(f'  <text x="205" y="278" text-anchor="middle" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">is a TRAINING fact: the model is right, the metric was wrong</text>')
ev.append(f'  <text x="555" y="262" text-anchor="middle" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">known-true competitors removed before ranking:</text>')
ev.append(f'  <text x="555" y="278" text-anchor="middle" font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">rank {raw_rank} → {filt_rank} · reciprocal rank {1 / raw_rank:.2f} → {1 / filt_rank:.2f} · Hits@1: 0 → 1</text>')
ev.append(f'''  <g font-family="{SANS}">
    <rect x="70" y="298" width="620" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="318" text-anchor="middle" font-size="13.5" font-weight="700" fill="var(--dkr-bg, #fff)">compute MRR and Hits@K on the FILTERED ranking — never punish known truth</text>
  </g>''')
write("fig-w4-eval", "\n".join(ev),
      f"A worked filtered-ranking example: for the query Volga flows through what, the true answer Tatarstan ranks {raw_rank} raw because the known training fact about Russia outranks it, and rank {filt_rank} after filtering",
      height=340)
