#!/usr/bin/env python
"""Generate the four Week 5 figures:
  fig-w5-hero          — a 2-hop query over an incomplete biomedical KG; answer sets
                         computed by real traversal (and one answer no path reaches)
  fig-w5-boxes         — Query2box projection + intersection in 2D, containment verified
  fig-w5-graphrag      — vector RAG vs GraphRAG on one concrete question (schematic)
  fig-w5-construction  — LLM-assisted KG construction failure modes (schematic)
Run: python scripts/figgen/w5_figs.py
"""
from pathlib import Path

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"


def write(name, body, aria, height=400):
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 {height}\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/w5_figs.py -->\n{body}\n</svg>\n</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


# ════════════════════════ the shared biomedical toy KG ═════════════════════
DRUGS = ["Aspirin", "Ibuprofen", "Naproxen", "Metformin"]
PROTS = ["COX-1", "COX-2", "AMPK"]
DISEASES = ["Inflammation", "Diabetes"]
TARGETS = [("Aspirin", "COX-1"), ("Aspirin", "COX-2"), ("Ibuprofen", "COX-2"),
           ("Naproxen", "COX-1"), ("Metformin", "AMPK")]
ASSOC = [("COX-2", "Inflammation"), ("AMPK", "Diabetes")]
MISSING = ("Naproxen", "COX-2")          # true in the world, unstated in the KG
assert MISSING not in TARGETS

# the 2-hop query, actually executed on the stated graph
q_prots = {p for p, d in ASSOC if d == "Inflammation"}
q_drugs = {dr for dr, p in TARGETS if p in q_prots}
q_drugs_true = q_drugs | ({MISSING[0]} if MISSING[1] in q_prots else set())
assert q_prots == {"COX-2"} and q_drugs == {"Aspirin", "Ibuprofen"}
assert q_drugs_true == {"Aspirin", "Ibuprofen", "Naproxen"}

POS = {
    "Aspirin": (120, 78), "Ibuprofen": (120, 168), "Naproxen": (120, 258), "Metformin": (120, 340),
    "COX-1": (350, 100), "COX-2": (350, 205), "AMPK": (350, 328),
    "Inflammation": (585, 175), "Diabetes": (585, 328),
}


def pill(x, y, label, fill, tfill="#fff", stroke="none", w=None, dash=False):
    w = w or (8.2 * len(label) + 22)
    d = ' stroke-dasharray="5,4"' if dash else ""
    return (f'<rect x="{x - w / 2:.0f}" y="{y - 14}" width="{w:.0f}" height="28" rx="14" '
            f'fill="{fill}" stroke="{stroke}" stroke-width="1.6"{d}/>'
            f'<text x="{x}" y="{y + 4.5}" text-anchor="middle" font-family="{SANS}" '
            f'font-size="12.5" font-weight="700" fill="{tfill}">{label}</text>')


hero = ['  <defs><marker id="w5hA" markerWidth="8" markerHeight="8" refX="10" refY="3" orient="auto">'
        '<path d="M0,0 L7,3 L0,6 Z" fill="var(--dkr-muted, #8e8e9a)"/></marker></defs>']
hero.append(f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13.5" font-weight="700" '
            f'fill="var(--dkr-text, #1c1c21)">query: which drugs target a protein associated with Inflammation?</text>')
hero.append(f'  <text x="380" y="43" text-anchor="middle" font-family="{MONO}" font-size="12" '
            f'fill="var(--dkr-muted, #6e6e7a)">?drug ←targets— ?protein ←associated_with— Inflammation</text>')
# stagger the entry points of the three edges converging on COX-2's left rim
ENTRY_DY = {("Aspirin", "COX-2"): -11, ("Ibuprofen", "COX-2"): 0}
for (a, b), rel, color in [(e, "targets", "var(--dkr-blue, #0f8377)") for e in TARGETS] + \
                          [(e, "assoc", "#7c5cd6") for e in ASSOC]:
    (x1, y1), (x2, y2) = POS[a], POS[b]
    y2 += ENTRY_DY.get((a, b), 0)
    hero.append(f'  <line x1="{x1 + 45}" y1="{y1}" x2="{x2 - 52}" y2="{y2}" stroke="{color}" '
                f'stroke-width="1.8" opacity="0.6" marker-end="url(#w5hA)"/>')
(x1, y1), (x2, y2) = POS[MISSING[0]], POS[MISSING[1]]
hero.append(f'  <line x1="{x1 + 45}" y1="{y1}" x2="{x2 - 52}" y2="{y2 + 11}" stroke="var(--dkr-accent, #d9603b)" '
            f'stroke-width="2.4" stroke-dasharray="7,5" opacity="0.9" marker-end="url(#w5hA)"/>')
hero.append(f'  <text x="234" y="252" text-anchor="middle" font-family="{SANS}" '
            f'font-size="12.5" font-weight="600" fill="var(--dkr-accent, #b84a2b)" '
            f'stroke="var(--dkr-paper, #fff)" stroke-width="4" paint-order="stroke">true, but never stated</text>')
# claim the separation band above the Metformin row: faint divider + side label
hero.append(f'  <line x1="60" y1="298" x2="700" y2="298" stroke="var(--dkr-muted, #8e8e9a)" '
            f'stroke-width="1" stroke-dasharray="2,6" opacity="0.55"/>')
hero.append(f'  <text x="700" y="292" text-anchor="end" font-family="{SANS}" font-size="12.5" '
            f'font-style="italic" fill="var(--dkr-muted, #6e6e7a)">below: the counterexample — Metformin&#8217;s 2-hop path exits the query</text>')
for e, (x, y) in POS.items():
    if e in DRUGS:
        in_ans = e in q_drugs
        in_true = e in q_drugs_true
        fill = ("var(--dkr-green, #199473)" if in_ans else
                "var(--dkr-paper, #fff)" if not in_true else "var(--dkr-paper, #fff)")
        stroke = "var(--dkr-accent, #d9603b)" if (in_true and not in_ans) else \
                 ("none" if in_ans else "var(--dkr-muted, #8e8e9a)")
        tfill = "#fff" if in_ans else ("var(--dkr-accent, #b84a2b)" if (in_true and not in_ans)
                                       else "var(--dkr-muted, #6e6e7a)")
        hero.append("  " + pill(x, y, e, fill, tfill, stroke, dash=(in_true and not in_ans)))
    elif e in PROTS:
        hot = e in q_prots
        hero.append("  " + pill(x, y, e, "#7c5cd6" if hot else "var(--dkr-paper, #fff)",
                                "#fff" if hot else "var(--dkr-muted, #6e6e7a)",
                                "none" if hot else "var(--dkr-muted, #8e8e9a)"))
    else:
        hot = e == "Inflammation"
        hero.append("  " + pill(x, y, e, "var(--dkr-yellow, #d9a62e)" if hot else "var(--dkr-paper, #fff)",
                                "#5c4508" if hot else "var(--dkr-muted, #6e6e7a)",
                                "none" if hot else "var(--dkr-muted, #8e8e9a)"))
hero.append(f'  <g font-family="{SANS}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">'
            f'<text x="120" y="382" text-anchor="middle">drugs</text>'
            f'<text x="350" y="382" text-anchor="middle">proteins · targets (teal)</text>'
            f'<text x="585" y="382" text-anchor="middle">diseases · associated_with (purple)</text></g>')
hero.append(f'''  <g font-family="{SANS}">
    <rect x="55" y="398" width="650" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="418" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">traversal finds two drugs — the true answer set has three. Lookup cannot reach Naproxen.</text>
  </g>''')
write("fig-w5-hero", "\n".join(hero),
      "A two-hop query over a small drug-protein-disease knowledge graph: traversal finds Aspirin and Ibuprofen via COX-2, while Naproxen is a true answer reachable only through an unstated edge",
      height=440)


# ═════════════════════════════ Query2box in 2D ═════════════════════════════
# toy geometry, all containment claims verified below
ENT2D = {"Aspirin": (5.2, 5.6), "Ibuprofen": (6.1, 4.9), "Naproxen": (5.7, 6.4),
         "Metformin": (1.5, 1.6), "COX-2": (4.1, 3.1), "AMPK": (1.2, 3.0),
         "Inflammation": (2.6, 1.0)}
B1_C, B1_O = (3.9, 2.9), (0.9, 0.9)     # after assoc⁻¹ projection from Inflammation
B2_C, B2_O = (5.7, 5.6), (1.3, 1.4)     # after targets⁻¹ projection

def inside(p, c, o):
    return abs(p[0] - c[0]) <= o[0] and abs(p[1] - c[1]) <= o[1]

assert inside(ENT2D["COX-2"], B1_C, B1_O) and not inside(ENT2D["AMPK"], B1_C, B1_O)
for d in ["Aspirin", "Ibuprofen", "Naproxen"]:
    assert inside(ENT2D[d], B2_C, B2_O), d
assert not inside(ENT2D["Metformin"], B2_C, B2_O)

# non-uniform scale: x stretched so the diagonal chain fills the canvas evenly
SX, SY = 80, 50
def bx(v): return 52 + v * SX
def by(v): return 410 - v * SY

boxes = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" '
         f'fill="var(--dkr-muted, #6e6e7a)">the same query, embedded: each step is a geometric operator; the answer set is “everything inside”</text>']
# how-to-read note claims the top-left corner
boxes.append(f'  <g font-family="{SANS}" font-size="12.5" fill="var(--dkr-muted, #6e6e7a)">'
             f'<text x="60" y="66">each dot: an entity&#8217;s embedding</text>'
             f'<text x="60" y="86">each box: a query region — answers are inside</text></g>')
for (c, o, color) in [(B1_C, B1_O, "#7c5cd6"),
                      (B2_C, B2_O, "var(--dkr-green, #199473)")]:
    x0, y0 = bx(c[0] - o[0]), by(c[1] + o[1])
    w, h = 2 * o[0] * SX, 2 * o[1] * SY
    boxes.append(f'  <rect x="{x0:.0f}" y="{y0:.0f}" width="{w:.0f}" height="{h:.0f}" rx="8" '
                 f'fill="{color}" opacity="0.12"/>')
    boxes.append(f'  <rect x="{x0:.0f}" y="{y0:.0f}" width="{w:.0f}" height="{h:.0f}" rx="8" '
                 f'fill="none" stroke="{color}" stroke-width="2.2"/>')
# step ①: label in the right-hand void, leader line to the purple box's edge
boxes.append(f'  <text x="452" y="270" text-anchor="start" font-family="{SANS}" '
             f'font-size="12.5" font-weight="700" fill="#7c5cd6">① project: assoc⁻¹(Inflammation)</text>')
boxes.append(f'  <line x1="448" y1="266" x2="438" y2="262" stroke="#7c5cd6" stroke-width="1.4" opacity="0.7"/>')
# step ②: label just left of the box→box arrow it describes
boxes.append(f'  <text x="412" y="212" text-anchor="end" font-family="{SANS}" '
             f'font-size="12.5" font-weight="700" fill="var(--dkr-green, #199473)">② project again: targets⁻¹(box)</text>')
boxes.append(f'  <path d="M{bx(2.6):.0f},{by(1.0) - 14:.0f} L{bx(3.55):.0f},{by(2.05):.0f}" stroke="#7c5cd6" '
             f'stroke-width="2" fill="none" marker-end="url(#w5bA)"/>')
boxes.append(f'  <path d="M{bx(4.6):.0f},{by(3.6):.0f} L{bx(5.3):.0f},{by(4.6):.0f}" stroke="var(--dkr-green, #199473)" '
             f'stroke-width="2" fill="none" marker-end="url(#w5bA)"/>')
boxes.append('  <defs><marker id="w5bA" markerWidth="9" markerHeight="9" refX="7" refY="3.5" orient="auto">'
             '<path d="M0,0 L8,3.5 L0,7 Z" fill="var(--dkr-muted, #8e8e9a)"/></marker></defs>')
for e, p in ENT2D.items():
    x, y = bx(p[0]), by(p[1])
    is_ans = e in ("Aspirin", "Ibuprofen", "Naproxen")
    is_anchor = e == "Inflammation"
    is_mid = e == "COX-2"
    fill = ("var(--dkr-green, #199473)" if is_ans else "var(--dkr-yellow, #d9a62e)" if is_anchor
            else "#7c5cd6" if is_mid else "var(--dkr-muted, #8e8e9a)")
    boxes.append(f'  <circle cx="{x:.0f}" cy="{y:.0f}" r="{8 if (is_ans or is_anchor or is_mid) else 6}" '
                 f'fill="{fill}" opacity="{0.95 if (is_ans or is_anchor or is_mid) else 0.5}"/>')
    if e == "Inflammation":   # label to the right: keeps it clear of Metformin's
        boxes.append(f'  <text x="{x + 14:.0f}" y="{y + 4:.0f}" text-anchor="start" font-family="{SANS}" '
                     f'font-size="12" font-weight="600" fill="var(--dkr-text, #1c1c21)">{e} (anchor: a point)</text>')
        continue
    dy = -13 if e not in ("COX-2", "Metformin") else 24
    boxes.append(f'  <text x="{x:.0f}" y="{y + dy:.0f}" text-anchor="middle" font-family="{SANS}" '
                 f'font-size="12" font-weight="600" fill="var(--dkr-text, #1c1c21)">{e}</text>')
boxes.append(f'''  <g font-family="{SANS}">
    <rect x="45" y="396" width="670" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="416" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">all three true drugs fall inside — never-stated Naproxen included. Regions generalize.</text>
  </g>''')
write("fig-w5-boxes", "\n".join(boxes),
      "The two-hop query embedded as Query2box operations in two dimensions: the anchor projects to a purple box containing COX-2, a second projection yields a green box containing all three true drugs including unstated Naproxen",
      height=440)


# ═════════════════════════════ GraphRAG schematic ══════════════════════════
gr = [f'  <text x="380" y="22" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">one question, two retrieval strategies (schematic)</text>']
gr.append(f'  <text x="380" y="44" text-anchor="middle" font-family="{SANS}" font-size="13.5" font-weight="700" '
          f'fill="var(--dkr-text, #1c1c21)">“Which region is Innopolis University in?” — the answer needs TWO facts from different documents</text>')

def panel(ox, title, color, steps, verdict, good):
    p = [f'  <g font-family="{SANS}">'
         f'<text x="{ox + 175}" y="76" text-anchor="middle" font-size="14.5" font-weight="700" fill="{color}">{title}</text>']
    y = 96
    for si, (txt, sub) in enumerate(steps):
        p.append(f'<rect x="{ox + 15}" y="{y}" width="320" height="44" rx="10" fill="{color}" opacity="0.1"/>')
        p.append(f'<rect x="{ox + 15}" y="{y}" width="320" height="44" rx="10" fill="none" stroke="{color}" stroke-width="1.6"/>')
        p.append(f'<text x="{ox + 175}" y="{y + 19}" text-anchor="middle" font-size="12.5" font-weight="600" fill="var(--dkr-text, #1c1c21)">{txt}</text>')
        p.append(f'<text x="{ox + 175}" y="{y + 36}" text-anchor="middle" font-size="11.8" fill="var(--dkr-muted, #6e6e7a)">{sub}</text>')
        y += 58
        p.append(f'<text x="{ox + 175}" y="{y - 3}" text-anchor="middle" font-size="12.5" '
                 f'font-weight="700" fill="{color}" opacity="0.85">↓</text>')
    vcol = "var(--dkr-green, #199473)" if good else "#cf4a30"
    p.append(f'<rect x="{ox + 15}" y="{y + 2}" width="320" height="30" rx="15" fill="{vcol}"/>')
    p.append(f'<text x="{ox + 175}" y="{y + 22}" text-anchor="middle" font-size="12.5" font-weight="700" fill="#fff">{verdict}</text>')
    p.append("</g>")
    return "\n  ".join(p)

gr.append(panel(20, "vector RAG", "var(--dkr-muted, #8e8e9a)", [
    ("embed the question", "one vector for the whole ask"),
    ("top-k similar chunks", "doc about IU ✓ · doc about Kazan ✗ (similar words!)"),
    ("LLM reads the chunks", "“Innopolis” found — Tatarstan never retrieved"),
], "answer: “Innopolis” — one hop short", False))
gr.append(panel(400, "GraphRAG", "var(--dkr-blue, #0f8377)", [
    ("link entities in the question", "“Innopolis University” → a node in the KG"),
    ("retrieve the neighborhood subgraph", "IU →located_in→ Innopolis →located_in→ Tatarstan"),
    ("LLM reads facts, with provenance", "each triple cites its source document"),
], "answer: “Tatarstan” — the path was the point", True))
gr.append(f'''  <g font-family="{SANS}">
    <rect x="55" y="322" width="650" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="342" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">similarity retrieves what LOOKS like the question; structure retrieves what CONNECTS to it</text>
  </g>''')
write("fig-w5-graphrag", "\n".join(gr),
      "Schematic comparison of vector RAG and GraphRAG on a two-hop question: chunk similarity retrieves lookalike documents and misses the second hop, while entity-linked subgraph retrieval walks the path to the answer",
      height=366)


# ═══════════════════════ LLM-assisted construction ═════════════════════════
con = [f'  <text x="380" y="22" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">LLMs writing knowledge graphs: the pipeline, annotated with its three classic failures (schematic)</text>']
con.append(f'''  <g font-family="{MONO}" font-size="12">
    <rect x="30" y="44" width="700" height="58" rx="10" fill="var(--dkr-muted, #8e8e9a)" opacity="0.10"/>
    <text x="45" y="66" fill="var(--dkr-text, #1c1c21)">“Innopolis University sits in the young city of Innopolis. The university, IU for</text>
    <text x="45" y="86" fill="var(--dkr-text, #1c1c21)">short, was founded in 2012 in the Republic of Tatarstan, on the Volga.”</text>
  </g>''')
rows = [
    ("(Innopolis University, located_in, Innopolis)", "ok", "var(--dkr-green, #199473)", "clean extraction"),
    ("(IU, located_in, Republic of Tatarstan)", "dup", "#cf4a30", "failure 1 — canonicalization: “IU” and two spellings of Tatarstan become NEW entities"),
    ("(Innopolis University, founded_in, 2012)", "ok", "var(--dkr-green, #199473)", "clean — if the schema has founded_in: org → year"),
    ("(Volga, located_in, Innopolis)", "hall", "#cf4a30", "failure 2 — precision: fluent, confident, and false (nothing in the text says this)"),
    ("(IU, founded_in, Tatarstan)", "type", "#cf4a30", "failure 3 — schema: founded_in expects a year; type-checking catches what eyeballs miss"),
]
y = 130
for triple, kind, color, note in rows:
    good = kind == "ok"
    con.append(f'  <rect x="30" y="{y - 17}" width="700" height="41" rx="8" fill="{color}" opacity="0.07"/>')
    con.append(f'  <rect x="30" y="{y - 17}" width="5" height="41" fill="{color}"/>')
    con.append(f'  <rect x="46" y="{y - 13}" width="26" height="22" rx="11" fill="{color}"/>')
    con.append(f'  <text x="59" y="{y + 3}" text-anchor="middle" font-family="{SANS}" font-size="12.5" '
               f'font-weight="700" fill="#fff">{"✓" if good else "✗"}</text>')
    con.append(f'  <text x="84" y="{y}" font-family="{MONO}" font-size="12" fill="{color}">{triple}</text>')
    con.append(f'  <text x="84" y="{y + 18}" font-family="{SANS}" font-size="11.8" fill="var(--dkr-muted, #6e6e7a)">{note}</text>')
    y += 47
con.append(f'''  <g font-family="{SANS}">
    <rect x="55" y="{y + 2}" width="650" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="{y + 22}" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">extraction is cheap; canonicalization, verification, and provenance are the actual engineering</text>
  </g>''')
write("fig-w5-construction", "\n".join(con),
      "An LLM extracts five triples from two sentences: two are clean, one duplicates entities under new names, one is a fluent hallucination, and one violates the schema's type signature",
      height=y + 50)
