#!/usr/bin/env python
"""Generate the four Week 7 figures:
  fig-w7-mpnn          — the message/aggregate/update anatomy + four instantiations
  fig-w7-aggregators   — which multisets mean/max/sum confuse (all values computed)
  fig-w7-oversmoothing — real propagation experiment on the karate club: cosine
                         similarity vs depth for plain / residual / restart rules
  fig-w7-design        — the design-space map (schematic, labeled; findings from
                         You, Ying & Leskovec 2020)
Run: python scripts/figgen/w7_figs.py
"""
import random
from pathlib import Path

import numpy as np

from karate_common import EDGES as K_EDGES, N as K_N

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"


def write(name, body, aria, height=400):
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 {height}\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/w7_figs.py -->\n{body}\n</svg>\n</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


# ═══════════════════════════ the MPNN anatomy ══════════════════════════════
mp = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">one template, three slots — every architecture this week is a way of filling them</text>']
mp.append(f'''  <g font-family="{MONO}" font-size="15" text-anchor="middle">
    <text x="380" y="58" fill="var(--dkr-text, #1c1c21)">h&#x2032;(v) = <tspan fill="#7c5cd6" font-weight="700">UPDATE</tspan>( h(v), <tspan fill="var(--dkr-green, #199473)" font-weight="700">AGG</tspan>{{ <tspan fill="var(--dkr-accent, #d9603b)" font-weight="700">MSG</tspan>(h(u)) : u &#x2208; N(v) }} )</text>
  </g>''')
slots = [
    (60, "MSG", "var(--dkr-accent, #d9603b)", "what each neighbor sends", "a linear map of neighbor features"),
    (310, "AGG", "var(--dkr-green, #199473)", "how the multiset is squashed", "mean · max · sum · attention"),
    (560, "UPDATE", "#7c5cd6", "how self meets neighborhood", "add · concat + linear · MLP · gated"),
]
for x, name, color, sub, opts in slots:
    mp.append(f'''  <g font-family="{SANS}">
    <rect x="{x}" y="82" width="200" height="74" rx="12" fill="{color}" opacity="0.12"/>
    <rect x="{x}" y="82" width="200" height="74" rx="12" fill="none" stroke="{color}" stroke-width="2"/>
    <text x="{x + 100}" y="104" text-anchor="middle" font-size="14" font-weight="700" fill="{color}">{name}</text>
    <text x="{x + 100}" y="124" text-anchor="middle" font-size="12" fill="var(--dkr-text, #1c1c21)">{sub}</text>
    <text x="{x + 100}" y="143" text-anchor="middle" font-size="12" fill="var(--dkr-muted, #6e6e7a)">{opts}</text>
  </g>''')
rows = [
    ("GCN (Wk 6)", "W·h(u) / √(d̂u d̂v)", "sum (pre-normalized)", "no self-term; self-loop in Â", "var(--dkr-muted, #8e8e9a)"),
    ("GraphSAGE", "h(u), sampled subset", "mean · max-pool · LSTM", "CONCAT(self, agg) → linear", "var(--dkr-blue, #0f8377)"),
    ("GAT", "W·h(u)", "softmax-attention mean", "weighted sum incl. self-attention", "var(--dkr-accent, #d9603b)"),
    ("GIN", "h(u), untouched", "sum — keep the multiset", "MLP((1+ε)·self + sum)", "var(--dkr-green, #199473)"),
]
y0 = 186
mp.append(f'  <g font-family="{SANS}" font-size="12.5" font-weight="700" fill="var(--dkr-muted, #6e6e7a)">'
          f'<text x="30" y="{y0}">model</text><text x="200" y="{y0}">message</text>'
          f'<text x="400" y="{y0}">aggregate</text><text x="562" y="{y0}">update</text></g>')
for i, (mname, msg, agg, upd, color) in enumerate(rows):
    yy = y0 + 26 + i * 34
    if i % 2 == 0:
        mp.append(f'  <rect x="20" y="{yy - 17}" width="720" height="32" fill="var(--dkr-muted, #8e8e9a)" opacity="0.07"/>')
    mp.append(f'  <text x="30" y="{yy}" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{color}">{mname}</text>')
    for x, txt in ((200, msg), (400, agg), (562, upd)):
        mp.append(f'  <text x="{x}" y="{yy}" font-family="{SANS}" font-size="12" fill="var(--dkr-text, #1c1c21)">{txt}</text>')
mp.append(f'''  <g font-family="{SANS}">
    <rect x="80" y="{y0 + 26 + 4 * 34 + 6}" width="600" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="{y0 + 26 + 4 * 34 + 26}" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">"specify MSG, AGG, UPDATE" recovers each model — and is a standing exam question</text>
  </g>''')
write("fig-w7-mpnn", "\n".join(mp),
      "The message passing template with its three slots — message, aggregate, update — and a table showing how GCN, GraphSAGE, GAT, and GIN each fill them",
      height=y0 + 26 + 4 * 34 + 50)


# ═══════════════════ aggregator confusion, computed ════════════════════════
# one-hot features: teal t=(1,0), gold g=(0,1) — the GIN paper's three cases
T, G = np.array([1.0, 0.0]), np.array([0.0, 1.0])
CASES = [
    ("{t} vs {t, t}", [T], [T, T]),
    ("{t, g} vs {t, t, g, g}", [T, G], [T, T, G, G]),
    ("{t, t, g} vs {t, g, g}", [T, T, G], [T, G, G]),
]

def aggs(ms):
    a = np.stack(ms)
    return a.mean(0), a.max(0), a.sum(0)

def vec(v):
    return f"({v[0]:.2g}, {v[1]:.2g})"

agf = [f'  <text x="380" y="22" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">two neighborhoods per case (teal/gold = one-hot features) — every number computed; ✗ = the aggregator cannot tell them apart</text>']
verdicts = []
for ci, (label, A, B) in enumerate(CASES):
    ox = 20 + ci * 245
    mA, xA, sA = aggs(A)
    mB, xB, sB = aggs(B)
    vm, vx, vs = np.allclose(mA, mB), np.allclose(xA, xB), np.allclose(sA, sB)
    verdicts.append((vm, vx, vs))
    # draw the two multisets as dots
    agf.append(f'  <text x="{ox + 110}" y="52" text-anchor="middle" font-family="{MONO}" font-size="12.5" font-weight="700" fill="var(--dkr-text, #1c1c21)">{label}</text>')
    for row, ms in ((0, A), (1, B)):
        yy = 76 + row * 34
        x0 = ox + 110 - 13 * len(ms)
        for i, f in enumerate(ms):
            col = "var(--dkr-blue, #0f8377)" if f[0] == 1 else "var(--dkr-yellow, #d9a62e)"
            agf.append(f'  <circle cx="{x0 + 26 * i + 10}" cy="{yy}" r="9" fill="{col}"/>')
    for k, (name, a, b, same) in enumerate([("mean", mA, mB, vm), ("max", xA, xB, vx), ("sum", sA, sB, vs)]):
        yy = 152 + k * 46
        mark = "✗" if same else "✓"
        mcol = "#cf4a30" if same else "var(--dkr-green, #199473)"
        agf.append(f'  <text x="{ox + 26}" y="{yy}" font-family="{SANS}" font-size="12.5" font-weight="700" fill="{mcol}">{mark} {name}</text>')
        agf.append(f'  <text x="{ox + 110}" y="{yy + 17}" text-anchor="middle" font-family="{MONO}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">{vec(a)} vs {vec(b)}</text>')

assert verdicts[0] == (True, True, False), "case 1: only sum distinguishes"
assert verdicts[1] == (True, True, False), "case 2: only sum distinguishes"
assert verdicts[2] == (False, True, False), "case 3: only mean distinguishes"

agf.append(f'''  <g font-family="{SANS}">
    <rect x="40" y="300" width="680" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="320" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">sum keeps counts · mean keeps proportions · max keeps presence — no single aggregator dominates</text>
  </g>''')
write("fig-w7-aggregators", "\n".join(agf),
      "Three pairs of neighbor multisets with computed mean, max, and sum: the first two pairs are confused by mean and max but separated by sum, the third is confused only by max and separated by both mean and sum",
      height=344)


# ═══════════════ oversmoothing: a real propagation experiment ══════════════
adj = np.zeros((K_N, K_N))
for a, b in K_EDGES:
    adj[a, b] = adj[b, a] = 1.0
A_hat = adj + np.eye(K_N)                        # self-loops
d = A_hat.sum(1)
P = A_hat / d[:, None]                           # row-normalized propagation

rng = np.random.default_rng(3)
X0 = rng.standard_normal((K_N, 16))

def mean_cos(X):
    Xn = X / (np.linalg.norm(X, axis=1, keepdims=True) + 1e-12)
    S = Xn @ Xn.T
    return (S.sum() - K_N) / (K_N * (K_N - 1))

K_MAX = 12
curves = {"plain": [], "residual": [], "restart": []}
Xp, Xr, Xs = X0.copy(), X0.copy(), X0.copy()
for k in range(K_MAX + 1):
    curves["plain"].append(mean_cos(Xp))
    curves["residual"].append(mean_cos(Xr))
    curves["restart"].append(mean_cos(Xs))
    Xp = P @ Xp
    Xr = 0.5 * Xr + 0.5 * (P @ Xr)
    Xs = 0.1 * X0 + 0.9 * (P @ Xs)

assert curves["plain"][-1] > 0.95, f"plain propagation must oversmooth, got {curves['plain'][-1]:.3f}"
assert curves["restart"][-1] < 0.9, f"restart must resist, got {curves['restart'][-1]:.3f}"
assert curves["residual"][-1] > curves["restart"][-1], "residual delays but does not stop"
print("oversmoothing endpoints:", {k: round(v[-1], 3) for k, v in curves.items()})

PX0, PY0, PW, PH_ = 90, 60, 560, 240
def px(k): return PX0 + k / K_MAX * PW
def py(v): return PY0 + (1 - v) * PH_

ov = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">the karate club, 16-dim random features, propagated k times — mean pairwise cosine similarity, computed exactly</text>']
ov.append(f'  <line x1="{PX0}" y1="{py(0)}" x2="{PX0}" y2="{py(1)}" stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1.4"/>')
ov.append(f'  <line x1="{PX0}" y1="{py(0)}" x2="{px(K_MAX)}" y2="{py(0)}" stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1.4"/>')
for v in (0, 0.5, 1.0):
    ov.append(f'  <text x="{PX0 - 10}" y="{py(v) + 4}" text-anchor="end" font-family="{MONO}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">{v:g}</text>')
    if v > 0:
        ov.append(f'  <line x1="{PX0}" y1="{py(v)}" x2="{px(K_MAX)}" y2="{py(v)}" stroke="var(--dkr-border, #e8e7e3)" stroke-width="1"/>')
for k in range(0, K_MAX + 1, 2):
    ov.append(f'  <text x="{px(k)}" y="{py(0) + 20}" text-anchor="middle" font-family="{MONO}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">{k}</text>')
ov.append(f'  <text x="{px(K_MAX / 2)}" y="{py(0) + 42}" text-anchor="middle" font-family="{SANS}" font-size="12.5" fill="var(--dkr-text, #1c1c21)">propagation steps k (≈ network depth)</text>')

styles = {"plain": ("var(--dkr-accent, #d9603b)", "plain:  x ← Âx"),
          "residual": ("#7c5cd6", "residual:  x ← ½x + ½Âx"),
          "restart": ("var(--dkr-green, #199473)", "restart:  x ← 0.1·x₀ + 0.9·Âx")}
for name, vals in curves.items():
    color, _ = styles[name]
    pts = " ".join(f"{px(k):.1f},{py(v):.1f}" for k, v in enumerate(vals))
    ov.append(f'  <polyline points="{pts}" fill="none" stroke="{color}" stroke-width="2.6"/>')
    for k in range(0, K_MAX + 1, 2):
        ov.append(f'  <circle cx="{px(k):.1f}" cy="{py(vals[k]):.1f}" r="3.5" fill="{color}"/>')
leg_y = 78
for i, (name, (color, label)) in enumerate(styles.items()):
    ov.append(f'  <line x1="{PX0 + 20}" y1="{leg_y + i * 22}" x2="{PX0 + 48}" y2="{leg_y + i * 22}" stroke="{color}" stroke-width="3"/>')
    ov.append(f'  <text x="{PX0 + 56}" y="{leg_y + i * 22 + 4}" font-family="{MONO}" font-size="12" fill="var(--dkr-text, #1c1c21)">{label}</text>')
ov.append(f'''  <g font-family="{SANS}">
    <rect x="75" y="368" width="610" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="388" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">by k = 12: plain {curves['plain'][-1]:.2f} (everyone identical) · residual {curves['residual'][-1]:.2f} (delayed) · restart {curves['restart'][-1]:.2f} (held)</text>
  </g>''')
write("fig-w7-oversmoothing", "\n".join(ov),
      f"Mean pairwise cosine similarity of node features on the karate club as propagation depth grows: plain propagation reaches {curves['plain'][-1]:.2f} by twelve steps while a residual rule delays collapse and a restart rule holds similarity at {curves['restart'][-1]:.2f}",
      height=412)


# ═══════════════════════════ the design-space map ══════════════════════════
ds = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" fill="var(--dkr-muted, #6e6e7a)">the knobs of a message-passing architecture (schematic; verdicts from the 315,000-configuration study)</text>']
dims = [
    ("layer type", "GCN · SAGE · GAT · GIN", "task-dependent — no universal winner"),
    ("depth", "2 · 4 · 6 · 8+", "task-dependent; deep needs skips"),
    ("aggregation", "mean · max · sum", "sum consistently strong, esp. graph-level"),
    ("skip pattern", "none · residual · concat · jumping knowledge", "consistently helpful — safest upgrade"),
    ("normalization", "none · Batch · Layer · Pair", "BN consistently helpful in the study"),
    ("regularization", "dropout · DropEdge · weight decay", "task-dependent; DropEdge aids depth"),
]
for i, (dim, opts, verdict) in enumerate(dims):
    yy = 56 + i * 52
    good = "consistently" in verdict
    vc = "var(--dkr-green, #199473)" if good else "var(--dkr-yellow, #d9a62e)"
    ds.append(f'''  <g font-family="{SANS}">
    <rect x="25" y="{yy - 16}" width="150" height="40" rx="10" fill="var(--dkr-blue, #0f8377)" opacity="0.12"/>
    <text x="100" y="{yy + 8}" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-blue, #0f8377)">{dim}</text>
    <text x="192" y="{yy + 8}" font-family="{MONO}" font-size="12" fill="var(--dkr-text, #1c1c21)">{opts}</text>
    <circle cx="492" cy="{yy + 3}" r="5" fill="{vc}"/>
    <text x="506" y="{yy + 8}" font-size="12" fill="var(--dkr-muted, #6e6e7a)">{verdict}</text>
  </g>''')
ds.append(f'''  <g font-family="{SANS}">
    <rect x="45" y="{56 + 6 * 52}" width="670" height="30" rx="15" fill="var(--dkr-green, #199473)"/>
    <text x="380" y="{56 + 6 * 52 + 20}" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">≈ 10⁵ combinations — which is why the week ends with a method, not another model</text>
  </g>''')
write("fig-w7-design", "\n".join(ds),
      "Six design dimensions of message-passing networks with their options and the 2020 design-space study's verdict on each: skip connections and batch normalization help consistently, most other choices are task-dependent",
      height=56 + 6 * 52 + 44)
