#!/usr/bin/env python
"""Generate the four Week 9 figures and VERIFY every expressiveness claim the
lecture makes (asserts fail loudly if a claim is wrong):
  fig-w9-trees     — computation trees of a triangle node vs a hexagon node,
                     unrolled to depth 3: identical, hence the blindness
  fig-w9-molecules — decalin vs bicyclopentyl with computed WL colors:
                     different molecules, identical color histograms
  fig-w9-ladder    — the expressiveness ladder: what separates each level
  fig-w9-squash    — computed sensitivity (Â^K) on a barbell: the bridge
                     crushes influence by orders of magnitude; one added
                     edge rescues it
Run: python scripts/figgen/w9_figs.py
"""
import math
from collections import Counter
from pathlib import Path

import networkx as nx
import numpy as np

FIGDIR = Path(__file__).resolve().parents[2] / "assets" / "figures"
SANS = "'Source Sans 3', sans-serif"
MONO = "'JetBrains Mono', monospace"


def write(name, body, aria, height=400):
    (FIGDIR / f"{name}.html").write_text(
        f"```{{=html}}\n<figure class=\"dkr-fig\">\n<svg viewBox=\"0 0 760 {height}\" role=\"img\" aria-label=\"{aria}\">\n"
        f"  <!-- generated by scripts/figgen/w9_figs.py -->\n{body}\n</svg>\n</figure>\n```\n",
        encoding="utf-8")
    print("wrote", name)


def wl_colors(G, rounds=None, init=None):
    """Run WL to stability (or a fixed number of rounds); return final colors
    canonicalized to small ints, and the per-round histograms."""
    colors = {v: (0 if init is None else init[v]) for v in G}
    hists = []
    r = 0
    while True:
        new = {v: (colors[v], tuple(sorted(colors[u] for u in G[v]))) for v in G}
        canon = {sig: i for i, sig in enumerate(sorted(set(new.values())))}
        new = {v: canon[new[v]] for v in G}
        hists.append(sorted(Counter(new.values()).values()))
        r += 1
        if new == colors or (rounds and r >= rounds):
            colors = new
            break
        colors = new
    return colors, hists


# ═══════════════ claim 1: triangles∪triangles vs hexagon (recap) ═══════════
G_tri = nx.disjoint_union(nx.cycle_graph(3), nx.cycle_graph(3))
G_hex = nx.cycle_graph(6)
_, h1 = wl_colors(G_tri, rounds=4)
_, h2 = wl_colors(G_hex, rounds=4)
assert h1 == h2, "blind pair: identical histograms forever"

# ═══════════════ claim 2: decalin vs bicyclopentyl are WL-blind ════════════
# decalin: two hexagons sharing an edge (10 C atoms); bicyclopentyl: two
# pentagons joined by a single bond. Same degree sequence (two 3s, eight 2s).
DECALIN = nx.Graph([(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 0),   # hexagon
                    (0, 6), (6, 7), (7, 8), (8, 9), (9, 1)])          # fused ring via edge 0-1
BICYCLO = nx.Graph([(0, 1), (1, 2), (2, 3), (3, 4), (4, 0),           # pentagon A
                    (5, 6), (6, 7), (7, 8), (8, 9), (9, 5),           # pentagon B
                    (0, 5)])                                          # the bond
assert sorted(d for _, d in DECALIN.degree()) == sorted(d for _, d in BICYCLO.degree()) == [2] * 8 + [3, 3]
assert DECALIN.number_of_edges() == BICYCLO.number_of_edges() == 11
cd, hd = wl_colors(DECALIN)
cb, hb = wl_colors(BICYCLO)
assert hd[-1] == hb[-1], f"decalin vs bicyclopentyl final histograms must match: {hd[-1]} vs {hb[-1]}"
assert not nx.is_isomorphic(DECALIN, BICYCLO), "and yet the molecules differ"
n_classes = len(set(cd.values()))
assert set(cd.values()) == set(cb.values()) or len(set(cb.values())) == n_classes
print(f"molecules verified: same histograms {hd[-1]}, non-isomorphic, {n_classes} color classes")

# ═══════════════ claim 3: CSL(11,2) vs CSL(11,3) ═══════════════════════════
def csl(n, s):
    g = nx.Graph()
    for v in range(n):
        g.add_edge(v, (v + 1) % n)
        g.add_edge(v, (v + s) % n)
    return g


C2, C3s = csl(11, 2), csl(11, 3)
assert all(d == 4 for _, d in C2.degree()) and all(d == 4 for _, d in C3s.degree())
_, hc2 = wl_colors(C2)
_, hc3 = wl_colors(C3s)
assert hc2[-1] == hc3[-1] == [11], "vertex-transitive: WL never splits either graph"
assert not nx.is_isomorphic(C2, C3s), "CSL(11,2) and CSL(11,3) are non-isomorphic"

# RW return probabilities separate them (and are constant within each graph)
def rw_returns(G, kmax=6):
    A = nx.to_numpy_array(G)
    M = A / A.sum(1, keepdims=True)
    out = []
    P = np.eye(len(A))
    for _ in range(kmax):
        P = P @ M
        out.append(np.diag(P).copy())
    return np.array(out)   # (kmax, n)


r2, r3 = rw_returns(C2), rw_returns(C3s)
assert np.allclose(r2, r2[:, :1], atol=1e-12) and np.allclose(r3, r3[:, :1], atol=1e-12), \
    "vertex-transitivity: return probs constant within each graph"
gap = np.abs(r2[:, 0] - r3[:, 0]).max()
assert gap > 0.01, f"return-probability signatures must differ between the graphs (gap {gap})"
k_best = int(np.argmax(np.abs(r2[:, 0] - r3[:, 0])))
print(f"CSL verified: both 4-regular, WL-blind, non-isomorphic; RWPE gap {gap:.4f} (max at k={k_best + 1})"
      f" — CSL(11,2) k4 return {r2[3, 0]:.4f} vs CSL(11,3) {r3[3, 0]:.4f}")

# ═══════════════ claim 4: barbell sensitivity + one-edge rescue ════════════
def ahat(G):
    A = nx.to_numpy_array(G, weight=None)
    At = A + np.eye(len(A))
    d = At.sum(1)
    Dm = np.diag(d ** -0.5)
    return Dm @ At @ Dm


BAR = nx.barbell_graph(5, 2)          # K5 — path of 2 — K5, nodes 0..11
SRC, FAR = 0, 11                      # source in left clique, target deep right (distance 5)
K = 5                                 # just deep enough to REACH the far clique — squashed, not merely absent
S = np.linalg.matrix_power(ahat(BAR), K)
sens_near = S[SRC, 4]                 # node 4 = left clique's bridgehead
sens_far = S[SRC, FAR]
ratio = sens_near / sens_far
assert 0 < sens_far < 1e-2 and ratio > 50, f"bridge crush: near {sens_near:.4f}, far {sens_far:.6f}, ratio {ratio:.0f}"

BAR2 = BAR.copy()
BAR2.add_edge(1, 10)                  # ONE rewiring edge across
S2 = np.linalg.matrix_power(ahat(BAR2), K)
rescue = S2[SRC, FAR] / sens_far
assert rescue > 20, f"one added edge must lift far sensitivity by >20x (got {rescue:.0f}x)"
print(f"barbell verified (K={K}): near {sens_near:.4f}, across-bridge {sens_far:.2e} "
      f"(ratio {ratio:.0f}x); one rewiring edge lifts it {rescue:.0f}x to {S2[SRC, FAR]:.2e}")


# ═══════════════ figure 1: computation trees ═══════════════════════════════
def draw_tree(cx, top, depth, spread, r=9):
    """Full binary computation tree (every node has 2 neighbors) to `depth`."""
    parts, pos = [], {(): (cx, top)}
    for d in range(1, depth + 1):
        step = spread / (2 ** d)
        for key in [k for k in pos if len(k) == d - 1]:
            x0, y0 = pos[key]
            for i, dx in enumerate((-step, step)):
                child = key + (i,)
                pos[child] = (x0 + dx, y0 + 56)
                parts.append(f'  <line x1="{x0:.1f}" y1="{y0}" x2="{pos[child][0]:.1f}" '
                             f'y2="{pos[child][1]}" stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1.4"/>')
    for key, (x, y) in pos.items():
        col = "var(--dkr-accent, #d9603b)" if key == () else "var(--dkr-blue, #0f8377)"
        parts.append(f'  <circle cx="{x:.1f}" cy="{y}" r="{r if key == () else (7 if len(key) < 3 else 5.5)}" fill="{col}"/>')
    return parts


tr = [f'  <text x="380" y="26" text-anchor="middle" font-family="{SANS}" font-size="13" '
      f'fill="var(--dkr-muted, #6e6e7a)">what one message-passing node actually sees: its neighborhood, unrolled — every node here has degree 2</text>']
tr += draw_tree(200, 66, 3, 185)
tr += draw_tree(553, 66, 3, 185)
tr.append(f'  <text x="200" y="292" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" '
          f'fill="var(--dkr-text, #1c1c21)">a triangle node&#x2019;s tree (depth 3)</text>')
tr.append(f'  <text x="553" y="292" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" '
          f'fill="var(--dkr-text, #1c1c21)">a hexagon node&#x2019;s tree (depth 3)</text>')
tr.append(f'''  <g font-family="{SANS}">
    <rect x="120" y="312" width="520" height="30" rx="15" fill="var(--dkr-accent, #d9603b)"/>
    <text x="380" y="332" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">identical trees at every depth — no weights can tell these nodes apart</text>
  </g>''')
write("fig-w9-trees", "\n".join(tr),
      "Two identical full binary computation trees side by side: a triangle node's unrolled neighborhood and a hexagon node's, both to depth 3 — message passing sees the same tree for both",
      height=360)

# ═══════════════ figure 2: the molecules, WL-colored ═══════════════════════
# palette per WL class (computed above; expect 2 classes: degree-3 and degree-2)
CLASS_COLOR = ["var(--dkr-blue, #0f8377)", "var(--dkr-yellow, #d9a62e)",
               "var(--dkr-green, #199473)", "#7c5cd6"]


def hexagon_pts(cx, cy, R, rot=0.0):
    return [(cx + R * math.cos(rot + k * math.pi / 3), cy + R * math.sin(rot + k * math.pi / 3))
            for k in range(6)]


def pentagon_pts(cx, cy, R, rot=0.0):
    return [(cx + R * math.cos(rot + k * 2 * math.pi / 5), cy + R * math.sin(rot + k * 2 * math.pi / 5))
            for k in range(5)]


mol = [f'  <text x="380" y="26" text-anchor="middle" font-family="{SANS}" font-size="13" '
       f'fill="var(--dkr-muted, #6e6e7a)">carbon skeletons, WL-colored to stability — count the colors: the histograms match</text>']
# decalin layout: two hexagons sharing the vertical edge 0-1
dec_pos = {0: (185, 110), 1: (185, 178)}
left = hexagon_pts(130, 144, 66, rot=0)
right = hexagon_pts(240, 144, 66, rot=math.pi)
dec_pos.update({5: left[1], 4: left[2], 3: left[3], 2: left[4]})
dec_pos.update({6: right[4], 7: right[3], 8: right[2], 9: right[1]})
# fix: choose ring positions so edges don't cross — recompute simply:
dec_pos = {0: (185, 108), 1: (185, 180),
           2: (128, 214), 3: (70, 180), 4: (70, 108), 5: (128, 74),
           9: (242, 214), 8: (300, 180), 7: (300, 108), 6: (242, 74)}
for a, b in DECALIN.edges():
    (x1, y1), (x2, y2) = dec_pos[a], dec_pos[b]
    mol.append(f'  <line x1="{x1:.0f}" y1="{y1:.0f}" x2="{x2:.0f}" y2="{y2:.0f}" '
               f'stroke="var(--dkr-muted, #8e8e9a)" stroke-width="2"/>')
for v, (x, y) in dec_pos.items():
    mol.append(f'  <circle cx="{x:.0f}" cy="{y:.0f}" r="10" fill="{CLASS_COLOR[cd[v]]}"/>')
# bicyclopentyl layout: two pentagons joined by horizontal bond 0-5
bpos = {}
pentL = {0: (505, 144), 1: (470, 96), 2: (416, 116), 3: (416, 172), 4: (470, 192)}
pentR = {5: (585, 144), 6: (620, 96), 7: (674, 116), 8: (674, 172), 9: (620, 192)}
bpos.update(pentL); bpos.update(pentR)
for a, b in BICYCLO.edges():
    (x1, y1), (x2, y2) = bpos[a], bpos[b]
    mol.append(f'  <line x1="{x1:.0f}" y1="{y1:.0f}" x2="{x2:.0f}" y2="{y2:.0f}" '
               f'stroke="var(--dkr-muted, #8e8e9a)" stroke-width="2"/>')
for v, (x, y) in bpos.items():
    mol.append(f'  <circle cx="{x:.0f}" cy="{y:.0f}" r="10" fill="{CLASS_COLOR[cb[v]]}"/>')
mol.append(f'  <text x="185" y="252" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" '
           f'fill="var(--dkr-text, #1c1c21)">decalin — two fused hexagons</text>')
mol.append(f'  <text x="545" y="252" text-anchor="middle" font-family="{SANS}" font-size="13" font-weight="700" '
           f'fill="var(--dkr-text, #1c1c21)">bicyclopentyl — two pentagons, one bond</text>')
hist_txt = " · ".join(f"{cnt}× class {i}" for i, cnt in sorted(Counter(cd.values()).items()))
mol.append(f'  <text x="380" y="282" text-anchor="middle" font-family="{MONO}" font-size="12.5" '
           f'fill="var(--dkr-muted, #6e6e7a)">both stabilize at: {hist_txt} — 1-WL calls them the same molecule</text>')
write("fig-w9-molecules", "\n".join(mol),
      "The carbon skeletons of decalin (two fused hexagons) and bicyclopentyl (two pentagons joined by a bond), nodes colored by their final WL color — both graphs show the same color counts although the molecules are different",
      height=300)

# ═══════════════ figure 3: the expressiveness ladder ═══════════════════════
la = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" '
      f'fill="var(--dkr-muted, #6e6e7a)">each rung separates pairs the rung below cannot — and charges for it</text>']
RUNGS = [
    ("mean / max MP-GNNs", "below 1-WL", "loses multiset counts ({t} vs {t,t})", "var(--dkr-muted, #8e8e9a)"),
    ("sum-MLP GNNs (GIN) = 1-WL", "the ceiling of message passing", "blind: C&#x2083;&#x222A;C&#x2083; vs C&#x2086;, decalin pair, all CSL graphs", "var(--dkr-blue, #0f8377)"),
    ("1-WL + structural features", "triangle counts, RW returns, Laplacian PEs", "separates the pairs above; costs preprocessing + choices", "var(--dkr-green, #199473)"),
    ("3-WL / higher-order GNNs", "colors pairs of nodes (n&#xB2; objects)", "separates CSL graphs natively; O(n&#xB3;) memory and up", "#7c5cd6"),
]
y = 52
for name, what, sep, color in RUNGS:
    la.append(f'''  <g font-family="{SANS}">
    <rect x="60" y="{y}" width="640" height="64" rx="10" fill="{color}" opacity="0.10"/>
    <rect x="60" y="{y}" width="640" height="64" rx="10" fill="none" stroke="{color}" stroke-width="2"/>
    <text x="80" y="{y + 26}" font-size="14" font-weight="700" fill="{color}">{name}</text>
    <text x="80" y="{y + 47}" font-size="12" fill="var(--dkr-text, #1c1c21)">{what} &#x2014; <tspan fill="var(--dkr-muted, #6e6e7a)">{sep}</tspan></text>
  </g>''')
    y += 78
for i in range(3):
    ay = 52 + 64 + i * 78
    la.append(f'  <line x1="380" y1="{ay}" x2="380" y2="{ay + 14}" stroke="var(--dkr-muted, #8e8e9a)" '
              f'stroke-width="2" marker-end="url(#w9-arr)"/>')
la.insert(1, '''  <defs><marker id="w9-arr" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="6" markerHeight="6" orient="auto">
    <path d="M 0 0 L 10 5 L 0 10 z" fill="var(--dkr-muted, #8e8e9a)"/></marker></defs>''')
write("fig-w9-ladder", "\n".join(la),
      "The expressiveness ladder: mean and max GNNs sit below 1-WL; GIN reaches the 1-WL ceiling; structural features climb past specific blind pairs; 3-WL and higher-order GNNs separate more but cost polynomially more",
      height=y + 8)

# ═══════════════ figure 4: barbell sensitivity, computed ═══════════════════
BPOS = {}
for i in range(5):
    a = -math.pi / 2 + i * 2 * math.pi / 5
    BPOS[i] = (120 + 52 * math.cos(a), 150 + 52 * math.sin(a))
BPOS[5] = (330, 150)
BPOS[6] = (430, 150)
for i in range(5):
    a = -math.pi / 2 + i * 2 * math.pi / 5
    BPOS[7 + i] = (640 - 52 * math.cos(a), 150 + 52 * math.sin(a))
# barbell_graph(5,2): nodes 0-4 clique, 5-6 path, 7-11 clique; bridges 4-5, 6-7
BPOS = {0: BPOS[0], 1: BPOS[1], 2: BPOS[2], 3: BPOS[3], 4: BPOS[4],
        5: (330, 150), 6: (430, 150),
        7: BPOS[7], 8: BPOS[8], 9: BPOS[9], 10: BPOS[10], 11: BPOS[11]}
# put clique bridgeheads nearest the path
BPOS[4] = (172, 150); BPOS[0] = (98, 96); BPOS[1] = (60, 150); BPOS[2] = (98, 204); BPOS[3] = (140, 96)
BPOS[7] = (588, 150); BPOS[8] = (662, 96); BPOS[9] = (700, 150); BPOS[10] = (662, 204); BPOS[11] = (620, 96)
vals = S[SRC]
vmax = vals.max()
sq = [f'  <text x="380" y="24" text-anchor="middle" font-family="{SANS}" font-size="13" '
      f'fill="var(--dkr-muted, #6e6e7a)">how much node 1 (&#x2605;) can influence each node after {K} layers: (&#x00C2;&#x2075;)&#x2081;&#x1D65;, computed exactly</text>']
for a, b in BAR.edges():
    (x1, y1), (x2, y2) = BPOS[a], BPOS[b]
    sq.append(f'  <line x1="{x1:.0f}" y1="{y1:.0f}" x2="{x2:.0f}" y2="{y2:.0f}" '
              f'stroke="var(--dkr-muted, #8e8e9a)" stroke-width="1.6" opacity="0.6"/>')
for v, (x, y) in BPOS.items():
    frac = vals[v] / vmax
    rr = 9 + 11 * math.sqrt(frac)
    sq.append(f'  <circle cx="{x:.0f}" cy="{y:.0f}" r="{rr:.1f}" fill="var(--dkr-accent, #d9603b)" '
              f'opacity="{0.25 + 0.75 * frac:.2f}"/>')
    label = f"{vals[v]:.3f}" if vals[v] >= 5e-3 else f"{vals[v]:.0e}"
    yoff = -18 if y < 150 else 30
    sq.append(f'  <text x="{x:.0f}" y="{y + yoff:.0f}" text-anchor="middle" font-family="{MONO}" '
              f'font-size="12" fill="var(--dkr-text, #1c1c21)">{label}</text>')
sq.append(f'  <text x="{BPOS[SRC][0]:.0f}" y="{BPOS[SRC][1] + 5:.0f}" text-anchor="middle" '
          f'font-size="13" fill="var(--dkr-bg, #fff)" font-weight="700">&#x2605;</text>')
sq.append(f'''  <g font-family="{SANS}">
    <rect x="62" y="252" width="636" height="30" rx="15" fill="var(--dkr-blue, #0f8377)"/>
    <text x="380" y="272" text-anchor="middle" font-size="13" font-weight="700" fill="var(--dkr-bg, #fff)">same clique: {sens_near:.3f} &#xB7; across the bridge: {sens_far:.0e} &#x2014; a {ratio:.0f}&#xD7; crush; one added edge buys {rescue:.0f}&#xD7; back</text>
  </g>''')
write("fig-w9-squash", "\n".join(sq),
      f"A barbell graph of two five-cliques joined by a two-node path, each node labeled with how much the starred source node can influence it after {K} propagation layers — influence within the source clique is around {sens_near:.3f} while across the bridge it collapses to about {sens_far:.0e}",
      height=300)

print("\nall Week 9 claims verified")
